VeriSol: SolidityAST.ModifierDefinition Class Reference
SolidityAST.ModifierDefinition Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
Block Body [get, set]
string Documentation [get, set]
string Name [get, set]
EnumVisibility Visibility [get, set]
Properties inherited from SolidityAST.CallableDeclaration
ParameterList Parameters [get, set]
ParameterList ReturnParameters [get, set]
Properties inherited from SolidityAST.Declaration
int Scope [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 531 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.ModifierDefinition.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 542 of file SolidityAST.cs.
References SolidityAST.ParameterList.Accept(), SolidityAST.Block.Accept(), SolidityAST.ModifierDefinition.Body, SolidityAST.IASTVisitor.EndVisit(), SolidityAST.CallableDeclaration.Parameters, and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.ModifierDefinition.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 552 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.ModifierDefinition.ToString () inline
Definition at line 557 of file SolidityAST.cs.
References SolidityAST.ModifierDefinition.Body, SolidityAST.ModifierDefinition.Name, and SolidityAST.CallableDeclaration.Parameters.
Property Documentation
Body
Block SolidityAST.ModifierDefinition.Body get set
Definition at line 533 of file SolidityAST.cs.
Referenced by SolidityAST.ModifierDefinition.Accept(), SolidityAST.ModifierDefinition.ToString(), and SolToBoogie.ProcedureTranslator.Visit().
Documentation
string SolidityAST.ModifierDefinition.Documentation get set
Definition at line 535 of file SolidityAST.cs.
Name
string SolidityAST.ModifierDefinition.Name get set
Definition at line 537 of file SolidityAST.cs.
Referenced by SolidityAST.ModifierDefinition.ToString(), and SolToBoogie.ProcedureTranslator.Visit().
Visibility
EnumVisibility SolidityAST.ModifierDefinition.Visibility get set
Definition at line 540 of file SolidityAST.cs.
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs