VeriSol: VeriSolRunner.ExternalTools.ToolManager Class Reference
VeriSolRunner.ExternalTools.ToolManager Class Reference abstract
Protected Member Functions
bool Exists ()
void EnsureCommandPathExisted ()
Protected Attributes
readonly ToolSourceSettings settings
Package Functions
ToolManager (ToolSourceSettings settings)
abstract void EnsureExisted ()
Properties
static string OsName [get]
string ExeName [get]
string Command [get]
Detailed Description
Definition at line 6 of file ToolManager.cs.
Constructor & Destructor Documentation
ToolManager()
VeriSolRunner.ExternalTools.ToolManager.ToolManager (ToolSourceSettings settings) inline package
Definition at line 51 of file ToolManager.cs.
References VeriSolRunner.ExternalTools.ToolManager.settings.
Member Function Documentation
EnsureCommandPathExisted()
void VeriSolRunner.ExternalTools.ToolManager.EnsureCommandPathExisted () inline protected
Definition at line 63 of file ToolManager.cs.
Referenced by VeriSolRunner.ExternalTools.DotnetCliToolManager.EnsureExisted(), and VeriSolRunner.ExternalTools.DownloadedToolManager.EnsureExisted().
EnsureExisted()
abstract void VeriSolRunner.ExternalTools.ToolManager.EnsureExisted () package pure virtual
Implemented in VeriSolRunner.ExternalTools.DownloadedToolManager, and VeriSolRunner.ExternalTools.DotnetCliToolManager.
Referenced by VeriSolRunner.ExternalTools.ExternalToolsManager.EnsureAllExisted().
Exists()
bool VeriSolRunner.ExternalTools.ToolManager.Exists () inline protected
Definition at line 58 of file ToolManager.cs.
References VeriSolRunner.ExternalTools.ToolManager.Command.
Referenced by VeriSolRunner.ExternalTools.DotnetCliToolManager.EnsureExisted(), and VeriSolRunner.ExternalTools.DownloadedToolManager.EnsureExisted().
Member Data Documentation
settings
readonly ToolSourceSettings VeriSolRunner.ExternalTools.ToolManager.settings protected
Definition at line 26 of file ToolManager.cs.
Referenced by VeriSolRunner.ExternalTools.ToolManager.ToolManager().
Property Documentation
Command
string VeriSolRunner.ExternalTools.ToolManager.Command get
Definition at line 43 of file ToolManager.cs.
Referenced by VeriSolRunner.ExternalTools.DownloadedToolManager.CopyToCommand(), VeriSolRunner.ExternalTools.DotnetCliToolManager.EnsureLinkedToZ3(), VeriSolRunner.ExternalTools.ToolManager.Exists(), SolToBoogieTest.RegressionExecutor.RegressionExecutor(), and VeriSolRunner.VeriSolExecutor.VeriSolExecutor().
ExeName
string VeriSolRunner.ExternalTools.ToolManager.ExeName get
Definition at line 28 of file ToolManager.cs.
Referenced by VeriSolRunner.ExternalTools.DotnetCliToolManager.GetZ3DependencyPath().
OsName
string VeriSolRunner.ExternalTools.ToolManager.OsName static get protected
Definition at line 8 of file ToolManager.cs.
Referenced by VeriSolRunner.ExternalTools.DownloadedToolManager.ChangePermission(), VeriSolRunner.ExternalTools.DownloadedToolManager.CreateSymbolicLink(), and VeriSolRunner.ExternalTools.SolcManager.Install().
The documentation for this class was generated from the following file:
Sources/ExternalToolsManager/ToolManager.cs