VeriSol: SolToBoogie.MapArrayHelper Class Reference
SolToBoogie.MapArrayHelper Class Reference
Static Public Member Functions
static string GetMemoryMapName (BoogieType keyType, BoogieType valType)
static BoogieExpr GetMemoryMapSelectExpr (BoogieType mapKeyType, BoogieType mapValType, BoogieExpr baseExpr, BoogieExpr indexExpr)
static BoogieType InferExprTypeFromTypeString (string typeString)
static BoogieType InferKeyTypeFromTypeString (string typeString)
static BoogieType InferValueTypeFromTypeString (string typeString)
static string GetValueTypeString (string typeString)
static bool IsMappingTypeString (string typeString)
static bool IsArrayTypeString (string typeString)
Static Private Attributes
static Regex mappingRegex = new Regex(@"mapping\((\w+)\s*\w*\s*=>\s*(.+)\‍)$")
static Regex arrayRegex = new Regex(@"(.+)\[\w*\] (storage ref|storage pointer|memory|calldata)$")
Detailed Description
Definition at line 9 of file MapArrayHelper.cs.
Member Function Documentation
GetMemoryMapName()
static string SolToBoogie.MapArrayHelper.GetMemoryMapName (BoogieType keyType, BoogieType valType) inline static
Definition at line 17 of file MapArrayHelper.cs.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateSingleMemoryVariable(), SolToBoogie.ProcedureTranslator.GetBoogieTypesFromMapping(), SolToBoogie.MapArrayHelper.GetMemoryMapSelectExpr(), SolToBoogie.ProcedureTranslator.InitializeNestedArrayMappingStateVar(), SolToBoogie.ProcedureTranslator.TranslateModifiesStmt(), SolToBoogie.ProcedureTranslator.TranslateVeriSolCodeContractFuncCall(), and SolToBoogie.ProcedureTranslator.Visit().
GetMemoryMapSelectExpr()
static BoogieExpr SolToBoogie.MapArrayHelper.GetMemoryMapSelectExpr (BoogieType mapKeyType, BoogieType mapValType, BoogieExpr baseExpr, BoogieExpr indexExpr) inline static
Definition at line 22 of file MapArrayHelper.cs.
References SolToBoogie.MapArrayHelper.GetMemoryMapName().
Referenced by SolToBoogie.ProcedureTranslator.TranslateDynamicArrayPush(), and SolToBoogie.ProcedureTranslator.Visit().
GetValueTypeString()
static string SolToBoogie.MapArrayHelper.GetValueTypeString (string typeString) inline static
Definition at line 136 of file MapArrayHelper.cs.
References SolToBoogie.MapArrayHelper.arrayRegex, and SolToBoogie.MapArrayHelper.mappingRegex.
Referenced by SolToBoogie.ProcedureTranslator.Visit().
InferExprTypeFromTypeString()
static BoogieType SolToBoogie.MapArrayHelper.InferExprTypeFromTypeString (string typeString) inline static
Definition at line 31 of file MapArrayHelper.cs.
References BoogieAST.BoogieType.Bool, BoogieAST.BoogieType.Int, SolToBoogie.MapArrayHelper.IsArrayTypeString(), SolToBoogie.MapArrayHelper.IsMappingTypeString(), and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.ProcedureTranslator.GetBoogieTypesFromMapping(), SolToBoogie.MapArrayHelper.InferKeyTypeFromTypeString(), SolToBoogie.MapArrayHelper.InferValueTypeFromTypeString(), SolToBoogie.ProcedureTranslator.InitializeNestedArrayMappingStateVar(), SolToBoogie.ProcedureTranslator.MkNewLocalVariableForFunctionReturn(), SolToBoogie.ProcedureTranslator.TranslateDynamicArrayPush(), and SolToBoogie.ProcedureTranslator.Visit().
InferKeyTypeFromTypeString()
static BoogieType SolToBoogie.MapArrayHelper.InferKeyTypeFromTypeString (string typeString) inline static
Definition at line 84 of file MapArrayHelper.cs.
References SolToBoogie.MapArrayHelper.arrayRegex, SolToBoogie.MapArrayHelper.InferExprTypeFromTypeString(), BoogieAST.BoogieType.Int, SolToBoogie.MapArrayHelper.mappingRegex, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.ProcedureTranslator.Visit().
InferValueTypeFromTypeString()
static BoogieType SolToBoogie.MapArrayHelper.InferValueTypeFromTypeString (string typeString) inline static
Definition at line 110 of file MapArrayHelper.cs.
References SolToBoogie.MapArrayHelper.arrayRegex, SolToBoogie.MapArrayHelper.InferExprTypeFromTypeString(), BoogieAST.BoogieType.Int, SolToBoogie.MapArrayHelper.mappingRegex, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.ProcedureTranslator.Visit().
IsArrayTypeString()
static bool SolToBoogie.MapArrayHelper.IsArrayTypeString (string typeString) inline static
Definition at line 158 of file MapArrayHelper.cs.
References SolToBoogie.MapArrayHelper.arrayRegex.
Referenced by SolToBoogie.MapArrayHelper.InferExprTypeFromTypeString(), SolToBoogie.ProcedureTranslator.IsDynamicArrayPush(), and SolToBoogie.ProcedureTranslator.Visit().
IsMappingTypeString()
static bool SolToBoogie.MapArrayHelper.IsMappingTypeString (string typeString) inline static
Definition at line 153 of file MapArrayHelper.cs.
References SolToBoogie.MapArrayHelper.mappingRegex.
Referenced by SolToBoogie.MapArrayHelper.InferExprTypeFromTypeString(), and SolToBoogie.ProcedureTranslator.Visit().
Member Data Documentation
arrayRegex
Regex SolToBoogie.MapArrayHelper.arrayRegex = new Regex(@"(.+)\[\w*\] (storage ref|storage pointer|memory|calldata)$") static private
Definition at line 13 of file MapArrayHelper.cs.
Referenced by SolToBoogie.MapArrayHelper.GetValueTypeString(), SolToBoogie.MapArrayHelper.InferKeyTypeFromTypeString(), SolToBoogie.MapArrayHelper.InferValueTypeFromTypeString(), and SolToBoogie.MapArrayHelper.IsArrayTypeString().
mappingRegex
Regex SolToBoogie.MapArrayHelper.mappingRegex = new Regex(@"mapping\((\w+)\s*\w*\s*=>\s*(.+)\‍)$") static private
Definition at line 11 of file MapArrayHelper.cs.
Referenced by SolToBoogie.MapArrayHelper.GetValueTypeString(), SolToBoogie.MapArrayHelper.InferKeyTypeFromTypeString(), SolToBoogie.MapArrayHelper.InferValueTypeFromTypeString(), and SolToBoogie.MapArrayHelper.IsMappingTypeString().
The documentation for this class was generated from the following file:
Sources/SolToBoogie/MapArrayHelper.cs