VeriSol: SolToBoogie.InheritanceCollector Class Reference
SolToBoogie.InheritanceCollector Class Reference
Public Member Functions
InheritanceCollector (TranslatorContext context)
void Collect ()
Private Attributes
TranslatorContext context
Detailed Description
Definition at line 8 of file InheritanceCollector.cs.
Constructor & Destructor Documentation
InheritanceCollector()
SolToBoogie.InheritanceCollector.InheritanceCollector (TranslatorContext context) inline
Definition at line 13 of file InheritanceCollector.cs.
References SolToBoogie.InheritanceCollector.context.
Member Function Documentation
Collect()
void SolToBoogie.InheritanceCollector.Collect () inline
Definition at line 18 of file InheritanceCollector.cs.
References SolToBoogie.TranslatorContext.AddSubTypeToContract(), SolToBoogie.InheritanceCollector.context, SolToBoogie.TranslatorContext.ContractDefinitions, SolToBoogie.TranslatorContext.GetASTNodeById(), and SolidityAST.ContractDefinition.LinearizedBaseContracts.
Referenced by SolToBoogie.BoogieTranslator.Translate().
Member Data Documentation
context
TranslatorContext SolToBoogie.InheritanceCollector.context private
Definition at line 11 of file InheritanceCollector.cs.
Referenced by SolToBoogie.InheritanceCollector.Collect(), and SolToBoogie.InheritanceCollector.InheritanceCollector().
The documentation for this class was generated from the following file:
Sources/SolToBoogie/InheritanceCollector.cs