VeriSol: SolidityAST.StructDefinition Class Reference
SolidityAST.StructDefinition Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
string CanonicalName [get, set]
string Name [get, set]
List< VariableDeclaration > Members [get, set]
EnumVisibility Visibility [get, set]
Properties inherited from SolidityAST.Declaration
int Scope [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 639 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.StructDefinition.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 650 of file SolidityAST.cs.
References SolidityAST.IASTVisitor.EndVisit(), SolidityAST.StructDefinition.Members, and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.StructDefinition.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 659 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.StructDefinition.ToString () inline
Definition at line 664 of file SolidityAST.cs.
References SolidityAST.StructDefinition.Members, and SolidityAST.StructDefinition.Name.
Property Documentation
CanonicalName
string SolidityAST.StructDefinition.CanonicalName get set
Definition at line 641 of file SolidityAST.cs.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateStructConstructors().
Members
List<VariableDeclaration> SolidityAST.StructDefinition.Members get set
Definition at line 645 of file SolidityAST.cs.
Referenced by SolidityAST.StructDefinition.Accept(), and SolidityAST.StructDefinition.ToString().
Name
string SolidityAST.StructDefinition.Name get set
Definition at line 643 of file SolidityAST.cs.
Referenced by SolidityAST.StructDefinition.ToString().
Visibility
EnumVisibility SolidityAST.StructDefinition.Visibility get set
Definition at line 648 of file SolidityAST.cs.
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs