VeriSol: SolidityAST.SourceUnitList Class Reference
SolidityAST.SourceUnitList Class Reference
Public Member Functions
SourceUnitList ()
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
void AddSourceUnit (string filename, SourceUnit sourceUnit)
bool ContainsFilename (string filename)
SourceUnit GetSourceUnitByFilename (string filename)
override string ToString ()
Properties
Dictionary< string, SourceUnit > FilenameToSourceUnitMap [get, private set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 91 of file SolidityAST.cs.
Constructor & Destructor Documentation
SourceUnitList()
SolidityAST.SourceUnitList.SourceUnitList () inline
Definition at line 95 of file SolidityAST.cs.
References SolidityAST.SourceUnitList.FilenameToSourceUnitMap, SolidityAST.ASTNode.Id, SolidityAST.ASTNode.NodeType, and SolidityAST.ASTNode.Src.
Member Function Documentation
Accept()
override void SolidityAST.SourceUnitList.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 104 of file SolidityAST.cs.
References SolidityAST.IASTVisitor.EndVisit(), SolidityAST.SourceUnitList.FilenameToSourceUnitMap, and SolidityAST.IASTVisitor.Visit().
Referenced by SolToBoogie.BoogieTranslator.Translate().
Accept< T >()
override T SolidityAST.SourceUnitList.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 116 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
AddSourceUnit()
void SolidityAST.SourceUnitList.AddSourceUnit (string filename, SourceUnit sourceUnit) inline
Definition at line 121 of file SolidityAST.cs.
References SolidityAST.SourceUnitList.FilenameToSourceUnitMap.
ContainsFilename()
bool SolidityAST.SourceUnitList.ContainsFilename (string filename) inline
Definition at line 126 of file SolidityAST.cs.
References SolidityAST.SourceUnitList.FilenameToSourceUnitMap.
GetSourceUnitByFilename()
SourceUnit SolidityAST.SourceUnitList.GetSourceUnitByFilename (string filename) inline
Definition at line 131 of file SolidityAST.cs.
References SolidityAST.SourceUnitList.FilenameToSourceUnitMap.
ToString()
override string SolidityAST.SourceUnitList.ToString () inline
Definition at line 136 of file SolidityAST.cs.
References SolidityAST.SourceUnitList.FilenameToSourceUnitMap.
Property Documentation
FilenameToSourceUnitMap
Dictionary<string, SourceUnit> SolidityAST.SourceUnitList.FilenameToSourceUnitMap get private set
Definition at line 93 of file SolidityAST.cs.
Referenced by SolidityAST.SourceUnitList.Accept(), SolidityAST.SourceUnitList.AddSourceUnit(), SolidityAST.SourceUnitList.ContainsFilename(), SolidityAST.SourceUnitList.GetSourceUnitByFilename(), SolidityAST.SourceUnitList.SourceUnitList(), and SolidityAST.SourceUnitList.ToString().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs