VeriSol: SolToBoogie.Extensions Class Reference
SolToBoogie.Extensions Class Reference
Static Public Member Functions
static bool IsInt (this TypeDescription typeDescription)
static bool IsIntWSize (this TypeDescription typeDescription, out uint sz)
static bool IsUint (this TypeDescription typeDescription)
static string GetNumberFromEnd (string text)
static bool IsUintWSize (this TypeDescription typeDescription, Expression expr, out uint sz)
static bool IsUintConst (this TypeDescription typeDescription, Expression constant, out BigInteger value, out uint sz)
static bool IsBool (this TypeDescription typeDescription)
static bool IsString (this TypeDescription typeDescription)
static bool IsAddress (this TypeDescription typeDescription)
static bool IsBytes (this TypeDescription typeDescription)
static bool IsStruct (this TypeDescription typeDescription)
static bool IsContract (this TypeDescription typeDescription)
static bool IsEnum (this TypeDescription typeDescription)
static bool IsElementaryType (this TypeDescription typeDescription)
static bool IsDynamicArray (this TypeDescription typeDescription)
static bool IsStaticArray (this TypeDescription typeDescription)
static bool IsArray (this TypeDescription typeDescription)
Static Private Member Functions
static int GetConstantSize (BigInteger constant)
Detailed Description
Definition at line 15 of file TransUtils.cs.
Member Function Documentation
GetConstantSize()
static int SolToBoogie.Extensions.GetConstantSize (BigInteger constant) inline static private
Definition at line 71 of file TransUtils.cs.
Referenced by SolToBoogie.Extensions.IsUintConst().
GetNumberFromEnd()
static string SolToBoogie.Extensions.GetNumberFromEnd (string text) inline static
Definition at line 59 of file TransUtils.cs.
Referenced by SolToBoogie.Extensions.IsIntWSize(), SolToBoogie.Extensions.IsUintConst(), SolToBoogie.Extensions.IsUintWSize(), and SolToBoogie.ProcedureTranslator.TranslateTypeCast().
IsAddress()
static bool SolToBoogie.Extensions.IsAddress (this TypeDescription typeDescription) inline static
Definition at line 226 of file TransUtils.cs.
References SolidityAST.TypeDescription.TypeString.
IsArray()
static bool SolToBoogie.Extensions.IsArray (this TypeDescription typeDescription) inline static
Definition at line 274 of file TransUtils.cs.
References SolToBoogie.Extensions.IsDynamicArray(), and SolToBoogie.Extensions.IsStaticArray().
IsBool()
static bool SolToBoogie.Extensions.IsBool (this TypeDescription typeDescription) inline static
Definition at line 214 of file TransUtils.cs.
References SolidityAST.TypeDescription.TypeString.
IsBytes()
static bool SolToBoogie.Extensions.IsBytes (this TypeDescription typeDescription) inline static
Definition at line 234 of file TransUtils.cs.
References SolidityAST.TypeDescription.TypeString.
IsContract()
static bool SolToBoogie.Extensions.IsContract (this TypeDescription typeDescription) inline static
Definition at line 245 of file TransUtils.cs.
References SolidityAST.TypeDescription.TypeString.
IsDynamicArray()
static bool SolToBoogie.Extensions.IsDynamicArray (this TypeDescription typeDescription) inline static
Definition at line 261 of file TransUtils.cs.
References SolidityAST.TypeDescription.TypeString.
Referenced by SolToBoogie.Extensions.IsArray().
IsElementaryType()
static bool SolToBoogie.Extensions.IsElementaryType (this TypeDescription typeDescription) inline static
Definition at line 255 of file TransUtils.cs.
IsEnum()
static bool SolToBoogie.Extensions.IsEnum (this TypeDescription typeDescription) inline static
Definition at line 250 of file TransUtils.cs.
References SolidityAST.TypeDescription.TypeString.
IsInt()
static bool SolToBoogie.Extensions.IsInt (this TypeDescription typeDescription) inline static
Definition at line 17 of file TransUtils.cs.
References SolidityAST.TypeDescription.TypeString.
IsIntWSize()
static bool SolToBoogie.Extensions.IsIntWSize (this TypeDescription typeDescription, out uint sz) inline static
Definition at line 23 of file TransUtils.cs.
References SolToBoogie.Extensions.GetNumberFromEnd(), and SolidityAST.TypeDescription.TypeString.
IsStaticArray()
static bool SolToBoogie.Extensions.IsStaticArray (this TypeDescription typeDescription) inline static
Definition at line 268 of file TransUtils.cs.
References SolidityAST.TypeDescription.TypeString.
Referenced by SolToBoogie.Extensions.IsArray().
IsString()
static bool SolToBoogie.Extensions.IsString (this TypeDescription typeDescription) inline static
Definition at line 220 of file TransUtils.cs.
References SolidityAST.TypeDescription.TypeString.
IsStruct()
static bool SolToBoogie.Extensions.IsStruct (this TypeDescription typeDescription) inline static
Definition at line 240 of file TransUtils.cs.
References SolidityAST.TypeDescription.TypeString.
IsUint()
static bool SolToBoogie.Extensions.IsUint (this TypeDescription typeDescription) inline static
Definition at line 53 of file TransUtils.cs.
References SolidityAST.TypeDescription.TypeString.
IsUintConst()
static bool SolToBoogie.Extensions.IsUintConst (this TypeDescription typeDescription, Expression constant, out BigInteger value, out uint sz) inline static
Definition at line 125 of file TransUtils.cs.
References SolToBoogie.Extensions.GetConstantSize(), SolToBoogie.Extensions.GetNumberFromEnd(), SolidityAST.BinaryOperation.LeftExpression, SolidityAST.BinaryOperation.RightExpression, SolidityAST.TypeDescription.ToString(), SolidityAST.Expression.TypeDescriptions, and SolidityAST.TypeDescription.TypeString.
Referenced by SolToBoogie.Extensions.IsUintWSize().
IsUintWSize()
static bool SolToBoogie.Extensions.IsUintWSize (this TypeDescription typeDescription, Expression expr, out uint sz) inline static
Definition at line 90 of file TransUtils.cs.
References SolToBoogie.Extensions.GetNumberFromEnd(), SolToBoogie.Extensions.IsUintConst(), and SolidityAST.TypeDescription.TypeString.
The documentation for this class was generated from the following file:
Sources/SolToBoogie/TransUtils.cs