VeriSol: VeriSolRunner.Program Class Reference
VeriSolRunner.Program Class Reference
Top level application to run VeriSol to target proofs as well as scalable counterexamples
Static Public Member Functions
static int Main (string[] args)
Static Private Member Functions
static void ShowUsage ()
static string GetSolcNameByOSPlatform ()
Detailed Description
Top level application to run VeriSol to target proofs as well as scalable counterexamples
Definition at line 17 of file Program.cs.
Member Function Documentation
GetSolcNameByOSPlatform()
static string VeriSolRunner.Program.GetSolcNameByOSPlatform () inline static private
Definition at line 96 of file Program.cs.
Main()
static int VeriSolRunner.Program.Main (string[] args) inline static
Definition at line 19 of file Program.cs.
References VeriSolRunner.ExternalTools.ExternalToolsManager.EnsureAllExisted(), SolToBoogie.ParseUtils.ParseCommandLineArgs(), and VeriSolRunner.Program.ShowUsage().
ShowUsage()
static void VeriSolRunner.Program.ShowUsage () inline static private
Definition at line 62 of file Program.cs.
Referenced by VeriSolRunner.Program.Main().
The documentation for this class was generated from the following file:
Sources/VeriSol/Program.cs