VeriSol: BoogieAST.BoogieStmtList Class Reference
BoogieAST.BoogieStmtList Class Reference
Public Member Functions
BoogieStmtList ()
int StatementCount ()
void AddStatement (BoogieCmd cmd)
void AppendStmtList (BoogieStmtList stmtList)
override string ToString ()
Static Public Member Functions
static BoogieStmtList MakeSingletonStmtList (BoogieCmd cmd)
Properties
List< BoogieBigBlock > BigBlocks [get, private set]
Detailed Description
Definition at line 582 of file BoogieAST.cs.
Constructor & Destructor Documentation
BoogieStmtList()
BoogieAST.BoogieStmtList.BoogieStmtList () inline
Definition at line 586 of file BoogieAST.cs.
References BoogieAST.BoogieStmtList.BigBlocks.
Referenced by BoogieAST.BoogieStmtList.MakeSingletonStmtList().
Member Function Documentation
AddStatement()
void BoogieAST.BoogieStmtList.AddStatement (BoogieCmd cmd) inline
Definition at line 605 of file BoogieAST.cs.
References BoogieAST.BoogieStmtList.BigBlocks.
Referenced by SolToBoogie.ProcedureTranslator.AddUnsignedTypeAssumeCmd(), SolToBoogie.ProcedureTranslator.CreateDistinctArrayMappingAddress(), SolToBoogie.RevertLogicGenerator.CreateSendSucess(), SolToBoogie.ProcedureTranslator.emitGasCheck(), SolToBoogie.ProcedureTranslator.emitRevertLogic(), SolToBoogie.FallbackGenerator.Generate(), SolToBoogie.RevertLogicGenerator.Generate(), SolToBoogie.HarnessGenerator.GenerateBoogieHarnessForContract(), SolToBoogie.HarnessGenerator.GenerateCorralChoiceProcForContract(), SolToBoogie.HarnessGenerator.GenerateCorralHarnessForContract(), SolToBoogie.HarnessGenerator.GenerateCorralWhileLoop(), SolToBoogie.ProcedureTranslator.GenerateDefaultConstructor(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalProcedureAllocMany(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalProcedureFresh(), SolToBoogie.ProcedureTranslator.GenerateInitializationForArrayStateVar(), SolToBoogie.ProcedureTranslator.GenerateInitializationForElementaryTypes(), SolToBoogie.ProcedureTranslator.GenerateInitializationForMappingStateVar(), SolToBoogie.ProcedureTranslator.GenerateInitializationForStructStateVar(), SolToBoogie.ProcedureTranslator.GenerateInitializationStmts(), SolToBoogie.ProcedureTranslator.GenerateNonDetExpr(), SolToBoogie.RevertLogicGenerator.generateRevertLogicForCmd(), SolToBoogie.HarnessGenerator.GenerateWhileLoop(), SolToBoogie.TransUtils.havocGas(), SolToBoogie.ProcedureTranslator.InitializeNestedArrayMappingStateVar(), SolToBoogie.ProcedureTranslator.preTranslationAction(), SolToBoogie.ProcedureTranslator.PrintArguments(), SolToBoogie.ProcedureTranslator.TranslateAbiEncodedFuncCall(), SolToBoogie.ProcedureTranslator.TranslateCallStatement(), SolToBoogie.ProcedureTranslator.TranslateDynamicArrayPush(), SolToBoogie.ProcedureTranslator.TranslateDynamicDispatchCall(), SolToBoogie.ProcedureTranslator.TranslateInternalFunctionCall(), SolToBoogie.ProcedureTranslator.TranslateKeccakFuncCall(), SolToBoogie.ProcedureTranslator.TranslateNewStatement(), SolToBoogie.ProcedureTranslator.TranslateSendCallStmt(), SolToBoogie.ProcedureTranslator.TranslateStructConstructor(), SolToBoogie.ProcedureTranslator.TranslateTransferCallStmt(), SolToBoogie.ProcedureTranslator.TranslateTypeCast(), SolToBoogie.ProcedureTranslator.TranslateUsingLibraryCall(), SolToBoogie.ProcedureTranslator.updateAssignedSums(), and SolToBoogie.ProcedureTranslator.Visit().
AppendStmtList()
void BoogieAST.BoogieStmtList.AppendStmtList (BoogieStmtList stmtList) inline
Definition at line 611 of file BoogieAST.cs.
References BoogieAST.BoogieStmtList.BigBlocks.
Referenced by SolToBoogie.ProcedureTranslator.AddAssumeForUints(), SolToBoogie.FallbackGenerator.Generate(), SolToBoogie.ProcedureTranslator.TranslateStatement(), and SolToBoogie.ProcedureTranslator.Visit().
MakeSingletonStmtList()
static BoogieStmtList BoogieAST.BoogieStmtList.MakeSingletonStmtList (BoogieCmd cmd) inline static
Definition at line 598 of file BoogieAST.cs.
References BoogieAST.BoogieStmtList.BigBlocks, and BoogieAST.BoogieStmtList.BoogieStmtList().
Referenced by SolToBoogie.ProcedureTranslator.AddAssumeForUints(), SolToBoogie.FallbackGenerator.CreateBodyOfSend(), SolToBoogie.RevertLogicGenerator.CreateSendFail(), SolToBoogie.RevertLogicGenerator.CreateSendSucess(), SolToBoogie.FallbackGenerator.GenerateBodyOfFallbackDispatch(), SolToBoogie.TransUtils.GenerateChoiceBlock(), SolToBoogie.ProcedureTranslator.TranslateDynamicDispatchCall(), SolToBoogie.ProcedureTranslator.TranslateSendCallStmt(), SolToBoogie.ProcedureTranslator.TranslateStatement(), SolToBoogie.ProcedureTranslator.TranslateTransferCallStmt(), and SolToBoogie.ProcedureTranslator.Visit().
StatementCount()
int BoogieAST.BoogieStmtList.StatementCount () inline
Definition at line 592 of file BoogieAST.cs.
References BoogieAST.BoogieStmtList.BigBlocks.
Referenced by BoogieAST.BoogieIfCmd.ToString().
ToString()
override string BoogieAST.BoogieStmtList.ToString () inline
Definition at line 620 of file BoogieAST.cs.
References BoogieAST.BoogieStmtList.BigBlocks.
Property Documentation
BigBlocks
List<BoogieBigBlock> BoogieAST.BoogieStmtList.BigBlocks get private set
Definition at line 584 of file BoogieAST.cs.
Referenced by BoogieAST.BoogieStmtList.AddStatement(), BoogieAST.BoogieStmtList.AppendStmtList(), BoogieAST.BoogieStmtList.BoogieStmtList(), SolToBoogie.RevertLogicGenerator.generateRevertLogicForCmd(), BoogieAST.BoogieStmtList.MakeSingletonStmtList(), BoogieAST.BoogieStmtList.StatementCount(), BoogieAST.BoogieStmtList.ToString(), and BoogieAST.BoogieIfCmd.ToString().
The documentation for this class was generated from the following file:
Sources/BoogieAST/BoogieAST.cs