VeriSol: SolidityAST.EnumDefinition Class Reference
SolidityAST.EnumDefinition Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
string CanonicalName [get, set]
string Name [get, set]
List< EnumValue > Members [get, set]
Properties inherited from SolidityAST.Declaration
int Scope [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 677 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.EnumDefinition.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 685 of file SolidityAST.cs.
References SolidityAST.IASTVisitor.EndVisit(), SolidityAST.EnumDefinition.Members, and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.EnumDefinition.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 694 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.EnumDefinition.ToString () inline
Definition at line 699 of file SolidityAST.cs.
References SolidityAST.EnumDefinition.Members, and SolidityAST.EnumDefinition.Name.
Property Documentation
CanonicalName
string SolidityAST.EnumDefinition.CanonicalName get set
Definition at line 679 of file SolidityAST.cs.
Members
List<EnumValue> SolidityAST.EnumDefinition.Members get set
Definition at line 683 of file SolidityAST.cs.
Referenced by SolidityAST.EnumDefinition.Accept(), SolToBoogie.TransUtils.GetEnumValueIndex(), and SolidityAST.EnumDefinition.ToString().
Name
string SolidityAST.EnumDefinition.Name get set
Definition at line 681 of file SolidityAST.cs.
Referenced by SolidityAST.EnumDefinition.ToString().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs