VeriSol: SolToBoogie.ProcedureTranslator Class Reference
SolToBoogie.ProcedureTranslator Class Reference
Public Member Functions
ProcedureTranslator (TranslatorContext context, bool _genInlineAttrsInBpl=true)
override bool Visit (ContractDefinition node)
override bool Visit (EnumDefinition node)
override bool Visit (FunctionDefinition node)
override bool Visit (ModifierDefinition node)
BoogieAssignCmd adjustSum (BoogieBinaryOperation.Opcode op, BoogieExpr sumInd, BoogieExpr amt)
override bool Visit (ParameterList node)
BoogieStmtList TranslateStatement (Statement node)
This the only method that returns a BoogieStmtList (value of currentStmtList)
override bool Visit (Block node)
override bool Visit (PlaceholderStatement node)
override bool Visit (VariableDeclarationStatement node)
void updateAssignedSums (BoogieBinaryOperation.Opcode op, List< Expression > exprs, List< BoogieExpr > boogieExprs)
override bool Visit (Assignment node)
override bool Visit (Return node)
override bool Visit (Throw node)
override bool Visit (IfStatement node)
override bool Visit (WhileStatement node)
override bool Visit (ForStatement node)
override bool Visit (DoWhileStatement node)
override bool Visit (Break node)
override bool Visit (Continue node)
override bool Visit (ExpressionStatement node)
override bool Visit (Literal node)
override bool Visit (Identifier node)
override bool Visit (MemberAccess node)
override bool Visit (FunctionCall node)
override bool Visit (UnaryOperation node)
override bool Visit (BinaryOperation node)
override bool Visit (Conditional node)
override bool Visit (IndexAccess node)
override bool Visit (InlineAssembly node)
override bool Equals (object obj)
Public Member Functions inherited from SolidityAST.BasicASTVisitor
virtual bool Visit (SourceUnitList node)
virtual bool Visit (SourceUnit node)
virtual bool Visit (PragmaDirective node)
virtual bool Visit (UsingForDirective node)
virtual bool Visit (ImportDirective node)
virtual bool Visit (InheritanceSpecifier node)
virtual bool Visit (ModifierInvocation node)
virtual bool Visit (EventDefinition node)
virtual bool Visit (StructDefinition node)
virtual bool Visit (EnumValue node)
virtual bool Visit (VariableDeclaration node)
virtual bool Visit (ElementaryTypeName node)
virtual bool Visit (UserDefinedTypeName node)
virtual bool Visit (Mapping node)
virtual bool Visit (ArrayTypeName node)
virtual bool Visit (EmitStatement node)
virtual bool Visit (ElementaryTypeNameExpression node)
virtual bool Visit (TupleExpression node)
virtual bool Visit (NewExpression node)
virtual void EndVisit (SourceUnitList node)
virtual void EndVisit (SourceUnit node)
virtual void EndVisit (PragmaDirective node)
virtual void EndVisit (UsingForDirective node)
virtual void EndVisit (ImportDirective node)
virtual void EndVisit (ContractDefinition node)
virtual void EndVisit (InheritanceSpecifier node)
virtual void EndVisit (FunctionDefinition node)
virtual void EndVisit (ParameterList node)
virtual void EndVisit (ModifierDefinition node)
virtual void EndVisit (ModifierInvocation node)
virtual void EndVisit (EventDefinition node)
virtual void EndVisit (StructDefinition node)
virtual void EndVisit (EnumDefinition node)
virtual void EndVisit (EnumValue node)
virtual void EndVisit (VariableDeclaration node)
virtual void EndVisit (ElementaryTypeName node)
virtual void EndVisit (UserDefinedTypeName node)
virtual void EndVisit (Mapping node)
virtual void EndVisit (ArrayTypeName node)
virtual void EndVisit (Block node)
virtual void EndVisit (PlaceholderStatement node)
virtual void EndVisit (IfStatement node)
virtual void EndVisit (WhileStatement node)
virtual void EndVisit (DoWhileStatement node)
virtual void EndVisit (ForStatement node)
virtual void EndVisit (Continue node)
virtual void EndVisit (Break node)
virtual void EndVisit (Return node)
virtual void EndVisit (Throw node)
virtual void EndVisit (EmitStatement node)
virtual void EndVisit (VariableDeclarationStatement node)
virtual void EndVisit (InlineAssembly node)
virtual void EndVisit (ExpressionStatement node)
virtual void EndVisit (Literal node)
virtual void EndVisit (Identifier node)
virtual void EndVisit (ElementaryTypeNameExpression node)
virtual void EndVisit (UnaryOperation node)
virtual void EndVisit (BinaryOperation node)
virtual void EndVisit (Conditional node)
virtual void EndVisit (Assignment node)
virtual void EndVisit (TupleExpression node)
virtual void EndVisit (FunctionCall node)
virtual void EndVisit (NewExpression node)
virtual void EndVisit (MemberAccess node)
virtual void EndVisit (IndexAccess node)
Properties
Dictionary< string, List< BoogieExpr > > ContractInvariants [get]
Private Member Functions
void preTranslationAction (ASTNode node)
void TranslateStructDefinition (StructDefinition structDefn)
void TranslateStateVarDeclaration (VariableDeclaration varDecl)
BoogieCallCmd InstrumentForPrintingData (TypeDescription type, BoogieExpr value, string name)
void PrintArguments (FunctionDefinition node, List< BoogieVariable > inParams, BoogieStmtList currentStmtList)
bool IsVeriSolContractInvariantFunction (FunctionDefinition node, BoogieStmtList procBody, out List< BoogieExpr > contractInvs)
BoogieStmtList GenerateInitializationStmts (ContractDefinition contract)
void GenerateInitializationForArrayStateVar (VariableDeclaration varDecl, ArrayTypeName array)
void GenerateInitializationForStructStateVar (VariableDeclaration varDecl, UserDefinedTypeName structVar)
BoogieFuncCallExpr GetCallExprForZeroInit (BoogieType key, BoogieType value)
BoogieExpr getSumArray ()
BoogieExpr getSumAccess (BoogieExpr key)
void GenerateInitializationForMappingStateVar (VariableDeclaration varDecl, Mapping mapping)
void GenerateInitializationForElementaryTypes (VariableDeclaration varDecl, ElementaryTypeName elementaryType)
void InitializeNestedArrayMappingStateVar (VariableDeclaration varDecl, Mapping mapping)
BoogieMapSelect CreateDistinctArrayMappingAddress (BoogieStmtList stmtList, VariableDeclaration varDecl)
void GetBoogieTypesFromMapping (VariableDeclaration varDecl, Mapping mapping, out BoogieType mapKeyType, out BoogieMapSelect lhs)
void GenerateDefaultConstructor (ContractDefinition contract)
void GenerateConstructorWithBaseCalls (FunctionDefinition ctor, List< BoogieVariable > inParams)
InheritanceSpecifier GetInheritanceSpecifieWithArgsOfBase (ContractDefinition contract, ContractDefinition baseContract)
ModifierInvocation GetModifierInvocationOfBase (FunctionDefinition ctor, ContractDefinition baseContract)
BoogieAssertCmd InstrumentSourceFileAndLineInfo (ASTNode node)
BoogieExpr AddModuloOp (Expression srcExpr, BoogieExpr expr, TypeDescription type)
void TranslateInBuiltFunction (FunctionCall funcCall, BoogieExpr lhs)
void TranslateFunctionCalls (FunctionCall funcCall, List< BoogieIdentifierExpr > outParams)
void AddAssumeForUints (Expression expr, BoogieExpr boogieExpr, TypeDescription typeDesc)
void emitRevertLogic (BoogieStmtList revertLogic)
List< BoogieExpr > ExtractSpecifications (string specStringCall, BoogieStmtList body, out BoogieStmtList bodyWithoutSpecNodes)
BoogieExpr TranslateModifiesStmt (BoogieExpr boogieExpr1, BoogieExpr boogieExpr2)
List< BoogieExpr > ExtractContractInvariants (BoogieStmtList body)
BoogieExpr TranslateExpr (Expression expr)
BoogieExpr TranslateNumberToExpr (Literal node)
BoogieExpr GenerateNonDetExpr (Expression node, string reason)
BoogieExpr TranslateBalance (MemberAccess node)
BoogieExpr TranslateArrayLength (MemberAccess node)
bool IsBuiltInTransferFunc (string functionName, FunctionCall node)
BoogieExpr TranslateVeriSolCodeContractFuncCall (FunctionCall node)
bool IsVeriSolCodeContractFunction (FunctionCall node)
string GetVeriSolCodeContractFunction (FunctionCall node)
BoogieIdentifierExpr MkNewLocalVariableForFunctionReturn (FunctionCall node)
BoogieIdentifierExpr MkNewLocalVariableWithType (BoogieType boogieTypeCall)
bool IsImplicitFunc (FunctionCall node)
Implicit function calls
bool IsContractConstructor (FunctionCall node)
bool IsStructConstructor (FunctionCall node)
bool IsKeccakFunc (FunctionCall node)
bool IsAbiEncodePackedFunc (FunctionCall node)
void TranslateKeccakFuncCall (FunctionCall funcCall, BoogieExpr lhs)
void TranslateAbiEncodedFuncCall (FunctionCall funcCall, BoogieExpr lhs)
void TranslateCallStatement (FunctionCall node, List< BoogieIdentifierExpr > outParams=null)
void TranslateTransferCallStmt (FunctionCall node)
BoogieCallCmd MkFallbackDispatchCallCmd (FunctionCall node, BoogieExpr amountExpr)
void TranslateSendCallStmt (FunctionCall node, BoogieIdentifierExpr returnExpr, BoogieExpr amountExpr, bool isCall=false)
void TranslateNewStatement (FunctionCall node, BoogieExpr lhs)
void TranslateStructConstructor (FunctionCall node, BoogieExpr lhs)
bool IsDynamicArrayPush (FunctionCall node)
void TranslateDynamicArrayPush (FunctionCall node)
void AddUnsignedTypeAssumeCmd (BoogieIdentifierExpr v)
bool IsExternalFunctionCall (FunctionCall node)
ContractDefinition IsLibraryFunctionCall (FunctionCall node)
void TranslateExternalFunctionCall (FunctionCall node, List< BoogieIdentifierExpr > outParams=null)
void TranslateUsingLibraryCall (FunctionCall node, List< BoogieIdentifierExpr > outParams)
bool IsUsingBasedLibraryCall (MemberAccess memberAccess)
void TranslateInternalFunctionCall (FunctionCall node, List< BoogieIdentifierExpr > outParams=null)
void TranslateDynamicDispatchCall (FunctionCall node, List< BoogieIdentifierExpr > outParams, List< BoogieExpr > arguments, bool condition, BoogieExpr receiver)
bool IsGetterForPublicVariable (FunctionCall node, out VariableDeclaration var, out ContractDefinition contractDefinition)
bool IsStaticDispatching (FunctionCall node)
ContractDefinition GetStaticDispatchingContract (FunctionCall node)
bool IsDynamicDispatching (FunctionCall node)
bool IsTypeCast (FunctionCall node)
void TranslateTypeCast (FunctionCall node, BoogieExpr lhs, out bool isElemenentaryTypeCast)
void VeriSolAssert (bool cond, string message="")
Static Private Member Functions
static void emitGasCheck (BoogieStmtList newBody)
Private Attributes
TranslatorContext context
Dictionary< string, List< BoogieVariable > > boogieToLocalVarsMap
string currentBoogieProc = null
bool inlineAssemblyPresent = false
ContractDefinition currentContract = null
FunctionDefinition currentFunction = null
string currentSourceFile = null
int currentSourceLine = -1
BoogieStmtList currentPostlude = null
bool genInlineAttrsInBpl
Dictionary< string, List< BoogieExpr > > contractInvariants = null
List< BoogieVariable > currentParamList
bool isReturnParameterList = false
BoogieStmtList currentStmtList = null
BoogieExpr currentExpr
Additional Inherited Members
Protected Member Functions inherited from SolidityAST.BasicASTVisitor
virtual bool CommonVisit (ASTNode node)
virtual void CommonEndVisit (ASTNode node)
Detailed Description
Definition at line 16 of file ProcedureTranslator.cs.
Constructor & Destructor Documentation
ProcedureTranslator()
SolToBoogie.ProcedureTranslator.ProcedureTranslator (TranslatorContext context, bool _genInlineAttrsInBpl = true) inline
Definition at line 77 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.boogieToLocalVarsMap, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.contractInvariants, and SolToBoogie.ProcedureTranslator.genInlineAttrsInBpl.
Member Function Documentation
AddAssumeForUints()
void SolToBoogie.ProcedureTranslator.AddAssumeForUints (Expression expr, BoogieExpr boogieExpr, TypeDescription typeDesc) inline private
Definition at line 1711 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AppendStmtList(), SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentStmtList, BoogieAST.BoogieStmtList.MakeSingletonStmtList(), SolToBoogie.TranslatorFlags.NoUnsignedAssumesFlag, SolToBoogie.TranslatorContext.TranslateFlags, SolToBoogie.TranslatorFlags.UseModularArithmetic, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.MkNewLocalVariableForFunctionReturn(), SolToBoogie.ProcedureTranslator.TranslateExpr(), and SolToBoogie.ProcedureTranslator.Visit().
AddModuloOp()
BoogieExpr SolToBoogie.ProcedureTranslator.AddModuloOp (Expression srcExpr, BoogieExpr expr, TypeDescription type) inline private
Definition at line 1424 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.context, SolToBoogie.TranslatorContext.TranslateFlags, SolToBoogie.TranslatorFlags.UseModularArithmetic, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
AddUnsignedTypeAssumeCmd()
void SolToBoogie.ProcedureTranslator.AddUnsignedTypeAssumeCmd (BoogieIdentifierExpr v) inline private
Definition at line 2976 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), and SolToBoogie.ProcedureTranslator.currentStmtList.
adjustSum()
BoogieAssignCmd SolToBoogie.ProcedureTranslator.adjustSum (BoogieBinaryOperation.Opcode op, BoogieExpr sumInd, BoogieExpr amt) inline
Definition at line 678 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.getSumAccess().
Referenced by SolToBoogie.ProcedureTranslator.updateAssignedSums(), and SolToBoogie.ProcedureTranslator.Visit().
CreateDistinctArrayMappingAddress()
BoogieMapSelect SolToBoogie.ProcedureTranslator.CreateDistinctArrayMappingAddress (BoogieStmtList stmtList, VariableDeclaration varDecl) inline private
Definition at line 938 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.ProcedureTranslator.boogieToLocalVarsMap, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentBoogieProc, SolToBoogie.TransUtils.GetCanonicalStateVariableName(), SolToBoogie.TranslatorContext.MakeFreshTypedIdent(), BoogieAST.BoogieNamedDecl.Name, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.ProcedureTranslator.GenerateInitializationForArrayStateVar(), and SolToBoogie.ProcedureTranslator.GenerateInitializationForMappingStateVar().
emitGasCheck()
static void SolToBoogie.ProcedureTranslator.emitGasCheck (BoogieStmtList newBody) inline static private
Definition at line 47 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement().
Referenced by SolToBoogie.ProcedureTranslator.preTranslationAction(), and SolToBoogie.ProcedureTranslator.Visit().
emitRevertLogic()
void SolToBoogie.ProcedureTranslator.emitRevertLogic (BoogieStmtList revertLogic) inline private
Definition at line 1740 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement().
Referenced by SolToBoogie.ProcedureTranslator.TranslateTransferCallStmt(), and SolToBoogie.ProcedureTranslator.Visit().
Equals()
override bool SolToBoogie.ProcedureTranslator.Equals (object obj) inline
Definition at line 3797 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.ContractInvariants, SolToBoogie.ProcedureTranslator.currentExpr, and SolToBoogie.ProcedureTranslator.Equals().
Referenced by SolToBoogie.ProcedureTranslator.Equals().
ExtractContractInvariants()
List<BoogieExpr> SolToBoogie.ProcedureTranslator.ExtractContractInvariants (BoogieStmtList body) inline private
Definition at line 1907 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.IsVeriSolContractInvariantFunction().
ExtractSpecifications()
List<BoogieExpr> SolToBoogie.ProcedureTranslator.ExtractSpecifications (string specStringCall, BoogieStmtList body, out BoogieStmtList bodyWithoutSpecNodes) inline private
Parameters
specStringCall "Invariant_VeriSol", "Ensures_VeriSol", "Requires_VeriSol"
body
bodyWithoutSpecNodes
Returns
Definition at line 1838 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.TranslateModifiesStmt(), and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
GenerateConstructorWithBaseCalls()
void SolToBoogie.ProcedureTranslator.GenerateConstructorWithBaseCalls (FunctionDefinition ctor, List< BoogieVariable > inParams) inline private
Definition at line 1085 of file ProcedureTranslator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), SolidityAST.InheritanceSpecifier.Arguments, SolidityAST.ModifierInvocation.Arguments, SolidityAST.ContractDefinition.BaseContracts, SolToBoogie.ProcedureTranslator.boogieToLocalVarsMap, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentBoogieProc, SolToBoogie.ProcedureTranslator.currentContract, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.TranslatorFlags.GenerateInlineAttributes, SolToBoogie.TranslatorContext.GetASTNodeById(), SolToBoogie.TransUtils.GetCanonicalConstructorName(), SolToBoogie.TranslatorContext.GetConstructorByContract(), SolToBoogie.TranslatorContext.GetContractByFunction(), SolToBoogie.ProcedureTranslator.GetInheritanceSpecifieWithArgsOfBase(), SolToBoogie.ProcedureTranslator.GetModifierInvocationOfBase(), SolidityAST.FunctionDefinition.IsConstructor, SolToBoogie.TranslatorContext.IsConstructorDefined(), SolToBoogie.TranslatorContext.IsMethodInIgnoredSet(), SolidityAST.ContractDefinition.LinearizedBaseContracts, BoogieAST.BoogieTypedIdent.Name, SolidityAST.ContractDefinition.Name, SolToBoogie.ProcedureTranslator.PrintArguments(), SolToBoogie.TranslatorContext.Program, SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.TranslatorContext.TranslateFlags, BoogieAST.BoogieVariable.TypedIdent, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
GenerateDefaultConstructor()
void SolToBoogie.ProcedureTranslator.GenerateDefaultConstructor (ContractDefinition contract) inline private
Definition at line 978 of file ProcedureTranslator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), BoogieAST.BoogieStmtList.AddStatement(), SolidityAST.InheritanceSpecifier.Arguments, SolidityAST.ContractDefinition.BaseContracts, SolToBoogie.ProcedureTranslator.boogieToLocalVarsMap, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentBoogieProc, SolToBoogie.ProcedureTranslator.currentContract, SolToBoogie.ProcedureTranslator.GenerateInitializationStmts(), SolToBoogie.TranslatorFlags.GenerateInlineAttributes, SolToBoogie.TranslatorContext.GetASTNodeById(), SolToBoogie.TransUtils.GetCanonicalConstructorName(), SolToBoogie.TranslatorContext.GetConstructorByContract(), SolToBoogie.TransUtils.GetDefaultInParams(), SolToBoogie.ProcedureTranslator.GetInheritanceSpecifieWithArgsOfBase(), SolToBoogie.ProcedureTranslator.InstrumentSourceFileAndLineInfo(), SolToBoogie.TranslatorContext.IsConstructorDefined(), SolidityAST.ContractDefinition.LinearizedBaseContracts, BoogieAST.BoogieTypedIdent.Name, SolidityAST.ContractDefinition.Name, SolToBoogie.TranslatorFlags.NoSourceLineInfoFlag, SolToBoogie.ProcedureTranslator.PrintArguments(), SolToBoogie.TranslatorContext.Program, SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.TranslatorContext.TranslateFlags, BoogieAST.BoogieVariable.TypedIdent, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
GenerateInitializationForArrayStateVar()
void SolToBoogie.ProcedureTranslator.GenerateInitializationForArrayStateVar (VariableDeclaration varDecl, ArrayTypeName array) inline private
Definition at line 622 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolidityAST.ArrayTypeName.BaseType, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.CreateDistinctArrayMappingAddress(), SolToBoogie.ProcedureTranslator.currentStmtList, SolidityAST.ArrayTypeName.Length, SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.TranslatorContext.TranslateFlags, and SolToBoogie.TranslatorFlags.UseModularArithmetic.
Referenced by SolToBoogie.ProcedureTranslator.GenerateInitializationStmts().
GenerateInitializationForElementaryTypes()
void SolToBoogie.ProcedureTranslator.GenerateInitializationForElementaryTypes (VariableDeclaration varDecl, ElementaryTypeName elementaryType) inline private
Definition at line 802 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.TransUtils.GetCanonicalStateVariableName(), SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.TranslatorContext.TranslateFlags, SolidityAST.VariableDeclaration.TypeDescriptions, SolidityAST.ElementaryTypeName.TypeDescriptions, SolidityAST.TypeDescription.TypeString, SolToBoogie.TranslatorFlags.UseModularArithmetic, SolidityAST.VariableDeclaration.Value, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.GenerateInitializationStmts().
GenerateInitializationForMappingStateVar()
void SolToBoogie.ProcedureTranslator.GenerateInitializationForMappingStateVar (VariableDeclaration varDecl, Mapping mapping) inline private
Definition at line 687 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), BoogieAST.BoogieType.Bool, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.CreateDistinctArrayMappingAddress(), SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.ProcedureTranslator.GetBoogieTypesFromMapping(), SolToBoogie.ProcedureTranslator.GetCallExprForZeroInit(), SolToBoogie.ProcedureTranslator.getSumAccess(), SolToBoogie.ProcedureTranslator.InitializeNestedArrayMappingStateVar(), SolToBoogie.TranslatorFlags.InstrumentSums, BoogieAST.BoogieType.Int, SolToBoogie.QVarGenerator.NewQVar(), SolToBoogie.TranslatorFlags.QuantFreeAllocs, BoogieAST.BoogieType.Ref, SolToBoogie.TranslatorContext.TranslateFlags, SolToBoogie.TranslatorFlags.UseModularArithmetic, and SolidityAST.Mapping.ValueType.
Referenced by SolToBoogie.ProcedureTranslator.GenerateInitializationStmts().
GenerateInitializationForStructStateVar()
void SolToBoogie.ProcedureTranslator.GenerateInitializationForStructStateVar (VariableDeclaration varDecl, UserDefinedTypeName structVar) inline private
Definition at line 640 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.ProcedureTranslator.boogieToLocalVarsMap, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentBoogieProc, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.TransUtils.GetCanonicalStateVariableName(), SolToBoogie.TranslatorContext.MakeFreshTypedIdent(), BoogieAST.BoogieNamedDecl.Name, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.ProcedureTranslator.GenerateInitializationStmts().
GenerateInitializationStmts()
BoogieStmtList SolToBoogie.ProcedureTranslator.GenerateInitializationStmts (ContractDefinition contract) inline private
Definition at line 573 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.ProcedureTranslator.GenerateInitializationForArrayStateVar(), SolToBoogie.ProcedureTranslator.GenerateInitializationForElementaryTypes(), SolToBoogie.ProcedureTranslator.GenerateInitializationForMappingStateVar(), SolToBoogie.ProcedureTranslator.GenerateInitializationForStructStateVar(), SolToBoogie.TranslatorContext.GetStateVarsByContract(), SolidityAST.VariableDeclaration.TypeDescriptions, and SolidityAST.VariableDeclaration.TypeName.
Referenced by SolToBoogie.ProcedureTranslator.GenerateDefaultConstructor(), and SolToBoogie.ProcedureTranslator.Visit().
GenerateNonDetExpr()
BoogieExpr SolToBoogie.ProcedureTranslator.GenerateNonDetExpr (Expression node, string reason) inline private
Definition at line 2294 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.ProcedureTranslator.currentStmtList, BoogieAST.BoogieType.Int, SolToBoogie.ProcedureTranslator.MkNewLocalVariableWithType(), BoogieAST.BoogieType.Ref, SolidityAST.Expression.TypeDescriptions, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
GetBoogieTypesFromMapping()
void SolToBoogie.ProcedureTranslator.GetBoogieTypesFromMapping (VariableDeclaration varDecl, Mapping mapping, out BoogieType mapKeyType, out BoogieMapSelect lhs) inline private
Definition at line 960 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.context, SolToBoogie.TransUtils.GetCanonicalStateVariableName(), SolToBoogie.MapArrayHelper.GetMemoryMapName(), SolToBoogie.MapArrayHelper.InferExprTypeFromTypeString(), SolidityAST.Mapping.KeyType, SolidityAST.TypeDescription.ToString(), SolidityAST.ElementaryTypeName.TypeDescriptions, SolidityAST.UserDefinedTypeName.TypeDescriptions, and SolidityAST.Mapping.ValueType.
Referenced by SolToBoogie.ProcedureTranslator.GenerateInitializationForMappingStateVar().
GetCallExprForZeroInit()
BoogieFuncCallExpr SolToBoogie.ProcedureTranslator.GetCallExprForZeroInit (BoogieType key, BoogieType value) inline private
Definition at line 661 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.GenerateInitializationForMappingStateVar(), SolToBoogie.ProcedureTranslator.InitializeNestedArrayMappingStateVar(), and SolToBoogie.ProcedureTranslator.Visit().
GetInheritanceSpecifieWithArgsOfBase()
InheritanceSpecifier SolToBoogie.ProcedureTranslator.GetInheritanceSpecifieWithArgsOfBase (ContractDefinition contract, ContractDefinition baseContract) inline private
Definition at line 1210 of file ProcedureTranslator.cs.
References SolidityAST.InheritanceSpecifier.Arguments, SolidityAST.InheritanceSpecifier.BaseName, and SolidityAST.UserDefinedTypeName.Name.
Referenced by SolToBoogie.ProcedureTranslator.GenerateConstructorWithBaseCalls(), and SolToBoogie.ProcedureTranslator.GenerateDefaultConstructor().
GetModifierInvocationOfBase()
ModifierInvocation SolToBoogie.ProcedureTranslator.GetModifierInvocationOfBase (FunctionDefinition ctor, ContractDefinition baseContract) inline private
Definition at line 1225 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.context, SolToBoogie.TranslatorContext.GetASTNodeById(), SolidityAST.ModifierInvocation.ModifierName, and SolidityAST.Identifier.ReferencedDeclaration.
Referenced by SolToBoogie.ProcedureTranslator.GenerateConstructorWithBaseCalls().
GetStaticDispatchingContract()
ContractDefinition SolToBoogie.ProcedureTranslator.GetStaticDispatchingContract (FunctionCall node) inline private
Definition at line 3348 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.context, SolidityAST.FunctionCall.Expression, SolidityAST.MemberAccess.Expression, SolToBoogie.TranslatorContext.GetASTNodeById(), SolidityAST.Identifier.ReferencedDeclaration, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.TranslateInternalFunctionCall().
getSumAccess()
BoogieExpr SolToBoogie.ProcedureTranslator.getSumAccess (BoogieExpr key) inline private
Definition at line 673 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.getSumArray().
Referenced by SolToBoogie.ProcedureTranslator.adjustSum(), SolToBoogie.ProcedureTranslator.GenerateInitializationForMappingStateVar(), SolToBoogie.ProcedureTranslator.TranslateDynamicArrayPush(), and SolToBoogie.ProcedureTranslator.Visit().
getSumArray()
BoogieExpr SolToBoogie.ProcedureTranslator.getSumArray () inline private
Definition at line 668 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.getSumAccess().
GetVeriSolCodeContractFunction()
string SolToBoogie.ProcedureTranslator.GetVeriSolCodeContractFunction (FunctionCall node) inline private
Definition at line 2543 of file ProcedureTranslator.cs.
References SolidityAST.FunctionCall.Expression.
Referenced by SolToBoogie.ProcedureTranslator.TranslateVeriSolCodeContractFuncCall().
InitializeNestedArrayMappingStateVar()
void SolToBoogie.ProcedureTranslator.InitializeNestedArrayMappingStateVar (VariableDeclaration varDecl, Mapping mapping) inline private
Definition at line 864 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.ProcedureTranslator.GetCallExprForZeroInit(), SolToBoogie.TransUtils.GetCanonicalStateVariableName(), SolToBoogie.MapArrayHelper.GetMemoryMapName(), SolToBoogie.MapArrayHelper.InferExprTypeFromTypeString(), SolidityAST.Mapping.KeyType, SolToBoogie.TranslatorFlags.LazyNestedAlloc, SolToBoogie.QVarGenerator.NewQVar(), SolToBoogie.TranslatorFlags.QuantFreeAllocs, BoogieAST.BoogieType.Ref, SolidityAST.TypeDescription.ToString(), SolToBoogie.TranslatorContext.TranslateFlags, and SolidityAST.ElementaryTypeName.TypeDescriptions.
Referenced by SolToBoogie.ProcedureTranslator.GenerateInitializationForMappingStateVar().
InstrumentForPrintingData()
BoogieCallCmd SolToBoogie.ProcedureTranslator.InstrumentForPrintingData (TypeDescription type, BoogieExpr value, string name) inline private
Definition at line 169 of file ProcedureTranslator.cs.
References BoogieAST.BoogieCmd.Attributes, SolToBoogie.ProcedureTranslator.context, SolToBoogie.TranslatorFlags.NoDataValuesInfoFlag, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.ProcedureTranslator.PrintArguments(), and SolToBoogie.ProcedureTranslator.Visit().
InstrumentSourceFileAndLineInfo()
BoogieAssertCmd SolToBoogie.ProcedureTranslator.InstrumentSourceFileAndLineInfo (ASTNode node) inline private
Definition at line 1310 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentSourceFile, SolToBoogie.ProcedureTranslator.currentSourceLine, and SolToBoogie.TransUtils.GenerateSourceInfoAnnotation().
Referenced by SolToBoogie.ProcedureTranslator.GenerateDefaultConstructor(), and SolToBoogie.ProcedureTranslator.TranslateStatement().
IsAbiEncodePackedFunc()
bool SolToBoogie.ProcedureTranslator.IsAbiEncodePackedFunc (FunctionCall node) inline private
Definition at line 2623 of file ProcedureTranslator.cs.
References SolidityAST.FunctionCall.Expression.
Referenced by SolToBoogie.ProcedureTranslator.IsImplicitFunc(), and SolToBoogie.ProcedureTranslator.Visit().
IsBuiltInTransferFunc()
bool SolToBoogie.ProcedureTranslator.IsBuiltInTransferFunc (string functionName, FunctionCall node) inline private
Definition at line 2494 of file ProcedureTranslator.cs.
References SolidityAST.FunctionCall.Expression.
Referenced by SolToBoogie.ProcedureTranslator.TranslateExternalFunctionCall(), and SolToBoogie.ProcedureTranslator.Visit().
IsContractConstructor()
bool SolToBoogie.ProcedureTranslator.IsContractConstructor (FunctionCall node) inline private
Definition at line 2604 of file ProcedureTranslator.cs.
References SolidityAST.FunctionCall.Expression.
Referenced by SolToBoogie.ProcedureTranslator.IsImplicitFunc(), and SolToBoogie.ProcedureTranslator.Visit().
IsDynamicArrayPush()
bool SolToBoogie.ProcedureTranslator.IsDynamicArrayPush (FunctionCall node) inline private
Definition at line 2922 of file ProcedureTranslator.cs.
References SolidityAST.FunctionCall.Expression, SolidityAST.MemberAccess.Expression, SolToBoogie.TransUtils.GetFuncNameFromFuncCall(), SolToBoogie.MapArrayHelper.IsArrayTypeString(), SolidityAST.Expression.TypeDescriptions, SolidityAST.TypeDescription.TypeString, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
IsDynamicDispatching()
bool SolToBoogie.ProcedureTranslator.IsDynamicDispatching (FunctionCall node) inline private
Definition at line 3361 of file ProcedureTranslator.cs.
References SolidityAST.FunctionCall.Expression.
Referenced by SolToBoogie.ProcedureTranslator.TranslateInternalFunctionCall().
IsExternalFunctionCall()
bool SolToBoogie.ProcedureTranslator.IsExternalFunctionCall (FunctionCall node) inline private
Definition at line 2983 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.context, SolidityAST.FunctionCall.Expression, and SolToBoogie.TranslatorContext.GetASTNodeById().
Referenced by SolToBoogie.ProcedureTranslator.TranslateFunctionCalls(), and SolToBoogie.ProcedureTranslator.Visit().
IsGetterForPublicVariable()
bool SolToBoogie.ProcedureTranslator.IsGetterForPublicVariable (FunctionCall node, out VariableDeclaration var, out ContractDefinition contractDefinition) inline private
Definition at line 3308 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.context, SolidityAST.FunctionCall.Expression, SolToBoogie.TranslatorContext.GetContractByName(), SolToBoogie.TranslatorContext.GetStateVarByDynamicType(), SolToBoogie.TranslatorContext.HasStateVarName(), and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.TranslateDynamicDispatchCall().
IsImplicitFunc()
bool SolToBoogie.ProcedureTranslator.IsImplicitFunc (FunctionCall node) inline private
Implicit function calls
Parameters
node
Returns
Definition at line 2594 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.IsAbiEncodePackedFunc(), SolToBoogie.ProcedureTranslator.IsContractConstructor(), SolToBoogie.ProcedureTranslator.IsKeccakFunc(), SolToBoogie.ProcedureTranslator.IsStructConstructor(), and SolToBoogie.ProcedureTranslator.IsTypeCast().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
IsKeccakFunc()
bool SolToBoogie.ProcedureTranslator.IsKeccakFunc (FunctionCall node) inline private
Definition at line 2614 of file ProcedureTranslator.cs.
References SolidityAST.FunctionCall.Expression.
Referenced by SolToBoogie.ProcedureTranslator.IsImplicitFunc(), and SolToBoogie.ProcedureTranslator.Visit().
IsLibraryFunctionCall()
ContractDefinition SolToBoogie.ProcedureTranslator.IsLibraryFunctionCall (FunctionCall node) inline private
Definition at line 3024 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.context, SolidityAST.FunctionCall.Expression, and SolToBoogie.TranslatorContext.GetASTNodeById().
Referenced by SolToBoogie.ProcedureTranslator.TranslateInternalFunctionCall().
IsStaticDispatching()
bool SolToBoogie.ProcedureTranslator.IsStaticDispatching (FunctionCall node) inline private
Definition at line 3333 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.context, SolidityAST.FunctionCall.Expression, and SolToBoogie.TranslatorContext.GetASTNodeById().
Referenced by SolToBoogie.ProcedureTranslator.TranslateInternalFunctionCall().
IsStructConstructor()
bool SolToBoogie.ProcedureTranslator.IsStructConstructor (FunctionCall node) inline private
Definition at line 2609 of file ProcedureTranslator.cs.
References SolidityAST.FunctionCall.Kind.
Referenced by SolToBoogie.ProcedureTranslator.IsImplicitFunc(), and SolToBoogie.ProcedureTranslator.Visit().
IsTypeCast()
bool SolToBoogie.ProcedureTranslator.IsTypeCast (FunctionCall node) inline private
Definition at line 3366 of file ProcedureTranslator.cs.
References SolidityAST.FunctionCall.Kind.
Referenced by SolToBoogie.ProcedureTranslator.IsImplicitFunc(), SolToBoogie.ProcedureTranslator.TranslateExpr(), and SolToBoogie.ProcedureTranslator.Visit().
IsUsingBasedLibraryCall()
bool SolToBoogie.ProcedureTranslator.IsUsingBasedLibraryCall (MemberAccess memberAccess) inline private
Definition at line 3181 of file ProcedureTranslator.cs.
References SolidityAST.MemberAccess.Expression, and SolidityAST.Expression.TypeDescriptions.
Referenced by SolToBoogie.ProcedureTranslator.TranslateExternalFunctionCall().
IsVeriSolCodeContractFunction()
bool SolToBoogie.ProcedureTranslator.IsVeriSolCodeContractFunction (FunctionCall node) inline private
Definition at line 2520 of file ProcedureTranslator.cs.
References SolidityAST.FunctionCall.Expression.
Referenced by SolToBoogie.ProcedureTranslator.Visit().
IsVeriSolContractInvariantFunction()
bool SolToBoogie.ProcedureTranslator.IsVeriSolContractInvariantFunction (FunctionDefinition node, BoogieStmtList procBody, out List< BoogieExpr > contractInvs) inline private
Definition at line 492 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.ExtractContractInvariants(), SolidityAST.CallableDeclaration.Parameters, SolidityAST.ParameterList.Parameters, SolidityAST.FunctionDefinition.StateMutability, and SolidityAST.FunctionDefinition.Visibility.
Referenced by SolToBoogie.ProcedureTranslator.Visit().
MkFallbackDispatchCallCmd()
BoogieCallCmd SolToBoogie.ProcedureTranslator.MkFallbackDispatchCallCmd (FunctionCall node, BoogieExpr amountExpr) inline private
Definition at line 2739 of file ProcedureTranslator.cs.
References SolidityAST.FunctionCall.Expression, SolidityAST.MemberAccess.Expression, SolToBoogie.ProcedureTranslator.TranslateExpr(), and SolToBoogie.ProcedureTranslator.VeriSolAssert().
MkNewLocalVariableForFunctionReturn()
BoogieIdentifierExpr SolToBoogie.ProcedureTranslator.MkNewLocalVariableForFunctionReturn (FunctionCall node) inline private
Definition at line 2565 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.AddAssumeForUints(), SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.MapArrayHelper.InferExprTypeFromTypeString(), SolToBoogie.ProcedureTranslator.MkNewLocalVariableWithType(), SolidityAST.Expression.TypeDescriptions, and SolidityAST.TypeDescription.TypeString.
Referenced by SolToBoogie.ProcedureTranslator.Visit().
MkNewLocalVariableWithType()
BoogieIdentifierExpr SolToBoogie.ProcedureTranslator.MkNewLocalVariableWithType (BoogieType boogieTypeCall) inline private
Definition at line 2578 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.boogieToLocalVarsMap, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentBoogieProc, and SolToBoogie.TranslatorContext.MakeFreshTypedIdent().
Referenced by SolToBoogie.ProcedureTranslator.GenerateNonDetExpr(), SolToBoogie.ProcedureTranslator.MkNewLocalVariableForFunctionReturn(), SolToBoogie.ProcedureTranslator.TranslateCallStatement(), SolToBoogie.ProcedureTranslator.TranslateSendCallStmt(), SolToBoogie.ProcedureTranslator.TranslateTransferCallStmt(), and SolToBoogie.ProcedureTranslator.Visit().
preTranslationAction()
void SolToBoogie.ProcedureTranslator.preTranslationAction (ASTNode node) inline private
Definition at line 57 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.ProcedureTranslator.emitGasCheck(), SolidityAST.ASTNode.GasCost, SolToBoogie.TranslatorFlags.InstrumentGas, SolToBoogie.TranslatorFlags.ModelReverts, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.ProcedureTranslator.Visit().
PrintArguments()
void SolToBoogie.ProcedureTranslator.PrintArguments (FunctionDefinition node, List< BoogieVariable > inParams, BoogieStmtList currentStmtList) inline private
Definition at line 206 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.ProcedureTranslator.InstrumentForPrintingData(), BoogieAST.BoogieNamedDecl.Name, SolidityAST.VariableDeclaration.Name, SolidityAST.VariableDeclaration.TypeDescriptions, and SolidityAST.TypeDescription.TypeString.
Referenced by SolToBoogie.ProcedureTranslator.GenerateConstructorWithBaseCalls(), SolToBoogie.ProcedureTranslator.GenerateDefaultConstructor(), and SolToBoogie.ProcedureTranslator.Visit().
TranslateAbiEncodedFuncCall()
void SolToBoogie.ProcedureTranslator.TranslateAbiEncodedFuncCall (FunctionCall funcCall, BoogieExpr lhs) inline private
Definition at line 2650 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolidityAST.FunctionCall.Arguments, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.ProcedureTranslator.TranslateExpr(), and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
TranslateArrayLength()
BoogieExpr SolToBoogie.ProcedureTranslator.TranslateArrayLength (MemberAccess node) inline private
Definition at line 2322 of file ProcedureTranslator.cs.
References SolidityAST.MemberAccess.Expression, SolidityAST.MemberAccess.MemberName, SolToBoogie.ProcedureTranslator.TranslateExpr(), and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
TranslateBalance()
BoogieExpr SolToBoogie.ProcedureTranslator.TranslateBalance (MemberAccess node) inline private
Definition at line 2315 of file ProcedureTranslator.cs.
References SolidityAST.MemberAccess.Expression, and SolToBoogie.ProcedureTranslator.TranslateExpr().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
TranslateCallStatement()
void SolToBoogie.ProcedureTranslator.TranslateCallStatement (FunctionCall node, List< BoogieIdentifierExpr > outParams = null) inline private
Definition at line 2667 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolidityAST.FunctionCall.Arguments, BoogieAST.BoogieType.Bool, SolToBoogie.ProcedureTranslator.currentExpr, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.ProcedureTranslator.MkNewLocalVariableWithType(), SolidityAST.FunctionCall.MsgValue, SolidityAST.FunctionCall.ToString(), SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.ProcedureTranslator.TranslateSendCallStmt(), and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.TranslateExternalFunctionCall(), and SolToBoogie.ProcedureTranslator.Visit().
TranslateDynamicArrayPush()
void SolToBoogie.ProcedureTranslator.TranslateDynamicArrayPush (FunctionCall node) inline private
Definition at line 2934 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolidityAST.FunctionCall.Arguments, SolToBoogie.ProcedureTranslator.boogieToLocalVarsMap, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentBoogieProc, SolToBoogie.ProcedureTranslator.currentStmtList, SolidityAST.FunctionCall.Expression, SolidityAST.MemberAccess.Expression, SolToBoogie.MapArrayHelper.GetMemoryMapSelectExpr(), SolToBoogie.ProcedureTranslator.getSumAccess(), SolToBoogie.MapArrayHelper.InferExprTypeFromTypeString(), SolToBoogie.TranslatorFlags.InstrumentSums, BoogieAST.BoogieType.Int, SolToBoogie.TranslatorContext.MakeFreshTypedIdent(), BoogieAST.BoogieTypedIdent.Name, SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.TranslatorContext.TranslateFlags, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
TranslateDynamicDispatchCall()
void SolToBoogie.ProcedureTranslator.TranslateDynamicDispatchCall (FunctionCall node, List< BoogieIdentifierExpr > outParams, List< BoogieExpr > arguments, bool condition, BoogieExpr receiver) inline private
Definition at line 3232 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentContract, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.TranslatorContext.GetAllFuncDefinitions(), SolToBoogie.TransUtils.GetCanonicalFunctionName(), SolToBoogie.TransUtils.GetCanonicalStateVariableName(), SolToBoogie.TranslatorContext.GetSubTypesOfContract(), SolToBoogie.TranslatorContext.HasFuncSignature(), SolidityAST.ASTNode.Id, SolToBoogie.TransUtils.InferFunctionSignature(), SolToBoogie.ProcedureTranslator.IsGetterForPublicVariable(), SolidityAST.ContractDefinition.LinearizedBaseContracts, BoogieAST.BoogieStmtList.MakeSingletonStmtList(), SolidityAST.ContractDefinition.Name, SolToBoogie.TranslatorFlags.OmitAssumeFalseForDynDispatch, SolToBoogie.TranslatorContext.TranslateFlags, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.TranslateExternalFunctionCall(), and SolToBoogie.ProcedureTranslator.TranslateInternalFunctionCall().
TranslateExpr()
BoogieExpr SolToBoogie.ProcedureTranslator.TranslateExpr (Expression expr) inline private
Definition at line 2075 of file ProcedureTranslator.cs.
References SolidityAST.ASTNode.Accept(), SolToBoogie.ProcedureTranslator.AddAssumeForUints(), SolToBoogie.ProcedureTranslator.currentExpr, SolToBoogie.ProcedureTranslator.IsTypeCast(), SolidityAST.Expression.TypeDescriptions, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.GenerateConstructorWithBaseCalls(), SolToBoogie.ProcedureTranslator.GenerateDefaultConstructor(), SolToBoogie.ProcedureTranslator.GenerateInitializationForArrayStateVar(), SolToBoogie.ProcedureTranslator.GenerateInitializationForElementaryTypes(), SolToBoogie.ProcedureTranslator.MkFallbackDispatchCallCmd(), SolToBoogie.ProcedureTranslator.TranslateAbiEncodedFuncCall(), SolToBoogie.ProcedureTranslator.TranslateArrayLength(), SolToBoogie.ProcedureTranslator.TranslateBalance(), SolToBoogie.ProcedureTranslator.TranslateCallStatement(), SolToBoogie.ProcedureTranslator.TranslateDynamicArrayPush(), SolToBoogie.ProcedureTranslator.TranslateExternalFunctionCall(), SolToBoogie.ProcedureTranslator.TranslateInternalFunctionCall(), SolToBoogie.ProcedureTranslator.TranslateKeccakFuncCall(), SolToBoogie.ProcedureTranslator.TranslateNewStatement(), SolToBoogie.ProcedureTranslator.TranslateSendCallStmt(), SolToBoogie.ProcedureTranslator.TranslateStructConstructor(), SolToBoogie.ProcedureTranslator.TranslateTransferCallStmt(), SolToBoogie.ProcedureTranslator.TranslateTypeCast(), SolToBoogie.ProcedureTranslator.TranslateUsingLibraryCall(), SolToBoogie.ProcedureTranslator.TranslateVeriSolCodeContractFuncCall(), and SolToBoogie.ProcedureTranslator.Visit().
TranslateExternalFunctionCall()
void SolToBoogie.ProcedureTranslator.TranslateExternalFunctionCall (FunctionCall node, List< BoogieIdentifierExpr > outParams = null) inline private
Definition at line 3042 of file ProcedureTranslator.cs.
References SolidityAST.FunctionCall.Arguments, SolToBoogie.ProcedureTranslator.boogieToLocalVarsMap, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentBoogieProc, SolidityAST.FunctionCall.Expression, SolidityAST.MemberAccess.Expression, BoogieAST.BoogieType.Int, SolToBoogie.ProcedureTranslator.IsBuiltInTransferFunc(), SolToBoogie.ProcedureTranslator.IsUsingBasedLibraryCall(), SolToBoogie.TranslatorContext.MakeFreshTypedIdent(), SolidityAST.MemberAccess.MemberName, SolidityAST.FunctionCall.MsgValue, SolToBoogie.ProcedureTranslator.TranslateCallStatement(), SolToBoogie.ProcedureTranslator.TranslateDynamicDispatchCall(), SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.ProcedureTranslator.TranslateSendCallStmt(), SolToBoogie.ProcedureTranslator.TranslateTransferCallStmt(), SolToBoogie.ProcedureTranslator.TranslateUsingLibraryCall(), and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.TranslateFunctionCalls(), and SolToBoogie.ProcedureTranslator.Visit().
TranslateFunctionCalls()
void SolToBoogie.ProcedureTranslator.TranslateFunctionCalls (FunctionCall funcCall, List< BoogieIdentifierExpr > outParams) inline private
Definition at line 1636 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.IsExternalFunctionCall(), SolToBoogie.ProcedureTranslator.TranslateExternalFunctionCall(), and SolToBoogie.ProcedureTranslator.TranslateInternalFunctionCall().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
TranslateInBuiltFunction()
void SolToBoogie.ProcedureTranslator.TranslateInBuiltFunction (FunctionCall funcCall, BoogieExpr lhs) inline private
Definition at line 1631 of file ProcedureTranslator.cs.
TranslateInternalFunctionCall()
void SolToBoogie.ProcedureTranslator.TranslateInternalFunctionCall (FunctionCall node, List< BoogieIdentifierExpr > outParams = null) inline private
Definition at line 3189 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.TransUtils.GetDefaultArguments(), SolToBoogie.TransUtils.GetFuncNameFromFuncCall(), SolToBoogie.ProcedureTranslator.GetStaticDispatchingContract(), SolToBoogie.ProcedureTranslator.IsDynamicDispatching(), SolToBoogie.ProcedureTranslator.IsLibraryFunctionCall(), SolToBoogie.ProcedureTranslator.IsStaticDispatching(), SolidityAST.ContractDefinition.Name, SolToBoogie.ProcedureTranslator.TranslateDynamicDispatchCall(), SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.ProcedureTranslator.TranslateStructConstructor(), and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.TranslateFunctionCalls(), and SolToBoogie.ProcedureTranslator.Visit().
TranslateKeccakFuncCall()
void SolToBoogie.ProcedureTranslator.TranslateKeccakFuncCall (FunctionCall funcCall, BoogieExpr lhs) inline private
Definition at line 2639 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolidityAST.FunctionCall.Arguments, SolToBoogie.ProcedureTranslator.currentStmtList, and SolToBoogie.ProcedureTranslator.TranslateExpr().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
TranslateModifiesStmt()
BoogieExpr SolToBoogie.ProcedureTranslator.TranslateModifiesStmt (BoogieExpr boogieExpr1, BoogieExpr boogieExpr2) inline private
Definition at line 1874 of file ProcedureTranslator.cs.
References SolToBoogie.MapArrayHelper.GetMemoryMapName(), BoogieAST.BoogieType.Int, SolToBoogie.QVarGenerator.NewQVar(), BoogieAST.BoogieType.Ref, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.ExtractSpecifications().
TranslateNewStatement()
void SolToBoogie.ProcedureTranslator.TranslateNewStatement (FunctionCall node, BoogieExpr lhs) inline private
Definition at line 2790 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolidityAST.FunctionCall.Arguments, SolToBoogie.ProcedureTranslator.boogieToLocalVarsMap, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentBoogieProc, SolToBoogie.ProcedureTranslator.currentStmtList, SolidityAST.FunctionCall.Expression, SolToBoogie.TranslatorContext.GetASTNodeById(), SolToBoogie.TransUtils.GetCanonicalConstructorName(), SolToBoogie.TranslatorContext.MakeFreshTypedIdent(), BoogieAST.BoogieTypedIdent.Name, BoogieAST.BoogieType.Ref, SolToBoogie.ProcedureTranslator.TranslateExpr(), SolidityAST.Expression.TypeDescriptions, SolidityAST.NewExpression.TypeName, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
TranslateNumberToExpr()
BoogieExpr SolToBoogie.ProcedureTranslator.TranslateNumberToExpr (Literal node) inline private
Definition at line 2134 of file ProcedureTranslator.cs.
References SolidityAST.Literal.Value.
Referenced by SolToBoogie.ProcedureTranslator.Visit().
TranslateSendCallStmt()
void SolToBoogie.ProcedureTranslator.TranslateSendCallStmt (FunctionCall node, BoogieIdentifierExpr returnExpr, BoogieExpr amountExpr, bool isCall = false) inline private
Definition at line 2753 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.TranslatorContext.CALL_GAS_STIPEND, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentStmtList, SolidityAST.FunctionCall.Expression, SolidityAST.MemberAccess.Expression, SolToBoogie.TranslatorFlags.InstrumentGas, BoogieAST.BoogieType.Int, BoogieAST.BoogieStmtList.MakeSingletonStmtList(), SolToBoogie.ProcedureTranslator.MkNewLocalVariableWithType(), SolToBoogie.ProcedureTranslator.TranslateExpr(), and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.ProcedureTranslator.TranslateCallStatement(), SolToBoogie.ProcedureTranslator.TranslateExternalFunctionCall(), and SolToBoogie.ProcedureTranslator.Visit().
TranslateStatement()
BoogieStmtList SolToBoogie.ProcedureTranslator.TranslateStatement (Statement node) inline
This the only method that returns a BoogieStmtList (value of currentStmtList)
Parameters
node
Returns
Definition at line 1286 of file ProcedureTranslator.cs.
References SolidityAST.ASTNode.Accept(), BoogieAST.BoogieStmtList.AppendStmtList(), SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.ProcedureTranslator.InstrumentSourceFileAndLineInfo(), BoogieAST.BoogieStmtList.MakeSingletonStmtList(), SolToBoogie.TranslatorFlags.NoSourceLineInfoFlag, SolToBoogie.TranslatorContext.TranslateFlags, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
TranslateStateVarDeclaration()
void SolToBoogie.ProcedureTranslator.TranslateStateVarDeclaration (VariableDeclaration varDecl) inline private
Definition at line 133 of file ProcedureTranslator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), SolToBoogie.ProcedureTranslator.context, SolToBoogie.TransUtils.GetBoogieTypeFromSolidityTypeName(), SolToBoogie.TransUtils.GetCanonicalStateVariableName(), SolToBoogie.TranslatorContext.Program, BoogieAST.BoogieType.Ref, SolidityAST.VariableDeclaration.StateVariable, SolToBoogie.TranslatorContext.TranslateFlags, SolidityAST.VariableDeclaration.TypeDescriptions, SolidityAST.VariableDeclaration.TypeName, SolToBoogie.TranslatorFlags.UseModularArithmetic, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
TranslateStructConstructor()
void SolToBoogie.ProcedureTranslator.TranslateStructConstructor (FunctionCall node, BoogieExpr lhs) inline private
Definition at line 2867 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.ProcedureTranslator.boogieToLocalVarsMap, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentBoogieProc, SolToBoogie.ProcedureTranslator.currentStmtList, BoogieAST.BoogieType.Int, SolToBoogie.TranslatorContext.MakeFreshTypedIdent(), BoogieAST.BoogieTypedIdent.Name, BoogieAST.BoogieType.Ref, SolToBoogie.ProcedureTranslator.TranslateExpr(), SolidityAST.Expression.TypeDescriptions, and SolidityAST.TypeDescription.TypeString.
Referenced by SolToBoogie.ProcedureTranslator.TranslateInternalFunctionCall(), and SolToBoogie.ProcedureTranslator.Visit().
TranslateStructDefinition()
void SolToBoogie.ProcedureTranslator.TranslateStructDefinition (StructDefinition structDefn) inline private
Definition at line 120 of file ProcedureTranslator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), SolToBoogie.ProcedureTranslator.context, SolToBoogie.TransUtils.GetBoogieTypeFromSolidityTypeName(), SolToBoogie.TranslatorContext.Program, BoogieAST.BoogieType.Ref, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
TranslateTransferCallStmt()
void SolToBoogie.ProcedureTranslator.TranslateTransferCallStmt (FunctionCall node) inline private
Definition at line 2690 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolidityAST.FunctionCall.Arguments, BoogieAST.BoogieType.Bool, SolToBoogie.TranslatorContext.CALL_GAS_STIPEND, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.ProcedureTranslator.emitRevertLogic(), SolidityAST.FunctionCall.Expression, SolidityAST.MemberAccess.Expression, SolToBoogie.TranslatorFlags.InstrumentGas, BoogieAST.BoogieType.Int, BoogieAST.BoogieStmtList.MakeSingletonStmtList(), SolToBoogie.ProcedureTranslator.MkNewLocalVariableWithType(), SolToBoogie.TranslatorFlags.ModelReverts, SolToBoogie.ProcedureTranslator.TranslateExpr(), and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.ProcedureTranslator.TranslateExternalFunctionCall(), and SolToBoogie.ProcedureTranslator.Visit().
TranslateTypeCast()
void SolToBoogie.ProcedureTranslator.TranslateTypeCast (FunctionCall node, BoogieExpr lhs, out bool isElemenentaryTypeCast) inline private
Parameters
node
lhs
isElemenentaryTypeCast indicates if the cast of to an elementary type, often used in specifications
Definition at line 3378 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolidityAST.FunctionCall.Arguments, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentExpr, SolToBoogie.ProcedureTranslator.currentStmtList, SolidityAST.FunctionCall.Expression, SolToBoogie.TranslatorContext.GetASTNodeById(), SolToBoogie.Extensions.GetNumberFromEnd(), SolToBoogie.TranslatorContext.GetSubTypesOfContract(), SolidityAST.FunctionCall.Kind, SolidityAST.Identifier.ReferencedDeclaration, SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.TranslatorContext.TranslateFlags, SolToBoogie.TranslatorFlags.UseModularArithmetic, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
TranslateUsingLibraryCall()
void SolToBoogie.ProcedureTranslator.TranslateUsingLibraryCall (FunctionCall node, List< BoogieIdentifierExpr > outParams) inline private
Definition at line 3105 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentContract, SolToBoogie.ProcedureTranslator.currentStmtList, SolidityAST.FunctionCall.Expression, SolToBoogie.TranslatorContext.GetAllFuncDefinitions(), SolToBoogie.TranslatorContext.GetASTNodeById(), SolToBoogie.TransUtils.GetCanonicalFunctionName(), SolToBoogie.TranslatorContext.HasFuncSignature(), SolToBoogie.TransUtils.InferFunctionSignature(), SolidityAST.ContractDefinition.LinearizedBaseContracts, SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.TranslatorContext.UsingMap, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.TranslateExternalFunctionCall().
TranslateVeriSolCodeContractFuncCall()
BoogieExpr SolToBoogie.ProcedureTranslator.TranslateVeriSolCodeContractFuncCall (FunctionCall node) inline private
Definition at line 2505 of file ProcedureTranslator.cs.
References SolidityAST.FunctionCall.Arguments, SolToBoogie.MapArrayHelper.GetMemoryMapName(), SolToBoogie.ProcedureTranslator.GetVeriSolCodeContractFunction(), BoogieAST.BoogieType.Int, BoogieAST.BoogieType.Ref, SolToBoogie.ProcedureTranslator.TranslateExpr(), and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
updateAssignedSums()
void SolToBoogie.ProcedureTranslator.updateAssignedSums (BoogieBinaryOperation.Opcode op, List< Expression > exprs, List< BoogieExpr > boogieExprs) inline
Definition at line 1442 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.ProcedureTranslator.adjustSum(), BoogieAST.BoogieMapSelect.BaseExpr, SolToBoogie.ProcedureTranslator.currentStmtList, SolidityAST.Expression.TypeDescriptions, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
VeriSolAssert()
void SolToBoogie.ProcedureTranslator.VeriSolAssert (bool cond, string message = "") inline private
Definition at line 3473 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.currentContract, SolToBoogie.ProcedureTranslator.currentFunction, SolidityAST.ContractDefinition.Name, and SolidityAST.FunctionDefinition.Name.
Referenced by SolToBoogie.ProcedureTranslator.AddAssumeForUints(), SolToBoogie.ProcedureTranslator.AddModuloOp(), SolToBoogie.ProcedureTranslator.ExtractContractInvariants(), SolToBoogie.ProcedureTranslator.ExtractSpecifications(), SolToBoogie.ProcedureTranslator.GenerateConstructorWithBaseCalls(), SolToBoogie.ProcedureTranslator.GenerateDefaultConstructor(), SolToBoogie.ProcedureTranslator.GenerateInitializationForElementaryTypes(), SolToBoogie.ProcedureTranslator.GenerateNonDetExpr(), SolToBoogie.ProcedureTranslator.GetStaticDispatchingContract(), SolToBoogie.ProcedureTranslator.IsDynamicArrayPush(), SolToBoogie.ProcedureTranslator.IsGetterForPublicVariable(), SolToBoogie.ProcedureTranslator.MkFallbackDispatchCallCmd(), SolToBoogie.ProcedureTranslator.TranslateAbiEncodedFuncCall(), SolToBoogie.ProcedureTranslator.TranslateArrayLength(), SolToBoogie.ProcedureTranslator.TranslateCallStatement(), SolToBoogie.ProcedureTranslator.TranslateDynamicArrayPush(), SolToBoogie.ProcedureTranslator.TranslateDynamicDispatchCall(), SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.ProcedureTranslator.TranslateExternalFunctionCall(), SolToBoogie.ProcedureTranslator.TranslateInternalFunctionCall(), SolToBoogie.ProcedureTranslator.TranslateModifiesStmt(), SolToBoogie.ProcedureTranslator.TranslateNewStatement(), SolToBoogie.ProcedureTranslator.TranslateStatement(), SolToBoogie.ProcedureTranslator.TranslateStateVarDeclaration(), SolToBoogie.ProcedureTranslator.TranslateStructDefinition(), SolToBoogie.ProcedureTranslator.TranslateTypeCast(), SolToBoogie.ProcedureTranslator.TranslateUsingLibraryCall(), SolToBoogie.ProcedureTranslator.TranslateVeriSolCodeContractFuncCall(), SolToBoogie.ProcedureTranslator.updateAssignedSums(), and SolToBoogie.ProcedureTranslator.Visit().
Visit() [1/27]
override bool SolToBoogie.ProcedureTranslator.Visit (Assignment node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 1456 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.AddModuloOp(), BoogieAST.BoogieStmtList.AddStatement(), BoogieAST.BoogieStmtList.AppendStmtList(), SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.MapArrayHelper.InferExprTypeFromTypeString(), SolToBoogie.ProcedureTranslator.InstrumentForPrintingData(), SolToBoogie.TranslatorFlags.InstrumentSums, SolToBoogie.ProcedureTranslator.IsAbiEncodePackedFunc(), SolToBoogie.ProcedureTranslator.IsContractConstructor(), SolToBoogie.ProcedureTranslator.IsKeccakFunc(), SolToBoogie.ProcedureTranslator.IsStructConstructor(), SolToBoogie.ProcedureTranslator.IsTypeCast(), SolidityAST.Assignment.LeftHandSide, SolToBoogie.ProcedureTranslator.MkNewLocalVariableForFunctionReturn(), SolToBoogie.ProcedureTranslator.MkNewLocalVariableWithType(), SolidityAST.Assignment.Operator, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolidityAST.Assignment.RightHandSide, SolToBoogie.ProcedureTranslator.TranslateAbiEncodedFuncCall(), SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.TranslatorContext.TranslateFlags, SolToBoogie.ProcedureTranslator.TranslateFunctionCalls(), SolToBoogie.ProcedureTranslator.TranslateKeccakFuncCall(), SolToBoogie.ProcedureTranslator.TranslateNewStatement(), SolToBoogie.ProcedureTranslator.TranslateStructConstructor(), SolToBoogie.ProcedureTranslator.TranslateTypeCast(), SolidityAST.Expression.TypeDescriptions, SolToBoogie.ProcedureTranslator.updateAssignedSums(), and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Visit() [2/27]
override bool SolToBoogie.ProcedureTranslator.Visit (BinaryOperation node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 3538 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentExpr, SolidityAST.BinaryOperation.LeftExpression, SolidityAST.BinaryOperation.Operator, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolidityAST.BinaryOperation.RightExpression, SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.TranslatorContext.TranslateFlags, SolidityAST.Expression.TypeDescriptions, SolToBoogie.TranslatorFlags.UseModularArithmetic, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Visit() [3/27]
override bool SolToBoogie.ProcedureTranslator.Visit (Block node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 1326 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.ProcedureTranslator.preTranslationAction(), and SolToBoogie.ProcedureTranslator.TranslateStatement().
Visit() [4/27]
override bool SolToBoogie.ProcedureTranslator.Visit (Break node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 1955 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.ProcedureTranslator.currentStmtList, and SolToBoogie.ProcedureTranslator.preTranslationAction().
Visit() [5/27]
override bool SolToBoogie.ProcedureTranslator.Visit (Conditional node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 3647 of file ProcedureTranslator.cs.
References SolidityAST.Conditional.Condition, SolToBoogie.ProcedureTranslator.currentExpr, SolidityAST.Conditional.FalseExpression, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolToBoogie.ProcedureTranslator.TranslateExpr(), and SolidityAST.Conditional.TrueExpression.
Visit() [6/27]
override bool SolToBoogie.ProcedureTranslator.Visit (Continue node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 1963 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.preTranslationAction(), and SolidityAST.Continue.ToString().
Visit() [7/27]
override bool SolToBoogie.ProcedureTranslator.Visit (ContractDefinition node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 85 of file ProcedureTranslator.cs.
References SolidityAST.ASTNode.Accept(), SolToBoogie.ProcedureTranslator.context, SolidityAST.ContractDefinition.ContractKind, SolToBoogie.ProcedureTranslator.currentContract, SolToBoogie.ProcedureTranslator.GenerateDefaultConstructor(), SolToBoogie.TranslatorContext.IsConstructorDefined(), SolidityAST.ContractDefinition.Name, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolToBoogie.ProcedureTranslator.TranslateStateVarDeclaration(), and SolToBoogie.ProcedureTranslator.TranslateStructDefinition().
Visit() [8/27]
override bool SolToBoogie.ProcedureTranslator.Visit (DoWhileStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 1929 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), BoogieAST.BoogieStmtList.AppendStmtList(), SolidityAST.DoWhileStatement.Body, SolidityAST.DoWhileStatement.Condition, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.ProcedureTranslator.emitGasCheck(), SolToBoogie.ProcedureTranslator.ExtractSpecifications(), SolToBoogie.TranslatorFlags.InstrumentGas, SolToBoogie.TranslatorFlags.ModelReverts, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.TranslatorContext.TranslateFlags, and SolToBoogie.ProcedureTranslator.TranslateStatement().
Visit() [9/27]
override bool SolToBoogie.ProcedureTranslator.Visit (EnumDefinition node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 162 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.preTranslationAction().
Visit() [10/27]
override bool SolToBoogie.ProcedureTranslator.Visit (ExpressionStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 1969 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.AddAssumeForUints(), SolToBoogie.ProcedureTranslator.AddModuloOp(), BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.ProcedureTranslator.adjustSum(), BoogieAST.BoogieCmd.Attributes, BoogieAST.BoogieMapSelect.BaseExpr, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentStmtList, SolidityAST.ExpressionStatement.Expression, SolToBoogie.ProcedureTranslator.getSumAccess(), SolToBoogie.TranslatorFlags.InstrumentSums, SolToBoogie.TranslatorFlags.NoDataValuesInfoFlag, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.TranslatorContext.TranslateFlags, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Visit() [11/27]
override bool SolToBoogie.ProcedureTranslator.Visit (ForStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 1802 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), BoogieAST.BoogieStmtList.AppendStmtList(), SolidityAST.ForStatement.Body, SolidityAST.ForStatement.Condition, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.ProcedureTranslator.emitGasCheck(), SolToBoogie.ProcedureTranslator.ExtractSpecifications(), SolidityAST.ForStatement.InitializationExpression, SolToBoogie.TranslatorFlags.InstrumentGas, SolidityAST.ForStatement.LoopExpression, SolToBoogie.TranslatorFlags.ModelReverts, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.TranslatorContext.TranslateFlags, and SolToBoogie.ProcedureTranslator.TranslateStatement().
Visit() [12/27]
override bool SolToBoogie.ProcedureTranslator.Visit (FunctionCall node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 2331 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolidityAST.FunctionCall.Arguments, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentContract, SolToBoogie.ProcedureTranslator.currentExpr, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.ProcedureTranslator.emitRevertLogic(), SolidityAST.FunctionCall.Expression, SolToBoogie.TransUtils.GetFuncNameFromFuncCall(), SolToBoogie.TranslatorContext.HasEventNameInContract(), SolToBoogie.ProcedureTranslator.IsAbiEncodePackedFunc(), SolToBoogie.ProcedureTranslator.IsBuiltInTransferFunc(), SolToBoogie.ProcedureTranslator.IsContractConstructor(), SolToBoogie.ProcedureTranslator.IsDynamicArrayPush(), SolToBoogie.ProcedureTranslator.IsExternalFunctionCall(), SolToBoogie.ProcedureTranslator.IsImplicitFunc(), SolToBoogie.ProcedureTranslator.IsKeccakFunc(), SolToBoogie.ProcedureTranslator.IsStructConstructor(), SolToBoogie.ProcedureTranslator.IsTypeCast(), SolToBoogie.ProcedureTranslator.IsVeriSolCodeContractFunction(), SolToBoogie.ProcedureTranslator.MkNewLocalVariableForFunctionReturn(), SolToBoogie.TranslatorFlags.ModelReverts, SolidityAST.ContractDefinition.Name, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolToBoogie.ProcedureTranslator.TranslateAbiEncodedFuncCall(), SolToBoogie.ProcedureTranslator.TranslateCallStatement(), SolToBoogie.ProcedureTranslator.TranslateDynamicArrayPush(), SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.ProcedureTranslator.TranslateExternalFunctionCall(), SolToBoogie.TranslatorContext.TranslateFlags, SolToBoogie.ProcedureTranslator.TranslateInternalFunctionCall(), SolToBoogie.ProcedureTranslator.TranslateKeccakFuncCall(), SolToBoogie.ProcedureTranslator.TranslateNewStatement(), SolToBoogie.ProcedureTranslator.TranslateSendCallStmt(), SolToBoogie.ProcedureTranslator.TranslateStructConstructor(), SolToBoogie.ProcedureTranslator.TranslateTransferCallStmt(), SolToBoogie.ProcedureTranslator.TranslateTypeCast(), SolToBoogie.ProcedureTranslator.TranslateVeriSolCodeContractFuncCall(), SolidityAST.Expression.TypeDescriptions, SolidityAST.TypeDescription.TypeString, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Visit() [13/27]
override bool SolToBoogie.ProcedureTranslator.Visit (FunctionDefinition node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 277 of file ProcedureTranslator.cs.
References SolidityAST.ParameterList.Accept(), BoogieAST.BoogieProgram.AddDeclaration(), BoogieAST.BoogieProcedure.AddPostConditions(), BoogieAST.BoogieProcedure.AddPreConditions(), BoogieAST.BoogieStmtList.AddStatement(), BoogieAST.BoogieStmtList.AppendStmtList(), SolidityAST.FunctionDefinition.Body, SolToBoogie.ProcedureTranslator.boogieToLocalVarsMap, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.contractInvariants, SolidityAST.ContractDefinition.ContractKind, SolToBoogie.ProcedureTranslator.currentBoogieProc, SolToBoogie.ProcedureTranslator.currentContract, SolToBoogie.ProcedureTranslator.currentFunction, SolToBoogie.ProcedureTranslator.currentParamList, SolToBoogie.ProcedureTranslator.currentPostlude, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.ProcedureTranslator.ExtractSpecifications(), SolToBoogie.ProcedureTranslator.GenerateConstructorWithBaseCalls(), SolToBoogie.ProcedureTranslator.GenerateInitializationStmts(), SolToBoogie.ProcedureTranslator.genInlineAttrsInBpl, SolToBoogie.TransUtils.GetDefaultArguments(), SolToBoogie.TransUtils.GetDefaultInParams(), SolidityAST.FunctionDefinition.Implemented, SolToBoogie.ProcedureTranslator.inlineAssemblyPresent, SolidityAST.FunctionDefinition.IsConstructor, SolidityAST.FunctionDefinition.IsFallback, SolToBoogie.TranslatorContext.IsMethodInIgnoredSet(), SolToBoogie.ProcedureTranslator.isReturnParameterList, SolToBoogie.ProcedureTranslator.IsVeriSolContractInvariantFunction(), SolidityAST.FunctionDefinition.Modifiers, SolToBoogie.TranslatorContext.ModifierToBoogiePostImpl, SolToBoogie.TranslatorContext.ModifierToBoogiePreImpl, SolToBoogie.TranslatorContext.ModifierToPreludeLocalVars, SolidityAST.ContractDefinition.Name, SolidityAST.FunctionDefinition.Name, SolidityAST.CallableDeclaration.Parameters, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolToBoogie.ProcedureTranslator.PrintArguments(), SolToBoogie.TranslatorContext.Program, SolidityAST.CallableDeclaration.ReturnParameters, SolidityAST.FunctionDefinition.StateMutability, SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.ProcedureTranslator.TranslateStatement(), SolToBoogie.ProcedureTranslator.VeriSolAssert(), and SolidityAST.FunctionDefinition.Visibility.
Visit() [14/27]
override bool SolToBoogie.ProcedureTranslator.Visit (Identifier node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 2164 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentExpr, SolToBoogie.TranslatorContext.GetASTNodeById(), SolToBoogie.TransUtils.GetCanonicalLocalVariableName(), SolToBoogie.TransUtils.GetCanonicalStateVariableName(), SolToBoogie.TranslatorContext.HasASTNodeId(), SolidityAST.Identifier.Name, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolidityAST.Identifier.ReferencedDeclaration, SolidityAST.VariableDeclaration.StateVariable, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Visit() [15/27]
override bool SolToBoogie.ProcedureTranslator.Visit (IfStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 1764 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolidityAST.IfStatement.Condition, SolToBoogie.ProcedureTranslator.currentStmtList, SolidityAST.IfStatement.FalseBody, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.ProcedureTranslator.TranslateStatement(), and SolidityAST.IfStatement.TrueBody.
Visit() [16/27]
override bool SolToBoogie.ProcedureTranslator.Visit (IndexAccess node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 3660 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolidityAST.IndexAccess.BaseExpression, BoogieAST.BoogieType.Bool, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentExpr, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.ProcedureTranslator.GetCallExprForZeroInit(), SolToBoogie.MapArrayHelper.GetMemoryMapName(), SolToBoogie.MapArrayHelper.GetMemoryMapSelectExpr(), SolToBoogie.ProcedureTranslator.getSumAccess(), SolToBoogie.MapArrayHelper.GetValueTypeString(), SolidityAST.IndexAccess.IndexExpression, SolToBoogie.MapArrayHelper.InferExprTypeFromTypeString(), SolToBoogie.MapArrayHelper.InferKeyTypeFromTypeString(), SolToBoogie.MapArrayHelper.InferValueTypeFromTypeString(), SolToBoogie.TranslatorFlags.InstrumentSums, BoogieAST.BoogieType.Int, SolToBoogie.MapArrayHelper.IsArrayTypeString(), SolToBoogie.MapArrayHelper.IsMappingTypeString(), SolToBoogie.TranslatorFlags.LazyNestedAlloc, SolToBoogie.ProcedureTranslator.MkNewLocalVariableWithType(), SolToBoogie.QVarGenerator.NewQVar(), SolToBoogie.ProcedureTranslator.preTranslationAction(), SolToBoogie.TranslatorFlags.QuantFreeAllocs, BoogieAST.BoogieType.Ref, SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.TranslatorContext.TranslateFlags, SolidityAST.Expression.TypeDescriptions, and SolidityAST.TypeDescription.TypeString.
Visit() [17/27]
override bool SolToBoogie.ProcedureTranslator.Visit (InlineAssembly node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 3790 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.preTranslationAction().
Visit() [18/27]
override bool SolToBoogie.ProcedureTranslator.Visit (Literal node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 2109 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.currentExpr, SolidityAST.Literal.Kind, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolToBoogie.ProcedureTranslator.TranslateNumberToExpr(), SolidityAST.Literal.Value, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Visit() [19/27]
override bool SolToBoogie.ProcedureTranslator.Visit (MemberAccess node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 2199 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentExpr, SolidityAST.MemberAccess.Expression, SolToBoogie.ProcedureTranslator.GenerateNonDetExpr(), SolToBoogie.TranslatorContext.GetASTNodeById(), SolToBoogie.TransUtils.GetEnumValueIndex(), SolToBoogie.TranslatorContext.HasASTNodeId(), SolidityAST.MemberAccess.MemberName, SolidityAST.Identifier.Name, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolidityAST.Identifier.ReferencedDeclaration, SolidityAST.MemberAccess.ToString(), SolToBoogie.ProcedureTranslator.TranslateArrayLength(), SolToBoogie.ProcedureTranslator.TranslateBalance(), SolToBoogie.ProcedureTranslator.TranslateExpr(), SolidityAST.Expression.TypeDescriptions, SolidityAST.TypeDescription.TypeString, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Visit() [20/27]
override bool SolToBoogie.ProcedureTranslator.Visit (ModifierDefinition node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 506 of file ProcedureTranslator.cs.
References SolidityAST.ModifierDefinition.Body, SolToBoogie.ProcedureTranslator.boogieToLocalVarsMap, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentBoogieProc, SolToBoogie.TranslatorContext.ModifierToBoogiePostImpl, SolToBoogie.TranslatorContext.ModifierToBoogiePreImpl, SolToBoogie.TranslatorContext.ModifierToPreludeLocalVars, SolidityAST.ModifierDefinition.Name, SolToBoogie.ProcedureTranslator.preTranslationAction(), and SolToBoogie.ProcedureTranslator.TranslateStatement().
Visit() [21/27]
override bool SolToBoogie.ProcedureTranslator.Visit (ParameterList node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 1245 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentParamList, SolToBoogie.TransUtils.GetBoogieTypeFromSolidityTypeName(), SolToBoogie.TransUtils.GetCanonicalLocalVariableName(), SolToBoogie.ProcedureTranslator.isReturnParameterList, SolidityAST.VariableDeclaration.Name, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolToBoogie.TranslatorContext.TranslateFlags, SolidityAST.VariableDeclaration.TypeDescriptions, SolidityAST.VariableDeclaration.TypeName, and SolToBoogie.TranslatorFlags.UseModularArithmetic.
Visit() [22/27]
override bool SolToBoogie.ProcedureTranslator.Visit (PlaceholderStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 1340 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.preTranslationAction().
Visit() [23/27]
override bool SolToBoogie.ProcedureTranslator.Visit (Return node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 1648 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), BoogieAST.BoogieStmtList.AppendStmtList(), SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentFunction, SolToBoogie.ProcedureTranslator.currentPostlude, SolToBoogie.ProcedureTranslator.currentStmtList, SolidityAST.Return.Expression, SolToBoogie.TransUtils.GetCanonicalLocalVariableName(), BoogieAST.BoogieStmtList.MakeSingletonStmtList(), SolidityAST.ParameterList.Parameters, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolidityAST.CallableDeclaration.ReturnParameters, SolToBoogie.ProcedureTranslator.TranslateExpr(), and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Visit() [24/27]
override bool SolToBoogie.ProcedureTranslator.Visit (Throw node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 1748 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AppendStmtList(), SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.ProcedureTranslator.emitRevertLogic(), BoogieAST.BoogieStmtList.MakeSingletonStmtList(), SolToBoogie.TranslatorFlags.ModelReverts, SolToBoogie.ProcedureTranslator.preTranslationAction(), and SolToBoogie.TranslatorContext.TranslateFlags.
Visit() [25/27]
override bool SolToBoogie.ProcedureTranslator.Visit (UnaryOperation node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 3483 of file ProcedureTranslator.cs.
References SolToBoogie.ProcedureTranslator.AddAssumeForUints(), BoogieAST.BoogieStmtList.AddStatement(), BoogieAST.BoogieCmd.Attributes, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentExpr, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.MapArrayHelper.InferExprTypeFromTypeString(), SolToBoogie.ProcedureTranslator.MkNewLocalVariableWithType(), SolToBoogie.TranslatorFlags.NoDataValuesInfoFlag, SolidityAST.UnaryOperation.Operator, SolidityAST.UnaryOperation.Prefix, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolidityAST.UnaryOperation.SubExpression, SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.TranslatorContext.TranslateFlags, SolidityAST.Expression.TypeDescriptions, SolidityAST.TypeDescription.TypeString, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Visit() [26/27]
override bool SolToBoogie.ProcedureTranslator.Visit (VariableDeclarationStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 1346 of file ProcedureTranslator.cs.
References SolidityAST.Assignment.Accept(), BoogieAST.BoogieStmtList.AppendStmtList(), SolToBoogie.ProcedureTranslator.boogieToLocalVarsMap, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentBoogieProc, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.TransUtils.GetBoogieTypeFromSolidityTypeName(), SolToBoogie.TransUtils.GetCanonicalLocalVariableName(), SolidityAST.ASTNode.Id, SolidityAST.Assignment.LeftHandSide, BoogieAST.BoogieStmtList.MakeSingletonStmtList(), SolidityAST.VariableDeclaration.Name, SolidityAST.Identifier.Name, SolidityAST.Assignment.Operator, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolidityAST.Identifier.ReferencedDeclaration, SolidityAST.Assignment.RightHandSide, SolToBoogie.TranslatorContext.TranslateFlags, SolidityAST.VariableDeclaration.TypeDescriptions, SolidityAST.Expression.TypeDescriptions, SolidityAST.VariableDeclaration.TypeName, SolToBoogie.TranslatorFlags.UseModularArithmetic, and SolToBoogie.ProcedureTranslator.VeriSolAssert().
Visit() [27/27]
override bool SolToBoogie.ProcedureTranslator.Visit (WhileStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 1782 of file ProcedureTranslator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolidityAST.WhileStatement.Body, SolidityAST.WhileStatement.Condition, SolToBoogie.ProcedureTranslator.context, SolToBoogie.ProcedureTranslator.currentStmtList, SolToBoogie.ProcedureTranslator.emitGasCheck(), SolToBoogie.ProcedureTranslator.ExtractSpecifications(), SolToBoogie.TranslatorFlags.InstrumentGas, SolToBoogie.TranslatorFlags.ModelReverts, SolToBoogie.ProcedureTranslator.preTranslationAction(), SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.TranslatorContext.TranslateFlags, and SolToBoogie.ProcedureTranslator.TranslateStatement().
Member Data Documentation
boogieToLocalVarsMap
Dictionary<string, List<BoogieVariable> > SolToBoogie.ProcedureTranslator.boogieToLocalVarsMap private
Definition at line 21 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.CreateDistinctArrayMappingAddress(), SolToBoogie.ProcedureTranslator.GenerateConstructorWithBaseCalls(), SolToBoogie.ProcedureTranslator.GenerateDefaultConstructor(), SolToBoogie.ProcedureTranslator.GenerateInitializationForStructStateVar(), SolToBoogie.ProcedureTranslator.MkNewLocalVariableWithType(), SolToBoogie.ProcedureTranslator.ProcedureTranslator(), SolToBoogie.ProcedureTranslator.TranslateDynamicArrayPush(), SolToBoogie.ProcedureTranslator.TranslateExternalFunctionCall(), SolToBoogie.ProcedureTranslator.TranslateNewStatement(), SolToBoogie.ProcedureTranslator.TranslateStructConstructor(), and SolToBoogie.ProcedureTranslator.Visit().
context
TranslatorContext SolToBoogie.ProcedureTranslator.context private
Definition at line 18 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.AddAssumeForUints(), SolToBoogie.ProcedureTranslator.AddModuloOp(), SolToBoogie.ProcedureTranslator.CreateDistinctArrayMappingAddress(), SolToBoogie.ProcedureTranslator.GenerateConstructorWithBaseCalls(), SolToBoogie.ProcedureTranslator.GenerateDefaultConstructor(), SolToBoogie.ProcedureTranslator.GenerateInitializationForArrayStateVar(), SolToBoogie.ProcedureTranslator.GenerateInitializationForElementaryTypes(), SolToBoogie.ProcedureTranslator.GenerateInitializationForMappingStateVar(), SolToBoogie.ProcedureTranslator.GenerateInitializationForStructStateVar(), SolToBoogie.ProcedureTranslator.GenerateInitializationStmts(), SolToBoogie.ProcedureTranslator.GetBoogieTypesFromMapping(), SolToBoogie.ProcedureTranslator.GetModifierInvocationOfBase(), SolToBoogie.ProcedureTranslator.GetStaticDispatchingContract(), SolToBoogie.ProcedureTranslator.InitializeNestedArrayMappingStateVar(), SolToBoogie.ProcedureTranslator.InstrumentForPrintingData(), SolToBoogie.ProcedureTranslator.InstrumentSourceFileAndLineInfo(), SolToBoogie.ProcedureTranslator.IsExternalFunctionCall(), SolToBoogie.ProcedureTranslator.IsGetterForPublicVariable(), SolToBoogie.ProcedureTranslator.IsLibraryFunctionCall(), SolToBoogie.ProcedureTranslator.IsStaticDispatching(), SolToBoogie.ProcedureTranslator.MkNewLocalVariableWithType(), SolToBoogie.ProcedureTranslator.preTranslationAction(), SolToBoogie.ProcedureTranslator.ProcedureTranslator(), SolToBoogie.ProcedureTranslator.TranslateDynamicArrayPush(), SolToBoogie.ProcedureTranslator.TranslateDynamicDispatchCall(), SolToBoogie.ProcedureTranslator.TranslateExternalFunctionCall(), SolToBoogie.ProcedureTranslator.TranslateNewStatement(), SolToBoogie.ProcedureTranslator.TranslateSendCallStmt(), SolToBoogie.ProcedureTranslator.TranslateStatement(), SolToBoogie.ProcedureTranslator.TranslateStateVarDeclaration(), SolToBoogie.ProcedureTranslator.TranslateStructConstructor(), SolToBoogie.ProcedureTranslator.TranslateStructDefinition(), SolToBoogie.ProcedureTranslator.TranslateTransferCallStmt(), SolToBoogie.ProcedureTranslator.TranslateTypeCast(), SolToBoogie.ProcedureTranslator.TranslateUsingLibraryCall(), and SolToBoogie.ProcedureTranslator.Visit().
contractInvariants
Dictionary<string, List<BoogieExpr> > SolToBoogie.ProcedureTranslator.contractInvariants = null private
Definition at line 45 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.ProcedureTranslator(), and SolToBoogie.ProcedureTranslator.Visit().
currentBoogieProc
string SolToBoogie.ProcedureTranslator.currentBoogieProc = null private
Definition at line 24 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.CreateDistinctArrayMappingAddress(), SolToBoogie.ProcedureTranslator.GenerateConstructorWithBaseCalls(), SolToBoogie.ProcedureTranslator.GenerateDefaultConstructor(), SolToBoogie.ProcedureTranslator.GenerateInitializationForStructStateVar(), SolToBoogie.ProcedureTranslator.MkNewLocalVariableWithType(), SolToBoogie.ProcedureTranslator.TranslateDynamicArrayPush(), SolToBoogie.ProcedureTranslator.TranslateExternalFunctionCall(), SolToBoogie.ProcedureTranslator.TranslateNewStatement(), SolToBoogie.ProcedureTranslator.TranslateStructConstructor(), and SolToBoogie.ProcedureTranslator.Visit().
currentContract
ContractDefinition SolToBoogie.ProcedureTranslator.currentContract = null private
Definition at line 30 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.GenerateConstructorWithBaseCalls(), SolToBoogie.ProcedureTranslator.GenerateDefaultConstructor(), SolToBoogie.ProcedureTranslator.TranslateDynamicDispatchCall(), SolToBoogie.ProcedureTranslator.TranslateUsingLibraryCall(), SolToBoogie.ProcedureTranslator.VeriSolAssert(), and SolToBoogie.ProcedureTranslator.Visit().
currentExpr
BoogieExpr SolToBoogie.ProcedureTranslator.currentExpr private
Definition at line 2071 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.Equals(), SolToBoogie.ProcedureTranslator.TranslateCallStatement(), SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.ProcedureTranslator.TranslateTypeCast(), and SolToBoogie.ProcedureTranslator.Visit().
currentFunction
FunctionDefinition SolToBoogie.ProcedureTranslator.currentFunction = null private
Definition at line 32 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.VeriSolAssert(), and SolToBoogie.ProcedureTranslator.Visit().
currentParamList
List<BoogieVariable> SolToBoogie.ProcedureTranslator.currentParamList private
Definition at line 1242 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.Visit().
currentPostlude
BoogieStmtList SolToBoogie.ProcedureTranslator.currentPostlude = null private
Definition at line 39 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.Visit().
currentSourceFile
string SolToBoogie.ProcedureTranslator.currentSourceFile = null private
Definition at line 35 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.InstrumentSourceFileAndLineInfo().
currentSourceLine
int SolToBoogie.ProcedureTranslator.currentSourceLine = -1 private
Definition at line 36 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.InstrumentSourceFileAndLineInfo().
currentStmtList
BoogieStmtList SolToBoogie.ProcedureTranslator.currentStmtList = null private
Definition at line 1279 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.AddAssumeForUints(), SolToBoogie.ProcedureTranslator.AddUnsignedTypeAssumeCmd(), SolToBoogie.ProcedureTranslator.GenerateConstructorWithBaseCalls(), SolToBoogie.ProcedureTranslator.GenerateInitializationForArrayStateVar(), SolToBoogie.ProcedureTranslator.GenerateInitializationForElementaryTypes(), SolToBoogie.ProcedureTranslator.GenerateInitializationForMappingStateVar(), SolToBoogie.ProcedureTranslator.GenerateInitializationForStructStateVar(), SolToBoogie.ProcedureTranslator.GenerateInitializationStmts(), SolToBoogie.ProcedureTranslator.GenerateNonDetExpr(), SolToBoogie.ProcedureTranslator.InitializeNestedArrayMappingStateVar(), SolToBoogie.ProcedureTranslator.MkNewLocalVariableForFunctionReturn(), SolToBoogie.ProcedureTranslator.preTranslationAction(), SolToBoogie.ProcedureTranslator.PrintArguments(), SolToBoogie.ProcedureTranslator.TranslateAbiEncodedFuncCall(), SolToBoogie.ProcedureTranslator.TranslateCallStatement(), SolToBoogie.ProcedureTranslator.TranslateDynamicArrayPush(), SolToBoogie.ProcedureTranslator.TranslateDynamicDispatchCall(), SolToBoogie.ProcedureTranslator.TranslateInternalFunctionCall(), SolToBoogie.ProcedureTranslator.TranslateKeccakFuncCall(), SolToBoogie.ProcedureTranslator.TranslateNewStatement(), SolToBoogie.ProcedureTranslator.TranslateSendCallStmt(), SolToBoogie.ProcedureTranslator.TranslateStatement(), SolToBoogie.ProcedureTranslator.TranslateStructConstructor(), SolToBoogie.ProcedureTranslator.TranslateTransferCallStmt(), SolToBoogie.ProcedureTranslator.TranslateTypeCast(), SolToBoogie.ProcedureTranslator.TranslateUsingLibraryCall(), SolToBoogie.ProcedureTranslator.updateAssignedSums(), and SolToBoogie.ProcedureTranslator.Visit().
genInlineAttrsInBpl
bool SolToBoogie.ProcedureTranslator.genInlineAttrsInBpl private
Definition at line 42 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.ProcedureTranslator(), and SolToBoogie.ProcedureTranslator.Visit().
inlineAssemblyPresent
bool SolToBoogie.ProcedureTranslator.inlineAssemblyPresent = false private
Definition at line 27 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.Visit().
isReturnParameterList
bool SolToBoogie.ProcedureTranslator.isReturnParameterList = false private
Definition at line 1243 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.Visit().
Property Documentation
ContractInvariants
Dictionary<string, List<BoogieExpr> > SolToBoogie.ProcedureTranslator.ContractInvariants get
Definition at line 2073 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.ProcedureTranslator.Equals(), and SolToBoogie.BoogieTranslator.Translate().
The documentation for this class was generated from the following file:
Sources/SolToBoogie/ProcedureTranslator.cs