VeriSol: SolidityAST.UsingForDirective Class Reference
SolidityAST.UsingForDirective Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
UserDefinedTypeName LibraryName [get, set]
TypeName TypeName [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 239 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.UsingForDirective.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 245 of file SolidityAST.cs.
References SolidityAST.ASTNode.Accept(), SolidityAST.UserDefinedTypeName.Accept(), SolidityAST.IASTVisitor.EndVisit(), SolidityAST.UsingForDirective.LibraryName, and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.UsingForDirective.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 258 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.UsingForDirective.ToString () inline
Definition at line 263 of file SolidityAST.cs.
References SolidityAST.UsingForDirective.LibraryName, and SolidityAST.UserDefinedTypeName.Name.
Property Documentation
LibraryName
UserDefinedTypeName SolidityAST.UsingForDirective.LibraryName get set
Definition at line 241 of file SolidityAST.cs.
Referenced by SolidityAST.UsingForDirective.Accept(), SolidityAST.UsingForDirective.ToString(), and SolToBoogie.UsingCollector.Visit().
TypeName
TypeName SolidityAST.UsingForDirective.TypeName get set
Definition at line 243 of file SolidityAST.cs.
Referenced by SolToBoogie.UsingCollector.Visit().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs