VeriSol: SolToBoogie.ResolutionHelper Class Reference
SolToBoogie.ResolutionHelper Class Reference
Public Member Functions
ResolutionHelper (TranslatorContext context)
List< ContractDefinition > TopologicalSortByDependency (HashSet< ContractDefinition > contracts)
Private Member Functions
void TopologicalSortImpl (HashSet< ContractDefinition > visited, ContractDefinition contract, List< ContractDefinition > result)
bool AllDependenciesVisited (HashSet< ContractDefinition > visited, ContractDefinition contract)
Private Attributes
TranslatorContext context
Detailed Description
Definition at line 9 of file ResolutionHelper.cs.
Constructor & Destructor Documentation
ResolutionHelper()
SolToBoogie.ResolutionHelper.ResolutionHelper (TranslatorContext context) inline
Definition at line 13 of file ResolutionHelper.cs.
References SolToBoogie.ResolutionHelper.context.
Member Function Documentation
AllDependenciesVisited()
bool SolToBoogie.ResolutionHelper.AllDependenciesVisited (HashSet< ContractDefinition > visited, ContractDefinition contract) inline private
Definition at line 55 of file ResolutionHelper.cs.
References SolToBoogie.ResolutionHelper.context, SolidityAST.ContractDefinition.ContractDependencies, and SolToBoogie.TranslatorContext.GetASTNodeById().
Referenced by SolToBoogie.ResolutionHelper.TopologicalSortImpl().
TopologicalSortByDependency()
List<ContractDefinition> SolToBoogie.ResolutionHelper.TopologicalSortByDependency (HashSet< ContractDefinition > contracts) inline
Definition at line 20 of file ResolutionHelper.cs.
References SolToBoogie.ResolutionHelper.TopologicalSortImpl().
Referenced by SolToBoogie.FunctionEventResolver.ResolveFunctions(), and SolToBoogie.StateVariableResolver.ResolveStateVariables().
TopologicalSortImpl()
void SolToBoogie.ResolutionHelper.TopologicalSortImpl (HashSet< ContractDefinition > visited, ContractDefinition contract, List< ContractDefinition > result) inline private
Definition at line 37 of file ResolutionHelper.cs.
References SolToBoogie.ResolutionHelper.AllDependenciesVisited(), SolToBoogie.ResolutionHelper.context, SolidityAST.ContractDefinition.ContractDependencies, and SolToBoogie.TranslatorContext.GetASTNodeById().
Referenced by SolToBoogie.ResolutionHelper.TopologicalSortByDependency().
Member Data Documentation
context
TranslatorContext SolToBoogie.ResolutionHelper.context private
Definition at line 11 of file ResolutionHelper.cs.
Referenced by SolToBoogie.ResolutionHelper.AllDependenciesVisited(), SolToBoogie.ResolutionHelper.ResolutionHelper(), and SolToBoogie.ResolutionHelper.TopologicalSortImpl().
The documentation for this class was generated from the following file:
Sources/SolToBoogie/ResolutionHelper.cs