VeriSol: SolidityAST.EventDefinition Class Reference
SolidityAST.EventDefinition Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
string Name [get, set]
string Documentation [get, set]
bool Anonymous [get, set]
Properties inherited from SolidityAST.CallableDeclaration
ParameterList Parameters [get, set]
ParameterList ReturnParameters [get, set]
Properties inherited from SolidityAST.Declaration
int Scope [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 609 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.EventDefinition.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 617 of file SolidityAST.cs.
References SolidityAST.ParameterList.Accept(), SolidityAST.IASTVisitor.EndVisit(), SolidityAST.CallableDeclaration.Parameters, and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.EventDefinition.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 626 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.EventDefinition.ToString () inline
Definition at line 631 of file SolidityAST.cs.
References SolidityAST.EventDefinition.Name, and SolidityAST.CallableDeclaration.Parameters.
Property Documentation
Anonymous
bool SolidityAST.EventDefinition.Anonymous get set
Definition at line 615 of file SolidityAST.cs.
Documentation
string SolidityAST.EventDefinition.Documentation get set
Definition at line 613 of file SolidityAST.cs.
Name
string SolidityAST.EventDefinition.Name get set
Definition at line 611 of file SolidityAST.cs.
Referenced by SolToBoogie.TransUtils.ComputeEventSignature(), SolToBoogie.TranslatorContext.HasEventNameInContract(), and SolidityAST.EventDefinition.ToString().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs