VeriSol: SolidityAST.TestMain Class Reference
SolidityAST.TestMain Class Reference
Static Public Member Functions
static void Main (string[] args)
Static Private Member Functions
static void LegacyMain (string[] args)
Detailed Description
Definition at line 9 of file TestMain.cs.
Member Function Documentation
LegacyMain()
static void SolidityAST.TestMain.LegacyMain (string[] args) inline static private
Definition at line 27 of file TestMain.cs.
References SolidityAST.SolidityCompiler.Compile(), and SolidityAST.AST.GetSourceUnits().
Main()
static void SolidityAST.TestMain.Main (string[] args) inline static
Definition at line 11 of file TestMain.cs.
References SolidityAST.RegressionExecutor.BatchExecute().
The documentation for this class was generated from the following file:
Sources/SolidityAST/TestMain.cs