VeriSol: SolToBoogieTest.RegressionExecutor Class Reference
SolToBoogieTest.RegressionExecutor Class Reference
Public Types
enum class BatchExeResult {
Success , SolcError , SolToBoogieError , CorralError ,
OtherException
}
Public Member Functions
RegressionExecutor (string testDirectory, string configDirectory, string recordsDir, ILogger logger, string testPrefix="")
int BatchExecute ()
BatchExeResult Execute (string filename, out string expected, out string current)
Private Member Functions
void ParseTranslatorFlags (TranslatorFlags translatorFlags, string args)
string RunCorral (CorralConfiguration corralConfig)
BatchExeResult CompareCorralOutput (string expected, string actual)
string GenerateCorralArguments (CorralConfiguration corralConfig)
void ReadRecord ()
void DeleteTemporaryFiles ()
Private Attributes
string solcPath
string corralPath
string testDirectory
string configDirectory
string recordsDir
ILogger logger
string testPrefix
Static Private Attributes
static readonly int corralTimeoutInMilliseconds = TimeSpan.FromSeconds(60).Seconds * 1000
static readonly string outFile = "__SolToBoogieTest_out.bpl"
static Dictionary< string, bool > filesToRun = new Dictionary<string, bool>()
Detailed Description
Definition at line 17 of file RegressionExecutor.cs.
Member Enumeration Documentation
BatchExeResult
enum SolToBoogieTest.RegressionExecutor.BatchExeResult strong
Enumerator
Success
SolcError
SolToBoogieError
CorralError
OtherException
Definition at line 39 of file RegressionExecutor.cs.
Constructor & Destructor Documentation
RegressionExecutor()
SolToBoogieTest.RegressionExecutor.RegressionExecutor (string testDirectory, string configDirectory, string recordsDir, ILogger logger, string testPrefix = "") inline
Definition at line 41 of file RegressionExecutor.cs.
References VeriSolRunner.ExternalTools.ToolManager.Command, VeriSolRunner.ExternalTools.ExternalToolsManager.Corral, SolidityAST.RegressionExecutor.logger, VeriSolRunner.ExternalTools.ExternalToolsManager.Solc, and SolidityAST.RegressionExecutor.testDirectory.
Member Function Documentation
BatchExecute()
int SolToBoogieTest.RegressionExecutor.BatchExecute () inline
Definition at line 52 of file RegressionExecutor.cs.
References SolToBoogieTest.RegressionExecutor.DeleteTemporaryFiles(), SolidityAST.RegressionExecutor.Execute(), SolidityAST.RegressionExecutor.logger, SolToBoogieTest.RegressionExecutor.ReadRecord(), and SolidityAST.RegressionExecutor.testDirectory.
CompareCorralOutput()
BatchExeResult SolToBoogieTest.RegressionExecutor.CompareCorralOutput (string expected, string actual) inline private
Definition at line 245 of file RegressionExecutor.cs.
Referenced by SolToBoogieTest.RegressionExecutor.Execute().
DeleteTemporaryFiles()
void SolToBoogieTest.RegressionExecutor.DeleteTemporaryFiles () inline private
Definition at line 300 of file RegressionExecutor.cs.
Referenced by SolToBoogieTest.RegressionExecutor.BatchExecute().
Execute()
BatchExeResult SolToBoogieTest.RegressionExecutor.Execute (string filename, out string expected, out string current) inline
Definition at line 155 of file RegressionExecutor.cs.
References SolToBoogieTest.RegressionExecutor.CompareCorralOutput(), SolidityAST.SolidityCompiler.Compile(), SolidityAST.CompilerOutput.ContainsError(), SolToBoogieTest.CorralConfiguration.ExpectedResult, BoogieAST.BoogieAST.GetRoot(), SolToBoogieTest.RegressionExecutor.ParseTranslatorFlags(), SolidityAST.CompilerOutput.PrintErrorsToConsole(), SolToBoogieTest.RegressionExecutor.RunCorral(), SolidityAST.RegressionExecutor.solcPath, SolidityAST.RegressionExecutor.testDirectory, SolToBoogie.BoogieTranslator.Translate(), and SolToBoogieTest.CorralConfiguration.TranslatorOptions.
GenerateCorralArguments()
string SolToBoogieTest.RegressionExecutor.GenerateCorralArguments (CorralConfiguration corralConfig) inline private
Definition at line 266 of file RegressionExecutor.cs.
Referenced by SolToBoogieTest.RegressionExecutor.RunCorral().
ParseTranslatorFlags()
void SolToBoogieTest.RegressionExecutor.ParseTranslatorFlags (TranslatorFlags translatorFlags, string args) inline private
Definition at line 132 of file RegressionExecutor.cs.
References SolidityAST.RegressionExecutor.logger, and SolToBoogie.ParseUtils.ParseCommandLineArgs().
Referenced by SolToBoogieTest.RegressionExecutor.Execute().
ReadRecord()
void SolToBoogieTest.RegressionExecutor.ReadRecord () inline private
Definition at line 282 of file RegressionExecutor.cs.
Referenced by SolToBoogieTest.RegressionExecutor.BatchExecute().
RunCorral()
string SolToBoogieTest.RegressionExecutor.RunCorral (CorralConfiguration corralConfig) inline private
Definition at line 216 of file RegressionExecutor.cs.
References SolToBoogieTest.RegressionExecutor.GenerateCorralArguments().
Referenced by SolToBoogieTest.RegressionExecutor.Execute().
Member Data Documentation
configDirectory
string SolToBoogieTest.RegressionExecutor.configDirectory private
Definition at line 25 of file RegressionExecutor.cs.
corralPath
string SolToBoogieTest.RegressionExecutor.corralPath private
Definition at line 21 of file RegressionExecutor.cs.
corralTimeoutInMilliseconds
readonly int SolToBoogieTest.RegressionExecutor.corralTimeoutInMilliseconds = TimeSpan.FromSeconds(60).Seconds * 1000 static private
Definition at line 33 of file RegressionExecutor.cs.
filesToRun
Dictionary<string, bool> SolToBoogieTest.RegressionExecutor.filesToRun = new Dictionary<string, bool>() static private
Definition at line 37 of file RegressionExecutor.cs.
logger
ILogger SolToBoogieTest.RegressionExecutor.logger private
Definition at line 29 of file RegressionExecutor.cs.
outFile
readonly string SolToBoogieTest.RegressionExecutor.outFile = "__SolToBoogieTest_out.bpl" static private
Definition at line 35 of file RegressionExecutor.cs.
recordsDir
string SolToBoogieTest.RegressionExecutor.recordsDir private
Definition at line 27 of file RegressionExecutor.cs.
solcPath
string SolToBoogieTest.RegressionExecutor.solcPath private
Definition at line 19 of file RegressionExecutor.cs.
testDirectory
string SolToBoogieTest.RegressionExecutor.testDirectory private
Definition at line 23 of file RegressionExecutor.cs.
testPrefix
string SolToBoogieTest.RegressionExecutor.testPrefix private
Definition at line 31 of file RegressionExecutor.cs.
The documentation for this class was generated from the following file:
Sources/SolToBoogieTest/RegressionExecutor.cs