VeriSol: SolidityAST.WhileStatement Class Reference
SolidityAST.WhileStatement Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
Expression Condition [get, set]
Statement Body [get, set]
Properties inherited from SolidityAST.Statement
string Documnetation [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 1041 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.WhileStatement.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1047 of file SolidityAST.cs.
References SolidityAST.ASTNode.Accept(), SolidityAST.WhileStatement.Body, SolidityAST.WhileStatement.Condition, SolidityAST.IASTVisitor.EndVisit(), and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.WhileStatement.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1057 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.WhileStatement.ToString () inline
Definition at line 1062 of file SolidityAST.cs.
References SolidityAST.WhileStatement.Body, and SolidityAST.WhileStatement.Condition.
Property Documentation
Body
Statement SolidityAST.WhileStatement.Body get set
Definition at line 1045 of file SolidityAST.cs.
Referenced by SolidityAST.WhileStatement.Accept(), SolidityAST.WhileStatement.ToString(), and SolToBoogie.ProcedureTranslator.Visit().
Condition
Expression SolidityAST.WhileStatement.Condition get set
Definition at line 1043 of file SolidityAST.cs.
Referenced by SolidityAST.WhileStatement.Accept(), SolidityAST.WhileStatement.ToString(), and SolToBoogie.ProcedureTranslator.Visit().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs