VeriSol: BoogieAST.BoogieType Class Reference
BoogieAST.BoogieType Class Reference
Static Public Attributes
static readonly BoogieType Int = new BoogieBasicType(BoogieBasicType.SimpleType.INT)
static readonly BoogieType Bool = new BoogieBasicType(BoogieBasicType.SimpleType.BOOL)
static readonly BoogieType Ref = new BoogieCtorType("Ref")
Detailed Description
Definition at line 365 of file BoogieAST.cs.
Member Data Documentation
Bool
readonly BoogieType BoogieAST.BoogieType.Bool = new BoogieBasicType(BoogieBasicType.SimpleType.BOOL) static
Definition at line 368 of file BoogieAST.cs.
Referenced by SolToBoogie.RevertLogicGenerator.CreateSendFail(), SolToBoogie.RevertLogicGenerator.CreateSendSucess(), SolToBoogie.FallbackGenerator.Generate(), SolToBoogie.RevertLogicGenerator.Generate(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalImplementations(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalProcedureAllocMany(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalVariables(), SolToBoogie.HarnessGenerator.GenerateHoudiniVarsForContract(), SolToBoogie.ProcedureTranslator.GenerateInitializationForMappingStateVar(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroIntBoolArrayFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroRefBoolArrayFunction(), SolToBoogie.TransUtils.GetBoogieTypeFromSolidityTypeName(), SolToBoogie.MapArrayHelper.InferExprTypeFromTypeString(), SolToBoogie.ProcedureTranslator.TranslateCallStatement(), SolToBoogie.ProcedureTranslator.TranslateTransferCallStmt(), and SolToBoogie.ProcedureTranslator.Visit().
Int
readonly BoogieType BoogieAST.BoogieType.Int = new BoogieBasicType(BoogieBasicType.SimpleType.INT) static
Definition at line 367 of file BoogieAST.cs.
Referenced by SolToBoogie.TransUtils.CollectLocalVars(), SolToBoogie.RevertLogicGenerator.CreateSendFail(), SolToBoogie.RevertLogicGenerator.CreateSendSucess(), SolToBoogie.FallbackGenerator.Generate(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodedFunctionOneArg(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodedFunctionOneArgRef(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodedFunctionTwoArgs(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodedFunctionTwoArgsOneRef(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodePackedAxiomOneArg(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodePackedAxiomTwoArgs(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodePackedAxiomTwoArgsOneRef(), SolToBoogie.HarnessGenerator.GenerateBoogieHarnessForContract(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateConstToRefAxiom(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateConstToRefFunction(), SolToBoogie.HarnessGenerator.GenerateCorralChoiceProcForContract(), SolToBoogie.HarnessGenerator.GenerateCorralHarnessForContract(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalImplementations(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalVariables(), SolToBoogie.ProcedureTranslator.GenerateInitializationForMappingStateVar(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateKeccakAxiom(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateKeccakFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForArray(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateModFunction(), SolToBoogie.ProcedureTranslator.GenerateNonDetExpr(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateRefToInt(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateTypes(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateVeriSolSumAxioms(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateVeriSolSumFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroIntBoolArrayFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroIntIntArrayFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroIntRefArrayFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroRefIntArrayFunction(), SolToBoogie.TransUtils.GetBoogieTypeFromSolidityTypeName(), SolToBoogie.TransUtils.GetDefaultInParams(), SolToBoogie.MapArrayHelper.InferExprTypeFromTypeString(), SolToBoogie.MapArrayHelper.InferKeyTypeFromTypeString(), SolToBoogie.MapArrayHelper.InferValueTypeFromTypeString(), SolToBoogie.ProcedureTranslator.TranslateDynamicArrayPush(), SolToBoogie.ProcedureTranslator.TranslateExternalFunctionCall(), SolToBoogie.ProcedureTranslator.TranslateModifiesStmt(), SolToBoogie.ProcedureTranslator.TranslateSendCallStmt(), SolToBoogie.ProcedureTranslator.TranslateStructConstructor(), SolToBoogie.ProcedureTranslator.TranslateTransferCallStmt(), SolToBoogie.ProcedureTranslator.TranslateVeriSolCodeContractFuncCall(), and SolToBoogie.ProcedureTranslator.Visit().
Ref
readonly BoogieType BoogieAST.BoogieType.Ref = new BoogieCtorType("Ref") static
Definition at line 369 of file BoogieAST.cs.
Referenced by SolToBoogie.TransUtils.CollectLocalVars(), SolToBoogie.ProcedureTranslator.CreateDistinctArrayMappingAddress(), SolToBoogie.RevertLogicGenerator.CreateSendFail(), SolToBoogie.RevertLogicGenerator.CreateSendSucess(), SolToBoogie.FallbackGenerator.Generate(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodedFunctionOneArgRef(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodedFunctionTwoArgsOneRef(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodePackedAxiomOneArgRef(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodePackedAxiomTwoArgsOneRef(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateConstants(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateConstToRefFunction(), SolToBoogie.HarnessGenerator.GenerateCorralChoiceProcForContract(), SolToBoogie.HarnessGenerator.GenerateCorralHarnessForContract(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalImplementations(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalProcedureAllocMany(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalProcedureFresh(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalVariables(), SolToBoogie.ProcedureTranslator.GenerateInitializationForMappingStateVar(), SolToBoogie.ProcedureTranslator.GenerateInitializationForStructStateVar(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForArray(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForMapping(), SolToBoogie.ProcedureTranslator.GenerateNonDetExpr(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateRefToInt(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateSingleMemoryVariable(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateVeriSolSumAxioms(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateVeriSolSumFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroIntRefArrayFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroRefBoolArrayFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroRefIntArrayFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroRefRefArrayFunction(), SolToBoogie.TransUtils.GetBoogieTypeFromSolidityTypeName(), SolToBoogie.TransUtils.GetDefaultInParams(), SolToBoogie.MapArrayHelper.InferExprTypeFromTypeString(), SolToBoogie.MapArrayHelper.InferKeyTypeFromTypeString(), SolToBoogie.MapArrayHelper.InferValueTypeFromTypeString(), SolToBoogie.ProcedureTranslator.InitializeNestedArrayMappingStateVar(), SolToBoogie.ProcedureTranslator.TranslateModifiesStmt(), SolToBoogie.ProcedureTranslator.TranslateNewStatement(), SolToBoogie.ProcedureTranslator.TranslateStateVarDeclaration(), SolToBoogie.ProcedureTranslator.TranslateStructConstructor(), SolToBoogie.ProcedureTranslator.TranslateStructDefinition(), SolToBoogie.ProcedureTranslator.TranslateVeriSolCodeContractFuncCall(), and SolToBoogie.ProcedureTranslator.Visit().
The documentation for this class was generated from the following file:
Sources/BoogieAST/BoogieAST.cs