VeriSol: SolidityAST.VariableDeclarationStatement Class Reference
SolidityAST.VariableDeclarationStatement Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
List< int > Assignments [get, set]
List< VariableDeclaration > Declarations [get, set]
Expression InitialValue [get, set]
Properties inherited from SolidityAST.Statement
string Documnetation [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 1262 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.VariableDeclarationStatement.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1270 of file SolidityAST.cs.
References SolidityAST.ASTNode.Accept(), SolidityAST.VariableDeclarationStatement.Declarations, SolidityAST.IASTVisitor.EndVisit(), SolidityAST.VariableDeclarationStatement.InitialValue, and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.VariableDeclarationStatement.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1284 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.VariableDeclarationStatement.ToString () inline
Definition at line 1289 of file SolidityAST.cs.
References SolidityAST.VariableDeclarationStatement.Declarations, and SolidityAST.VariableDeclarationStatement.InitialValue.
Property Documentation
Assignments
List<int> SolidityAST.VariableDeclarationStatement.Assignments get set
Definition at line 1264 of file SolidityAST.cs.
Declarations
List<VariableDeclaration> SolidityAST.VariableDeclarationStatement.Declarations get set
Definition at line 1266 of file SolidityAST.cs.
Referenced by SolidityAST.VariableDeclarationStatement.Accept(), and SolidityAST.VariableDeclarationStatement.ToString().
InitialValue
Expression SolidityAST.VariableDeclarationStatement.InitialValue get set
Definition at line 1268 of file SolidityAST.cs.
Referenced by SolidityAST.VariableDeclarationStatement.Accept(), and SolidityAST.VariableDeclarationStatement.ToString().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs