VeriSol: SolToBoogie.GhostVarAndAxiomGenerator Class Reference
SolToBoogie.GhostVarAndAxiomGenerator Class Reference
Public Member Functions
GhostVarAndAxiomGenerator (TranslatorContext context)
void Generate ()
Private Member Functions
void GenerateFunctions ()
BoogieFunction GenerateZeroRefIntArrayFunction ()
BoogieFunction GenerateZeroIntIntArrayFunction ()
BoogieFunction GenerateZeroRefBoolArrayFunction ()
BoogieFunction GenerateZeroIntBoolArrayFunction ()
BoogieFunction GenerateZeroRefRefArrayFunction ()
BoogieFunction GenerateZeroIntRefArrayFunction ()
BoogieFunction GenerateKeccakFunction ()
BoogieFunction GenerateAbiEncodedFunctionOneArg ()
BoogieFunction GenerateAbiEncodedFunctionTwoArgs ()
BoogieFunction GenerateAbiEncodedFunctionOneArgRef ()
BoogieFunction GenerateAbiEncodedFunctionTwoArgsOneRef ()
BoogieFunction GenerateConstToRefFunction ()
BoogieFunction GenerateRefToInt ()
BoogieFunction GenerateModFunction ()
BoogieFunction GenerateVeriSolSumFunction ()
void GenerateTypes ()
void GenerateConstants ()
void GenerateGlobalVariables ()
void GenerateGlobalImplementations ()
void GenerateStructConstructors ()
void GenerateStructConstructors (ContractDefinition contract, StructDefinition structDefn)
void GenerateBoogieRecord (string typeName, BoogieType btype)
void GenerateGlobalProcedureFresh ()
void GenerateGlobalProcedureAllocMany ()
void GenerateAxioms ()
BoogieAxiom GenerateConstToRefAxiom ()
BoogieAxiom GenerateKeccakAxiom ()
BoogieAxiom GenerateAbiEncodePackedAxiomOneArg ()
BoogieAxiom GenerateAbiEncodePackedAxiomTwoArgs ()
BoogieAxiom GenerateAbiEncodePackedAxiomOneArgRef ()
List< BoogieAxiom > GenerateVeriSolSumAxioms ()
BoogieAxiom GenerateAbiEncodePackedAxiomTwoArgsOneRef ()
void GenerateMemoryVariables ()
void GenerateMemoryVariablesForMapping (Mapping mapping, HashSet< KeyValuePair< BoogieType, BoogieType >> generatedTypes)
void GenerateMemoryVariablesForArray (ArrayTypeName array, HashSet< KeyValuePair< BoogieType, BoogieType >> generatedTypes)
void GenerateSingleMemoryVariable (BoogieType keyType, BoogieType valType)
Private Attributes
TranslatorContext context
BoogieCtorType contractType = new BoogieCtorType("ContractName")
Detailed Description
Definition at line 11 of file GhostVarAndAxiomGenerator.cs.
Constructor & Destructor Documentation
GhostVarAndAxiomGenerator()
SolToBoogie.GhostVarAndAxiomGenerator.GhostVarAndAxiomGenerator (TranslatorContext context) inline
Definition at line 18 of file GhostVarAndAxiomGenerator.cs.
References SolToBoogie.GhostVarAndAxiomGenerator.context.
Member Function Documentation
Generate()
void SolToBoogie.GhostVarAndAxiomGenerator.Generate () inline
Definition at line 23 of file GhostVarAndAxiomGenerator.cs.
References SolToBoogie.GhostVarAndAxiomGenerator.GenerateAxioms(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateConstants(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalImplementations(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalVariables(), and SolToBoogie.GhostVarAndAxiomGenerator.GenerateTypes().
Referenced by SolToBoogie.BoogieTranslator.Translate().
GenerateAbiEncodedFunctionOneArg()
BoogieFunction SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodedFunctionOneArg () inline private
Definition at line 133 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions().
GenerateAbiEncodedFunctionOneArgRef()
BoogieFunction SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodedFunctionOneArgRef () inline private
Definition at line 157 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions().
GenerateAbiEncodedFunctionTwoArgs()
BoogieFunction SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodedFunctionTwoArgs () inline private
Definition at line 144 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions().
GenerateAbiEncodedFunctionTwoArgsOneRef()
BoogieFunction SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodedFunctionTwoArgsOneRef () inline private
Definition at line 168 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions().
GenerateAbiEncodePackedAxiomOneArg()
BoogieAxiom SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodePackedAxiomOneArg () inline private
Definition at line 531 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int, and SolToBoogie.QVarGenerator.NewQVar().
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateAxioms().
GenerateAbiEncodePackedAxiomOneArgRef()
BoogieAxiom SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodePackedAxiomOneArgRef () inline private
Definition at line 572 of file GhostVarAndAxiomGenerator.cs.
References SolToBoogie.QVarGenerator.NewQVar(), and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateAxioms().
GenerateAbiEncodePackedAxiomTwoArgs()
BoogieAxiom SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodePackedAxiomTwoArgs () inline private
Definition at line 548 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int, and SolToBoogie.QVarGenerator.NewQVar().
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateAxioms().
GenerateAbiEncodePackedAxiomTwoArgsOneRef()
BoogieAxiom SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodePackedAxiomTwoArgsOneRef () inline private
Definition at line 629 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int, SolToBoogie.QVarGenerator.NewQVar(), and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateAxioms().
GenerateAxioms()
void SolToBoogie.GhostVarAndAxiomGenerator.GenerateAxioms () inline private
Definition at line 479 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), SolToBoogie.GhostVarAndAxiomGenerator.context, SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodePackedAxiomOneArg(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodePackedAxiomOneArgRef(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodePackedAxiomTwoArgs(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodePackedAxiomTwoArgsOneRef(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateConstToRefAxiom(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateKeccakAxiom(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateVeriSolSumAxioms(), SolToBoogie.TranslatorFlags.NoAxiomsFlag, SolToBoogie.TranslatorContext.Program, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.Generate().
GenerateBoogieRecord()
void SolToBoogie.GhostVarAndAxiomGenerator.GenerateBoogieRecord (string typeName, BoogieType btype) inline private
Definition at line 387 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), SolToBoogie.GhostVarAndAxiomGenerator.context, SolToBoogie.TranslatorFlags.NoDataValuesInfoFlag, SolToBoogie.TranslatorContext.Program, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalImplementations().
GenerateConstants()
void SolToBoogie.GhostVarAndAxiomGenerator.GenerateConstants () inline private
Definition at line 248 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), SolToBoogie.GhostVarAndAxiomGenerator.context, SolToBoogie.TranslatorContext.ContractDefinitions, SolidityAST.ContractDefinition.Name, SolidityAST.ContractDefinition.Nodes, SolToBoogie.TranslatorContext.Program, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.Generate().
GenerateConstToRefAxiom()
BoogieAxiom SolToBoogie.GhostVarAndAxiomGenerator.GenerateConstToRefAxiom () inline private
Definition at line 497 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int, and SolToBoogie.QVarGenerator.NewQVar().
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateAxioms().
GenerateConstToRefFunction()
BoogieFunction SolToBoogie.GhostVarAndAxiomGenerator.GenerateConstToRefFunction () inline private
Definition at line 182 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions().
GenerateFunctions()
void SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions () inline private
Definition at line 33 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), SolToBoogie.GhostVarAndAxiomGenerator.context, SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodedFunctionOneArg(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodedFunctionOneArgRef(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodedFunctionTwoArgs(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodedFunctionTwoArgsOneRef(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateConstToRefFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateKeccakFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateModFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateRefToInt(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateVeriSolSumFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroIntBoolArrayFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroIntIntArrayFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroIntRefArrayFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroRefBoolArrayFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroRefIntArrayFunction(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroRefRefArrayFunction(), SolToBoogie.TranslatorContext.Program, SolToBoogie.TranslatorFlags.QuantFreeAllocs, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.Generate().
GenerateGlobalImplementations()
void SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalImplementations () inline private
Definition at line 323 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Bool, SolToBoogie.GhostVarAndAxiomGenerator.GenerateBoogieRecord(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalProcedureAllocMany(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalProcedureFresh(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateStructConstructors(), BoogieAST.BoogieType.Int, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.Generate().
GenerateGlobalProcedureAllocMany()
void SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalProcedureAllocMany () inline private
Definition at line 442 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), BoogieAST.BoogieStmtList.AddStatement(), BoogieAST.BoogieType.Bool, SolToBoogie.GhostVarAndAxiomGenerator.context, SolToBoogie.TranslatorFlags.GenerateInlineAttributes, SolToBoogie.TranslatorFlags.LazyNestedAlloc, SolToBoogie.QVarGenerator.NewQVar(), SolToBoogie.TranslatorContext.Program, BoogieAST.BoogieType.Ref, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalImplementations().
GenerateGlobalProcedureFresh()
void SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalProcedureFresh () inline private
Definition at line 402 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.GhostVarAndAxiomGenerator.context, SolToBoogie.TranslatorFlags.GenerateInlineAttributes, SolToBoogie.TranslatorContext.Program, BoogieAST.BoogieType.Ref, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalImplementations().
GenerateGlobalVariables()
void SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalVariables () inline private
Definition at line 271 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), BoogieAST.BoogieType.Bool, SolToBoogie.GhostVarAndAxiomGenerator.context, SolToBoogie.GhostVarAndAxiomGenerator.contractType, SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariables(), SolToBoogie.TranslatorFlags.InstrumentGas, SolToBoogie.TranslatorFlags.InstrumentSums, BoogieAST.BoogieType.Int, SolToBoogie.TranslatorFlags.ModelReverts, SolToBoogie.TranslatorContext.Program, BoogieAST.BoogieType.Ref, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.Generate().
GenerateKeccakAxiom()
BoogieAxiom SolToBoogie.GhostVarAndAxiomGenerator.GenerateKeccakAxiom () inline private
Definition at line 514 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int, and SolToBoogie.QVarGenerator.NewQVar().
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateAxioms().
GenerateKeccakFunction()
BoogieFunction SolToBoogie.GhostVarAndAxiomGenerator.GenerateKeccakFunction () inline private
Definition at line 122 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions().
GenerateMemoryVariables()
void SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariables () inline private
Definition at line 653 of file GhostVarAndAxiomGenerator.cs.
References SolToBoogie.GhostVarAndAxiomGenerator.context, SolToBoogie.TranslatorContext.ContractToArraysMap, SolToBoogie.TranslatorContext.ContractToMappingsMap, SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForArray(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForMapping(), and SolidityAST.VariableDeclaration.TypeName.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalVariables().
GenerateMemoryVariablesForArray()
void SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForArray (ArrayTypeName array, HashSet< KeyValuePair< BoogieType, BoogieType >> generatedTypes) inline private
Definition at line 705 of file GhostVarAndAxiomGenerator.cs.
References SolidityAST.ArrayTypeName.BaseType, SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForMapping(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateSingleMemoryVariable(), SolToBoogie.TransUtils.GetBoogieTypeFromSolidityTypeName(), BoogieAST.BoogieType.Int, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariables(), and SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForMapping().
GenerateMemoryVariablesForMapping()
void SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForMapping (Mapping mapping, HashSet< KeyValuePair< BoogieType, BoogieType >> generatedTypes) inline private
Definition at line 678 of file GhostVarAndAxiomGenerator.cs.
References SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForArray(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateSingleMemoryVariable(), SolToBoogie.TransUtils.GetBoogieTypeFromSolidityTypeName(), SolidityAST.Mapping.KeyType, BoogieAST.BoogieType.Ref, and SolidityAST.Mapping.ValueType.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariables(), and SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForArray().
GenerateModFunction()
BoogieFunction SolToBoogie.GhostVarAndAxiomGenerator.GenerateModFunction () inline private
Definition at line 206 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions().
GenerateRefToInt()
BoogieFunction SolToBoogie.GhostVarAndAxiomGenerator.GenerateRefToInt () inline private
Definition at line 194 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions().
GenerateSingleMemoryVariable()
void SolToBoogie.GhostVarAndAxiomGenerator.GenerateSingleMemoryVariable (BoogieType keyType, BoogieType valType) inline private
Definition at line 732 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), SolToBoogie.GhostVarAndAxiomGenerator.context, SolToBoogie.MapArrayHelper.GetMemoryMapName(), SolToBoogie.TranslatorContext.Program, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForArray(), and SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForMapping().
GenerateStructConstructors() [1/2]
void SolToBoogie.GhostVarAndAxiomGenerator.GenerateStructConstructors () inline private
Definition at line 333 of file GhostVarAndAxiomGenerator.cs.
References SolToBoogie.GhostVarAndAxiomGenerator.context, SolToBoogie.TranslatorContext.ContractDefinitions, and SolidityAST.ContractDefinition.Nodes.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalImplementations().
GenerateStructConstructors() [2/2]
void SolToBoogie.GhostVarAndAxiomGenerator.GenerateStructConstructors (ContractDefinition contract, StructDefinition structDefn) inline private
Definition at line 347 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), SolidityAST.StructDefinition.CanonicalName, SolToBoogie.GhostVarAndAxiomGenerator.context, SolToBoogie.TranslatorFlags.GenerateInlineAttributes, SolToBoogie.TransUtils.GetBoogieTypeFromSolidityTypeName(), SolToBoogie.TransUtils.GetDefaultInParams(), SolToBoogie.TranslatorContext.Program, and SolToBoogie.TranslatorContext.TranslateFlags.
GenerateTypes()
void SolToBoogie.GhostVarAndAxiomGenerator.GenerateTypes () inline private
Definition at line 233 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), SolToBoogie.GhostVarAndAxiomGenerator.context, BoogieAST.BoogieType.Int, SolToBoogie.TranslatorFlags.NoCustomTypes, SolToBoogie.TranslatorContext.Program, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.Generate().
GenerateVeriSolSumAxioms()
List<BoogieAxiom> SolToBoogie.GhostVarAndAxiomGenerator.GenerateVeriSolSumAxioms () inline private
Definition at line 589 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int, SolToBoogie.QVarGenerator.NewQVar(), and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateAxioms().
GenerateVeriSolSumFunction()
BoogieFunction SolToBoogie.GhostVarAndAxiomGenerator.GenerateVeriSolSumFunction () inline private
Definition at line 220 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions().
GenerateZeroIntBoolArrayFunction()
BoogieFunction SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroIntBoolArrayFunction () inline private
Definition at line 89 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Bool, and BoogieAST.BoogieType.Int.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions().
GenerateZeroIntIntArrayFunction()
BoogieFunction SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroIntIntArrayFunction () inline private
Definition at line 67 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions().
GenerateZeroIntRefArrayFunction()
BoogieFunction SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroIntRefArrayFunction () inline private
Definition at line 111 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions().
GenerateZeroRefBoolArrayFunction()
BoogieFunction SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroRefBoolArrayFunction () inline private
Definition at line 78 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Bool, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions().
GenerateZeroRefIntArrayFunction()
BoogieFunction SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroRefIntArrayFunction () inline private
Definition at line 56 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Int, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions().
GenerateZeroRefRefArrayFunction()
BoogieFunction SolToBoogie.GhostVarAndAxiomGenerator.GenerateZeroRefRefArrayFunction () inline private
Definition at line 100 of file GhostVarAndAxiomGenerator.cs.
References BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions().
Member Data Documentation
context
TranslatorContext SolToBoogie.GhostVarAndAxiomGenerator.context private
Definition at line 14 of file GhostVarAndAxiomGenerator.cs.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateAxioms(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateBoogieRecord(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateConstants(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalProcedureAllocMany(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalProcedureFresh(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalVariables(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariables(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateSingleMemoryVariable(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateStructConstructors(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateTypes(), and SolToBoogie.GhostVarAndAxiomGenerator.GhostVarAndAxiomGenerator().
contractType
BoogieCtorType SolToBoogie.GhostVarAndAxiomGenerator.contractType = new BoogieCtorType("ContractName") private
Definition at line 16 of file GhostVarAndAxiomGenerator.cs.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalVariables().
The documentation for this class was generated from the following file:
Sources/SolToBoogie/GhostVarAndAxiomGenerator.cs