VeriSol: SolToBoogie.HarnessGenerator Class Reference
SolToBoogie.HarnessGenerator Class Reference
Public Member Functions
HarnessGenerator (TranslatorContext context, Dictionary< string, List< BoogieExpr >> _contractInvariants)
void Generate ()
Private Member Functions
void GenerateHoudiniVarsForContract (ContractDefinition contract, Dictionary< int, BoogieExpr > houdiniVarMap)
void GenerateModifiers ()
void GenerateBoogieHarnessForContract (ContractDefinition contract, Dictionary< int, BoogieExpr > houdiniVarMap)
BoogieAssumeCmd GenerateDynamicTypeAssumes (ContractDefinition contract)
List< BoogieCmd > GenerateConstructorCall (ContractDefinition contract)
BoogieWhileCmd GenerateWhileLoop (ContractDefinition contract, Dictionary< int, BoogieExpr > houdiniVarMap, List< BoogieVariable > localVars)
BoogieStmtList GenerateHavocBlock (ContractDefinition contract, List< BoogieVariable > localVars)
string GetHoudiniVarName (int id, ContractDefinition contract)
void GenerateCorralChoiceProcForContract (ContractDefinition contract)
void GenerateCorralHarnessForContract (ContractDefinition contract)
BoogieWhileCmd GenerateCorralWhileLoop (ContractDefinition contract)
List< BoogieVariable > RemoveThisFromVariables (List< BoogieVariable > variables)
List< BoogieVariable > GetParamsOfFunction (FunctionDefinition funcDef)
Private Attributes
TranslatorContext context
Dictionary< string, List< BoogieExpr > > contractInvariants
Detailed Description
Generate harness for each contract
Definition at line 13 of file HarnessGenerator.cs.
Constructor & Destructor Documentation
HarnessGenerator()
SolToBoogie.HarnessGenerator.HarnessGenerator (TranslatorContext context, Dictionary< string, List< BoogieExpr >> _contractInvariants) inline
Definition at line 18 of file HarnessGenerator.cs.
References SolToBoogie.HarnessGenerator.context.
Member Function Documentation
Generate()
void SolToBoogie.HarnessGenerator.Generate () inline
Definition at line 24 of file HarnessGenerator.cs.
References SolToBoogie.HarnessGenerator.context, SolToBoogie.TranslatorContext.ContractDefinitions, SolidityAST.ContractDefinition.ContractKind, SolToBoogie.HarnessGenerator.GenerateBoogieHarnessForContract(), SolToBoogie.HarnessGenerator.GenerateCorralChoiceProcForContract(), SolToBoogie.HarnessGenerator.GenerateCorralHarnessForContract(), SolToBoogie.HoudiniHelper.GenerateHoudiniVarMapping(), SolToBoogie.HarnessGenerator.GenerateHoudiniVarsForContract(), SolToBoogie.HarnessGenerator.GenerateModifiers(), SolidityAST.ContractDefinition.Name, SolToBoogie.TranslatorFlags.NoBoogieHarness, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.BoogieTranslator.Translate().
GenerateBoogieHarnessForContract()
void SolToBoogie.HarnessGenerator.GenerateBoogieHarnessForContract (ContractDefinition contract, Dictionary< int, BoogieExpr > houdiniVarMap) inline private
Definition at line 93 of file HarnessGenerator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.TransUtils.CollectLocalVars(), SolToBoogie.HarnessGenerator.context, SolToBoogie.HarnessGenerator.GenerateConstructorCall(), SolToBoogie.HarnessGenerator.GenerateDynamicTypeAssumes(), SolToBoogie.HarnessGenerator.GenerateWhileLoop(), SolToBoogie.TranslatorFlags.InstrumentGas, BoogieAST.BoogieType.Int, SolToBoogie.TranslatorFlags.ModelReverts, SolidityAST.ContractDefinition.Name, SolToBoogie.TranslatorContext.Program, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.HarnessGenerator.Generate().
GenerateConstructorCall()
List<BoogieCmd> SolToBoogie.HarnessGenerator.GenerateConstructorCall (ContractDefinition contract) inline private
Definition at line 148 of file HarnessGenerator.cs.
References SolToBoogie.HarnessGenerator.context, SolToBoogie.TranslatorContext.CREATE_GAS_COST, SolToBoogie.TransUtils.GetCanonicalConstructorName(), SolToBoogie.TransUtils.GetCanonicalLocalVariableName(), SolToBoogie.TranslatorContext.GetConstructorByContract(), SolToBoogie.TranslatorFlags.InstrumentGas, SolToBoogie.TranslatorContext.IsConstructorDefined(), SolToBoogie.TranslatorContext.TranslateFlags, and SolidityAST.VariableDeclaration.TypeName.
Referenced by SolToBoogie.HarnessGenerator.GenerateBoogieHarnessForContract(), and SolToBoogie.HarnessGenerator.GenerateCorralHarnessForContract().
GenerateCorralChoiceProcForContract()
void SolToBoogie.HarnessGenerator.GenerateCorralChoiceProcForContract (ContractDefinition contract) inline private
Definition at line 255 of file HarnessGenerator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.TransUtils.CollectLocalVars(), SolToBoogie.HarnessGenerator.context, SolToBoogie.TransUtils.GenerateChoiceBlock(), SolToBoogie.HarnessGenerator.GenerateHavocBlock(), BoogieAST.BoogieType.Int, SolidityAST.ContractDefinition.Name, SolToBoogie.TranslatorContext.Program, BoogieAST.BoogieType.Ref, and SolToBoogie.HarnessGenerator.RemoveThisFromVariables().
Referenced by SolToBoogie.HarnessGenerator.Generate().
GenerateCorralHarnessForContract()
void SolToBoogie.HarnessGenerator.GenerateCorralHarnessForContract (ContractDefinition contract) inline private
Definition at line 274 of file HarnessGenerator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.HarnessGenerator.context, SolToBoogie.TranslatorFlags.CreateMainHarness, SolToBoogie.TranslatorContext.EntryPointContract, SolToBoogie.HarnessGenerator.GenerateConstructorCall(), SolToBoogie.HarnessGenerator.GenerateCorralWhileLoop(), SolToBoogie.HarnessGenerator.GenerateDynamicTypeAssumes(), SolToBoogie.TranslatorContext.GetConstructorByContract(), SolToBoogie.HarnessGenerator.GetParamsOfFunction(), SolToBoogie.TranslatorFlags.InstrumentGas, BoogieAST.BoogieType.Int, SolToBoogie.TranslatorContext.IsConstructorDefined(), SolToBoogie.TranslatorFlags.ModelReverts, SolidityAST.ContractDefinition.Name, SolToBoogie.TranslatorFlags.NoCustomTypes, SolToBoogie.TranslatorContext.Program, BoogieAST.BoogieType.Ref, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.HarnessGenerator.Generate().
GenerateCorralWhileLoop()
BoogieWhileCmd SolToBoogie.HarnessGenerator.GenerateCorralWhileLoop (ContractDefinition contract) inline private
Definition at line 323 of file HarnessGenerator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.HarnessGenerator.contractInvariants, and SolidityAST.ContractDefinition.Name.
Referenced by SolToBoogie.HarnessGenerator.GenerateCorralHarnessForContract().
GenerateDynamicTypeAssumes()
BoogieAssumeCmd SolToBoogie.HarnessGenerator.GenerateDynamicTypeAssumes (ContractDefinition contract) inline private
Definition at line 122 of file HarnessGenerator.cs.
References SolToBoogie.HarnessGenerator.context, SolToBoogie.TranslatorContext.GetSubTypesOfContract(), SolToBoogie.TranslatorFlags.OmitAssumeFalseForDynDispatch, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.HarnessGenerator.GenerateBoogieHarnessForContract(), and SolToBoogie.HarnessGenerator.GenerateCorralHarnessForContract().
GenerateHavocBlock()
BoogieStmtList SolToBoogie.HarnessGenerator.GenerateHavocBlock (ContractDefinition contract, List< BoogieVariable > localVars) inline private
Definition at line 213 of file HarnessGenerator.cs.
References SolToBoogie.HarnessGenerator.context, SolToBoogie.TranslatorContext.ContractDefinitions, SolToBoogie.TransUtils.havocGas(), SolToBoogie.TranslatorFlags.InstrumentGas, BoogieAST.BoogieTypedIdent.Name, SolToBoogie.TranslatorContext.TranslateFlags, and BoogieAST.BoogieVariable.TypedIdent.
Referenced by SolToBoogie.HarnessGenerator.GenerateCorralChoiceProcForContract(), and SolToBoogie.HarnessGenerator.GenerateWhileLoop().
GenerateHoudiniVarsForContract()
void SolToBoogie.HarnessGenerator.GenerateHoudiniVarsForContract (ContractDefinition contract, Dictionary< int, BoogieExpr > houdiniVarMap) inline private
Definition at line 58 of file HarnessGenerator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), BoogieAST.BoogieDeclaration.Attributes, BoogieAST.BoogieType.Bool, SolToBoogie.HarnessGenerator.context, SolToBoogie.HarnessGenerator.GetHoudiniVarName(), and SolToBoogie.TranslatorContext.Program.
Referenced by SolToBoogie.HarnessGenerator.Generate().
GenerateModifiers()
void SolToBoogie.HarnessGenerator.GenerateModifiers () inline private
Definition at line 72 of file HarnessGenerator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), SolToBoogie.HarnessGenerator.context, SolToBoogie.TranslatorContext.ModifierToBoogiePostImpl, SolToBoogie.TranslatorContext.ModifierToBoogiePostProc, SolToBoogie.TranslatorContext.ModifierToBoogiePreImpl, SolToBoogie.TranslatorContext.ModifierToBoogiePreProc, and SolToBoogie.TranslatorContext.Program.
Referenced by SolToBoogie.HarnessGenerator.Generate().
GenerateWhileLoop()
BoogieWhileCmd SolToBoogie.HarnessGenerator.GenerateWhileLoop (ContractDefinition contract, Dictionary< int, BoogieExpr > houdiniVarMap, List< BoogieVariable > localVars) inline private
Definition at line 185 of file HarnessGenerator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), SolToBoogie.HarnessGenerator.context, SolToBoogie.HarnessGenerator.contractInvariants, SolToBoogie.TransUtils.GenerateChoiceBlock(), SolToBoogie.HarnessGenerator.GenerateHavocBlock(), SolToBoogie.HarnessGenerator.GetHoudiniVarName(), and SolidityAST.ContractDefinition.Name.
Referenced by SolToBoogie.HarnessGenerator.GenerateBoogieHarnessForContract().
GetHoudiniVarName()
string SolToBoogie.HarnessGenerator.GetHoudiniVarName (int id, ContractDefinition contract) inline private
Definition at line 250 of file HarnessGenerator.cs.
References SolidityAST.ContractDefinition.Name.
Referenced by SolToBoogie.HarnessGenerator.GenerateHoudiniVarsForContract(), and SolToBoogie.HarnessGenerator.GenerateWhileLoop().
GetParamsOfFunction()
List<BoogieVariable> SolToBoogie.HarnessGenerator.GetParamsOfFunction (FunctionDefinition funcDef) inline private
Definition at line 356 of file HarnessGenerator.cs.
References SolToBoogie.HarnessGenerator.context, SolToBoogie.TransUtils.GetBoogieTypeFromSolidityTypeName(), SolToBoogie.TransUtils.GetCanonicalLocalVariableName(), SolidityAST.VariableDeclaration.Name, and SolidityAST.VariableDeclaration.TypeName.
Referenced by SolToBoogie.HarnessGenerator.GenerateCorralHarnessForContract().
RemoveThisFromVariables()
List<BoogieVariable> SolToBoogie.HarnessGenerator.RemoveThisFromVariables (List< BoogieVariable > variables) inline private
Definition at line 343 of file HarnessGenerator.cs.
References BoogieAST.BoogieTypedIdent.Name, and BoogieAST.BoogieVariable.TypedIdent.
Referenced by SolToBoogie.HarnessGenerator.GenerateCorralChoiceProcForContract().
Member Data Documentation
context
TranslatorContext SolToBoogie.HarnessGenerator.context private
Definition at line 15 of file HarnessGenerator.cs.
Referenced by SolToBoogie.HarnessGenerator.Generate(), SolToBoogie.HarnessGenerator.GenerateBoogieHarnessForContract(), SolToBoogie.HarnessGenerator.GenerateConstructorCall(), SolToBoogie.HarnessGenerator.GenerateCorralChoiceProcForContract(), SolToBoogie.HarnessGenerator.GenerateCorralHarnessForContract(), SolToBoogie.HarnessGenerator.GenerateDynamicTypeAssumes(), SolToBoogie.HarnessGenerator.GenerateHavocBlock(), SolToBoogie.HarnessGenerator.GenerateHoudiniVarsForContract(), SolToBoogie.HarnessGenerator.GenerateModifiers(), SolToBoogie.HarnessGenerator.GenerateWhileLoop(), SolToBoogie.HarnessGenerator.GetParamsOfFunction(), and SolToBoogie.HarnessGenerator.HarnessGenerator().
contractInvariants
Dictionary<string, List<BoogieExpr> > SolToBoogie.HarnessGenerator.contractInvariants private
Definition at line 16 of file HarnessGenerator.cs.
Referenced by SolToBoogie.HarnessGenerator.GenerateCorralWhileLoop(), and SolToBoogie.HarnessGenerator.GenerateWhileLoop().
The documentation for this class was generated from the following file:
Sources/SolToBoogie/HarnessGenerator.cs