VeriSol: SolToBoogie.StateVariableResolver Class Reference
SolToBoogie.StateVariableResolver Class Reference
Public Member Functions
StateVariableResolver (TranslatorContext context)
void Resolve ()
Private Member Functions
void ResolveStateVariables ()
void ComputeVisibleStateVariables ()
void PrintStateVarResolutionMap ()
void PrintVisibleStateVars ()
Private Attributes
TranslatorContext context
Detailed Description
Determine the visible state variables for each contract considering the inheritance hierarchy, and put the information in the context.
Definition at line 14 of file StateVariableResolver.cs.
Constructor & Destructor Documentation
StateVariableResolver()
SolToBoogie.StateVariableResolver.StateVariableResolver (TranslatorContext context) inline
Definition at line 18 of file StateVariableResolver.cs.
References SolToBoogie.StateVariableResolver.context.
Member Function Documentation
ComputeVisibleStateVariables()
void SolToBoogie.StateVariableResolver.ComputeVisibleStateVariables () inline private
Definition at line 71 of file StateVariableResolver.cs.
References SolToBoogie.TranslatorContext.AddVisibleStateVarToContract(), SolToBoogie.StateVariableResolver.context, and SolToBoogie.TranslatorContext.StateVarNameResolutionMap.
Referenced by SolToBoogie.StateVariableResolver.Resolve().
PrintStateVarResolutionMap()
void SolToBoogie.StateVariableResolver.PrintStateVarResolutionMap () inline private
Definition at line 85 of file StateVariableResolver.cs.
References SolToBoogie.StateVariableResolver.context, SolToBoogie.TranslatorContext.GetContractByStateVarDecl(), SolToBoogie.TranslatorContext.GetStateVarByDynamicType(), SolidityAST.ContractDefinition.Name, SolidityAST.VariableDeclaration.Name, and SolToBoogie.TranslatorContext.StateVarNameResolutionMap.
PrintVisibleStateVars()
void SolToBoogie.StateVariableResolver.PrintVisibleStateVars () inline private
Definition at line 100 of file StateVariableResolver.cs.
References SolToBoogie.StateVariableResolver.context, SolToBoogie.TranslatorContext.ContractToVisibleStateVarsMap, and SolidityAST.ContractDefinition.Name.
Resolve()
void SolToBoogie.StateVariableResolver.Resolve () inline
Definition at line 23 of file StateVariableResolver.cs.
References SolToBoogie.StateVariableResolver.ComputeVisibleStateVariables(), and SolToBoogie.StateVariableResolver.ResolveStateVariables().
Referenced by SolToBoogie.BoogieTranslator.Translate().
ResolveStateVariables()
void SolToBoogie.StateVariableResolver.ResolveStateVariables () inline private
Definition at line 29 of file StateVariableResolver.cs.
References SolToBoogie.TranslatorContext.AddStateVarToDynamicType(), SolToBoogie.StateVariableResolver.context, SolToBoogie.TranslatorContext.ContractDefinitions, SolToBoogie.TranslatorContext.GetASTNodeById(), SolToBoogie.TranslatorContext.GetStateVarsByContract(), SolidityAST.ContractDefinition.LinearizedBaseContracts, SolidityAST.VariableDeclaration.Name, SolToBoogie.ResolutionHelper.TopologicalSortByDependency(), and SolidityAST.VariableDeclaration.Visibility.
Referenced by SolToBoogie.StateVariableResolver.Resolve().
Member Data Documentation
context
TranslatorContext SolToBoogie.StateVariableResolver.context private
Definition at line 16 of file StateVariableResolver.cs.
Referenced by SolToBoogie.StateVariableResolver.ComputeVisibleStateVariables(), SolToBoogie.StateVariableResolver.PrintStateVarResolutionMap(), SolToBoogie.StateVariableResolver.PrintVisibleStateVars(), SolToBoogie.StateVariableResolver.ResolveStateVariables(), and SolToBoogie.StateVariableResolver.StateVariableResolver().
The documentation for this class was generated from the following file:
Sources/SolToBoogie/StateVariableResolver.cs