VeriSol: SolToBoogie.FunctionEventResolver Class Reference
SolToBoogie.FunctionEventResolver Class Reference
Public Member Functions
FunctionEventResolver (TranslatorContext context)
void Resolve ()
Private Member Functions
void ResolveFunctions ()
void ComputeVisibleFunctions ()
void PrintFunctionResolutionMap ()
void PrintVisibleFunctions ()
Private Attributes
TranslatorContext context
Detailed Description
Determine the visible functions/events for each contract considering the inheritance hierarchy, and put the information in the context.
Definition at line 14 of file FunctionEventResolver.cs.
Constructor & Destructor Documentation
FunctionEventResolver()
SolToBoogie.FunctionEventResolver.FunctionEventResolver (TranslatorContext context) inline
Definition at line 20 of file FunctionEventResolver.cs.
References SolToBoogie.FunctionEventResolver.context.
Member Function Documentation
ComputeVisibleFunctions()
void SolToBoogie.FunctionEventResolver.ComputeVisibleFunctions () inline private
Definition at line 81 of file FunctionEventResolver.cs.
References SolToBoogie.TranslatorContext.AddVisibleFunctionToContract(), SolToBoogie.FunctionEventResolver.context, and SolToBoogie.TranslatorContext.FuncSigResolutionMap.
Referenced by SolToBoogie.FunctionEventResolver.Resolve().
PrintFunctionResolutionMap()
void SolToBoogie.FunctionEventResolver.PrintFunctionResolutionMap () inline private
Definition at line 95 of file FunctionEventResolver.cs.
References SolToBoogie.FunctionEventResolver.context, SolToBoogie.TranslatorContext.FuncSigResolutionMap, SolToBoogie.TranslatorContext.GetContractByFunction(), SolToBoogie.TranslatorContext.GetFunctionByDynamicType(), and SolidityAST.ContractDefinition.Name.
PrintVisibleFunctions()
void SolToBoogie.FunctionEventResolver.PrintVisibleFunctions () inline private
Definition at line 110 of file FunctionEventResolver.cs.
References SolToBoogie.FunctionEventResolver.context, SolToBoogie.TranslatorContext.ContractToVisibleFunctionsMap, SolToBoogie.TransUtils.GetCanonicalFunctionName(), and SolidityAST.ContractDefinition.Name.
Resolve()
void SolToBoogie.FunctionEventResolver.Resolve () inline
Definition at line 26 of file FunctionEventResolver.cs.
References SolToBoogie.FunctionEventResolver.ComputeVisibleFunctions(), and SolToBoogie.FunctionEventResolver.ResolveFunctions().
Referenced by SolToBoogie.BoogieTranslator.Translate().
ResolveFunctions()
void SolToBoogie.FunctionEventResolver.ResolveFunctions () inline private
Definition at line 32 of file FunctionEventResolver.cs.
References SolToBoogie.TranslatorContext.AddEventToContract(), SolToBoogie.TranslatorContext.AddFunctionToDynamicType(), SolToBoogie.TransUtils.ComputeFunctionSignature(), SolToBoogie.FunctionEventResolver.context, SolToBoogie.TranslatorContext.ContractDefinitions, SolToBoogie.TranslatorContext.GetASTNodeById(), SolToBoogie.TranslatorContext.GetEventDefintionsInContract(), SolToBoogie.TranslatorContext.GetFuncDefintionsInContract(), SolidityAST.ContractDefinition.LinearizedBaseContracts, and SolToBoogie.ResolutionHelper.TopologicalSortByDependency().
Referenced by SolToBoogie.FunctionEventResolver.Resolve().
Member Data Documentation
context
TranslatorContext SolToBoogie.FunctionEventResolver.context private
Definition at line 18 of file FunctionEventResolver.cs.
Referenced by SolToBoogie.FunctionEventResolver.ComputeVisibleFunctions(), SolToBoogie.FunctionEventResolver.FunctionEventResolver(), SolToBoogie.FunctionEventResolver.PrintFunctionResolutionMap(), SolToBoogie.FunctionEventResolver.PrintVisibleFunctions(), and SolToBoogie.FunctionEventResolver.ResolveFunctions().
The documentation for this class was generated from the following file:
Sources/SolToBoogie/FunctionEventResolver.cs