VeriSol: SolidityAST.BasicASTVisitor Class Reference
SolidityAST.BasicASTVisitor Class Reference
Public Member Functions
virtual bool Visit (SourceUnitList node)
virtual bool Visit (SourceUnit node)
virtual bool Visit (PragmaDirective node)
virtual bool Visit (UsingForDirective node)
virtual bool Visit (ImportDirective node)
virtual bool Visit (ContractDefinition node)
virtual bool Visit (InheritanceSpecifier node)
virtual bool Visit (FunctionDefinition node)
virtual bool Visit (ParameterList node)
virtual bool Visit (ModifierDefinition node)
virtual bool Visit (ModifierInvocation node)
virtual bool Visit (EventDefinition node)
virtual bool Visit (StructDefinition node)
virtual bool Visit (EnumDefinition node)
virtual bool Visit (EnumValue node)
virtual bool Visit (VariableDeclaration node)
virtual bool Visit (ElementaryTypeName node)
virtual bool Visit (UserDefinedTypeName node)
virtual bool Visit (Mapping node)
virtual bool Visit (ArrayTypeName node)
virtual bool Visit (Block node)
virtual bool Visit (PlaceholderStatement node)
virtual bool Visit (IfStatement node)
virtual bool Visit (WhileStatement node)
virtual bool Visit (DoWhileStatement node)
virtual bool Visit (ForStatement node)
virtual bool Visit (Continue node)
virtual bool Visit (Break node)
virtual bool Visit (Return node)
virtual bool Visit (Throw node)
virtual bool Visit (EmitStatement node)
virtual bool Visit (VariableDeclarationStatement node)
virtual bool Visit (InlineAssembly node)
virtual bool Visit (ExpressionStatement node)
virtual bool Visit (Literal node)
virtual bool Visit (Identifier node)
virtual bool Visit (ElementaryTypeNameExpression node)
virtual bool Visit (UnaryOperation node)
virtual bool Visit (BinaryOperation node)
virtual bool Visit (Conditional node)
virtual bool Visit (Assignment node)
virtual bool Visit (TupleExpression node)
virtual bool Visit (FunctionCall node)
virtual bool Visit (NewExpression node)
virtual bool Visit (MemberAccess node)
virtual bool Visit (IndexAccess node)
virtual void EndVisit (SourceUnitList node)
virtual void EndVisit (SourceUnit node)
virtual void EndVisit (PragmaDirective node)
virtual void EndVisit (UsingForDirective node)
virtual void EndVisit (ImportDirective node)
virtual void EndVisit (ContractDefinition node)
virtual void EndVisit (InheritanceSpecifier node)
virtual void EndVisit (FunctionDefinition node)
virtual void EndVisit (ParameterList node)
virtual void EndVisit (ModifierDefinition node)
virtual void EndVisit (ModifierInvocation node)
virtual void EndVisit (EventDefinition node)
virtual void EndVisit (StructDefinition node)
virtual void EndVisit (EnumDefinition node)
virtual void EndVisit (EnumValue node)
virtual void EndVisit (VariableDeclaration node)
virtual void EndVisit (ElementaryTypeName node)
virtual void EndVisit (UserDefinedTypeName node)
virtual void EndVisit (Mapping node)
virtual void EndVisit (ArrayTypeName node)
virtual void EndVisit (Block node)
virtual void EndVisit (PlaceholderStatement node)
virtual void EndVisit (IfStatement node)
virtual void EndVisit (WhileStatement node)
virtual void EndVisit (DoWhileStatement node)
virtual void EndVisit (ForStatement node)
virtual void EndVisit (Continue node)
virtual void EndVisit (Break node)
virtual void EndVisit (Return node)
virtual void EndVisit (Throw node)
virtual void EndVisit (EmitStatement node)
virtual void EndVisit (VariableDeclarationStatement node)
virtual void EndVisit (InlineAssembly node)
virtual void EndVisit (ExpressionStatement node)
virtual void EndVisit (Literal node)
virtual void EndVisit (Identifier node)
virtual void EndVisit (ElementaryTypeNameExpression node)
virtual void EndVisit (UnaryOperation node)
virtual void EndVisit (BinaryOperation node)
virtual void EndVisit (Conditional node)
virtual void EndVisit (Assignment node)
virtual void EndVisit (TupleExpression node)
virtual void EndVisit (FunctionCall node)
virtual void EndVisit (NewExpression node)
virtual void EndVisit (MemberAccess node)
virtual void EndVisit (IndexAccess node)
Protected Member Functions
virtual bool CommonVisit (ASTNode node)
virtual void CommonEndVisit (ASTNode node)
Detailed Description
Definition at line 5 of file BasicASTVisitor.cs.
Member Function Documentation
CommonEndVisit()
virtual void SolidityAST.BasicASTVisitor.CommonEndVisit (ASTNode node) inline protected virtual
Reimplemented in SolToBoogie.SourceInfoCollector.
Definition at line 12 of file BasicASTVisitor.cs.
Referenced by SolidityAST.BasicASTVisitor.EndVisit().
CommonVisit()
virtual bool SolidityAST.BasicASTVisitor.CommonVisit (ASTNode node) inline protected virtual
Reimplemented in SolidityAST.NodeMapper, and SolidityCFG.CFGBuilder.
Definition at line 7 of file BasicASTVisitor.cs.
Referenced by SolidityAST.BasicASTVisitor.Visit().
EndVisit() [1/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (ArrayTypeName node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 148 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [2/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (Assignment node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 190 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [3/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (BinaryOperation node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 186 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [4/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (Block node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 150 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [5/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (Break node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring.
Definition at line 164 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [6/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (Conditional node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 188 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [7/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (Continue node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring.
Definition at line 162 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [8/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (ContractDefinition node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.UsingCollector, SolToBoogie.SolidityDesugaring, SolToBoogie.MapArrayCollector, and SolToBoogie.FunctionEventCollector.
Definition at line 120 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [9/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (DoWhileStatement node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring.
Definition at line 158 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [10/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (ElementaryTypeName node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 142 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [11/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (ElementaryTypeNameExpression node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 182 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [12/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (EmitStatement node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring.
Definition at line 170 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [13/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (EnumDefinition node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 136 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [14/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (EnumValue node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 138 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [15/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (EventDefinition node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 132 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [16/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (ExpressionStatement node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring.
Definition at line 176 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [17/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (ForStatement node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring.
Definition at line 160 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [18/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (FunctionCall node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring.
Definition at line 194 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [19/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (FunctionDefinition node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 124 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [20/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (Identifier node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 180 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [21/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (IfStatement node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring.
Definition at line 154 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [22/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (ImportDirective node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 118 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [23/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (IndexAccess node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 200 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [24/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (InheritanceSpecifier node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 122 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [25/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (InlineAssembly node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring.
Definition at line 174 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [26/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (Literal node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 178 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [27/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (Mapping node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 146 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [28/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (MemberAccess node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 198 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [29/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (ModifierDefinition node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 128 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [30/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (ModifierInvocation node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 130 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [31/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (NewExpression node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 196 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [32/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (ParameterList node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 126 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [33/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (PlaceholderStatement node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring.
Definition at line 152 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [34/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (PragmaDirective node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 114 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [35/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (Return node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring.
Definition at line 166 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [36/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (SourceUnit node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 112 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [37/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (SourceUnitList node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 110 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [38/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (StructDefinition node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 134 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [39/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (Throw node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring.
Definition at line 168 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [40/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (TupleExpression node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 192 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [41/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (UnaryOperation node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 184 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [42/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (UserDefinedTypeName node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 144 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [43/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (UsingForDirective node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 116 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [44/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (VariableDeclaration node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 140 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [45/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (VariableDeclarationStatement node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring.
Definition at line 172 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
EndVisit() [46/46]
virtual void SolidityAST.BasicASTVisitor.EndVisit (WhileStatement node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring.
Definition at line 156 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonEndVisit().
Visit() [1/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (ArrayTypeName node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 55 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [2/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (Assignment node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.ProcedureTranslator.
Definition at line 97 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [3/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (BinaryOperation node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.ProcedureTranslator, and SolidityCFG.CFGBuilder.
Definition at line 93 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [4/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (Block node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.ProcedureTranslator.
Definition at line 57 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [5/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (Break node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring, and SolToBoogie.ProcedureTranslator.
Definition at line 71 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [6/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (Conditional node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.ProcedureTranslator, and SolidityCFG.CFGBuilder.
Definition at line 95 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [7/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (Continue node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring, and SolToBoogie.ProcedureTranslator.
Definition at line 69 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [8/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (ContractDefinition node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.UsingCollector, SolToBoogie.StateVariableCollector, SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, SolToBoogie.MapArrayCollector, SolToBoogie.FunctionEventCollector, SolToBoogie.ContractCollector, and SolToBoogie.ConstructorCollector.
Definition at line 27 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [9/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (DoWhileStatement node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring, and SolToBoogie.ProcedureTranslator.
Definition at line 65 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [10/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (ElementaryTypeName node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 49 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [11/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (ElementaryTypeNameExpression node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 89 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [12/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (EmitStatement node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring.
Definition at line 77 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [13/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (EnumDefinition node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.ProcedureTranslator.
Definition at line 43 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [14/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (EnumValue node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 45 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [15/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (EventDefinition node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.FunctionEventCollector.
Definition at line 39 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [16/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (ExpressionStatement node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring, and SolToBoogie.ProcedureTranslator.
Definition at line 83 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [17/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (ForStatement node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring, and SolToBoogie.ProcedureTranslator.
Definition at line 67 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [18/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (FunctionCall node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring, and SolToBoogie.ProcedureTranslator.
Definition at line 101 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [19/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (FunctionDefinition node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, and SolToBoogie.FunctionEventCollector.
Definition at line 31 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [20/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (Identifier node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.ProcedureTranslator.
Definition at line 87 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [21/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (IfStatement node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, and SolidityCFG.CFGBuilder.
Definition at line 61 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [22/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (ImportDirective node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 25 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [23/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (IndexAccess node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.ProcedureTranslator.
Definition at line 107 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [24/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (InheritanceSpecifier node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 29 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [25/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (InlineAssembly node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring, and SolToBoogie.ProcedureTranslator.
Definition at line 81 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [26/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (Literal node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.ProcedureTranslator.
Definition at line 85 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [27/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (Mapping node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 53 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [28/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (MemberAccess node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.ProcedureTranslator.
Definition at line 105 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [29/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (ModifierDefinition node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.ProcedureTranslator, and SolToBoogie.ModifierCollector.
Definition at line 35 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [30/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (ModifierInvocation node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 37 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [31/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (NewExpression node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 103 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [32/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (ParameterList node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.ProcedureTranslator.
Definition at line 33 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [33/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (PlaceholderStatement node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring, and SolToBoogie.ProcedureTranslator.
Definition at line 59 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [34/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (PragmaDirective node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 21 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [35/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (Return node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring, and SolToBoogie.ProcedureTranslator.
Definition at line 73 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [36/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (SourceUnit node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SourceInfoCollector.
Definition at line 19 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [37/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (SourceUnitList node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SourceInfoCollector.
Definition at line 17 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [38/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (StructDefinition node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 41 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [39/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (Throw node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring, and SolToBoogie.ProcedureTranslator.
Definition at line 75 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [40/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (TupleExpression node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 99 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [41/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (UnaryOperation node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.ProcedureTranslator.
Definition at line 91 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [42/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (UserDefinedTypeName node) inline virtual
Implements SolidityAST.IASTVisitor.
Definition at line 51 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [43/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (UsingForDirective node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.UsingCollector.
Definition at line 23 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [44/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (VariableDeclaration node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.MapArrayCollector.
Definition at line 47 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [45/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (VariableDeclarationStatement node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring, and SolToBoogie.ProcedureTranslator.
Definition at line 79 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
Visit() [46/46]
virtual bool SolidityAST.BasicASTVisitor.Visit (WhileStatement node) inline virtual
Implements SolidityAST.IASTVisitor.
Reimplemented in SolToBoogie.SolidityDesugaring, and SolToBoogie.ProcedureTranslator.
Definition at line 63 of file BasicASTVisitor.cs.
References SolidityAST.BasicASTVisitor.CommonVisit().
The documentation for this class was generated from the following file:
Sources/SolidityAST/BasicASTVisitor.cs