VeriSol: SolidityAST.UserDefinedTypeName Class Reference
SolidityAST.UserDefinedTypeName Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
string ContractScope [get, set]
string Name [get, set]
int ReferencedDeclaration [get, set]
TypeDescription TypeDescriptions [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 832 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.UserDefinedTypeName.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 843 of file SolidityAST.cs.
References SolidityAST.IASTVisitor.EndVisit(), and SolidityAST.IASTVisitor.Visit().
Referenced by SolidityAST.UsingForDirective.Accept(), and SolidityAST.InheritanceSpecifier.Accept().
Accept< T >()
override T SolidityAST.UserDefinedTypeName.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 849 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.UserDefinedTypeName.ToString () inline
Definition at line 854 of file SolidityAST.cs.
References SolidityAST.UserDefinedTypeName.Name.
Property Documentation
ContractScope
string SolidityAST.UserDefinedTypeName.ContractScope get set
Definition at line 835 of file SolidityAST.cs.
Name
string SolidityAST.UserDefinedTypeName.Name get set
Definition at line 837 of file SolidityAST.cs.
Referenced by SolToBoogie.ProcedureTranslator.GetInheritanceSpecifieWithArgsOfBase(), SolidityAST.UsingForDirective.ToString(), and SolidityAST.UserDefinedTypeName.ToString().
ReferencedDeclaration
int SolidityAST.UserDefinedTypeName.ReferencedDeclaration get set
Definition at line 839 of file SolidityAST.cs.
TypeDescriptions
TypeDescription SolidityAST.UserDefinedTypeName.TypeDescriptions get set
Definition at line 841 of file SolidityAST.cs.
Referenced by SolToBoogie.ProcedureTranslator.GetBoogieTypesFromMapping().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs