VeriSol: SolToBoogie.FallbackGenerator Class Reference
SolToBoogie.FallbackGenerator Class Reference
Public Member Functions
FallbackGenerator (TranslatorContext _context)
void Generate ()
Private Member Functions
BoogieStmtList CreateBodyOfSend (List< BoogieVariable > inParams, List< BoogieVariable > outParams, string fbProcName)
BoogieStmtList CreateBodyOfUnknownFallback (List< BoogieVariable > fbLocalVars, List< BoogieVariable > inParams)
BoogieStmtList GenerateBodyOfFallbackDispatch (List< BoogieVariable > inParams, string fbUnknownProcName)
Private Attributes
TranslatorContext context
Detailed Description
Definition at line 16 of file FallbackGenerator.cs.
Constructor & Destructor Documentation
FallbackGenerator()
SolToBoogie.FallbackGenerator.FallbackGenerator (TranslatorContext _context) inline
Definition at line 20 of file FallbackGenerator.cs.
References SolToBoogie.FallbackGenerator.context.
Member Function Documentation
CreateBodyOfSend()
BoogieStmtList SolToBoogie.FallbackGenerator.CreateBodyOfSend (List< BoogieVariable > inParams, List< BoogieVariable > outParams, string fbProcName) inline private
Definition at line 88 of file FallbackGenerator.cs.
References BoogieAST.BoogieStmtList.MakeSingletonStmtList().
Referenced by SolToBoogie.FallbackGenerator.Generate().
CreateBodyOfUnknownFallback()
BoogieStmtList SolToBoogie.FallbackGenerator.CreateBodyOfUnknownFallback (List< BoogieVariable > fbLocalVars, List< BoogieVariable > inParams) inline private
Definition at line 115 of file FallbackGenerator.cs.
References SolToBoogie.TransUtils.CollectLocalVars(), SolToBoogie.FallbackGenerator.context, SolToBoogie.TranslatorContext.ContractDefinitions, SolToBoogie.TransUtils.GenerateChoiceBlock(), SolToBoogie.TranslatorFlags.ModelStubsAsCallbacks(), SolToBoogie.TranslatorFlags.ModelStubsAsSkips(), and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.FallbackGenerator.Generate().
Generate()
void SolToBoogie.FallbackGenerator.Generate () inline
Definition at line 25 of file FallbackGenerator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), BoogieAST.BoogieStmtList.AddStatement(), BoogieAST.BoogieStmtList.AppendStmtList(), BoogieAST.BoogieType.Bool, SolToBoogie.FallbackGenerator.context, SolToBoogie.FallbackGenerator.CreateBodyOfSend(), SolToBoogie.FallbackGenerator.CreateBodyOfUnknownFallback(), BoogieAST.BoogieProgram.Declarations, SolToBoogie.FallbackGenerator.GenerateBodyOfFallbackDispatch(), SolToBoogie.TranslatorFlags.GenerateInlineAttributes, BoogieAST.BoogieType.Int, SolToBoogie.TranslatorFlags.ModelStubsAsCallbacks(), SolToBoogie.TranslatorFlags.ModelStubsAsHavocs(), SolToBoogie.TranslatorFlags.ModelStubsAsSkips(), SolToBoogie.TranslatorContext.Program, BoogieAST.BoogieType.Ref, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.BoogieTranslator.Translate().
GenerateBodyOfFallbackDispatch()
BoogieStmtList SolToBoogie.FallbackGenerator.GenerateBodyOfFallbackDispatch (List< BoogieVariable > inParams, string fbUnknownProcName) inline private
Definition at line 145 of file FallbackGenerator.cs.
References SolToBoogie.FallbackGenerator.context, SolToBoogie.TranslatorContext.ContractDefinitions, SolToBoogie.TranslatorContext.ContractToFallbackMap, SolToBoogie.TransUtils.GetCanonicalFunctionName(), and BoogieAST.BoogieStmtList.MakeSingletonStmtList().
Referenced by SolToBoogie.FallbackGenerator.Generate().
Member Data Documentation
context
TranslatorContext SolToBoogie.FallbackGenerator.context private
Definition at line 18 of file FallbackGenerator.cs.
Referenced by SolToBoogie.FallbackGenerator.CreateBodyOfUnknownFallback(), SolToBoogie.FallbackGenerator.FallbackGenerator(), SolToBoogie.FallbackGenerator.Generate(), and SolToBoogie.FallbackGenerator.GenerateBodyOfFallbackDispatch().
The documentation for this class was generated from the following file:
Sources/SolToBoogie/FallbackGenerator.cs