VeriSol: SolidityAST.CompilerOutput Class Reference
SolidityAST.CompilerOutput Class Reference
Public Member Functions
bool ContainsError ()
void PrintErrorsToConsole ()
Properties
Dictionary< string, Dictionary< string, object > > Contracts [get, private set]
List< CompilerError > Errors [get, private set]
Dictionary< string, SoliditySourceFile > Sources [get, private set]
Detailed Description
Definition at line 9 of file CompilerOutput.cs.
Member Function Documentation
ContainsError()
bool SolidityAST.CompilerOutput.ContainsError () inline
Definition at line 20 of file CompilerOutput.cs.
References SolidityAST.CompilerOutput.Errors, and SolidityAST.CompilerError.Severity.
Referenced by SolToBoogieTest.RegressionExecutor.Execute(), and VeriSolRunner.VeriSolExecutor.ExecuteSolToBoogie().
PrintErrorsToConsole()
void SolidityAST.CompilerOutput.PrintErrorsToConsole () inline
Definition at line 33 of file CompilerOutput.cs.
References SolidityAST.CompilerOutput.Errors, SolidityAST.CompilerError.FormattedMessage, and SolidityAST.CompilerError.Severity.
Referenced by SolToBoogieTest.RegressionExecutor.Execute(), and VeriSolRunner.VeriSolExecutor.ExecuteSolToBoogie().
Property Documentation
Contracts
Dictionary<string, Dictionary<string, object> > SolidityAST.CompilerOutput.Contracts get private set
Definition at line 12 of file CompilerOutput.cs.
Errors
List<CompilerError> SolidityAST.CompilerOutput.Errors get private set
Definition at line 15 of file CompilerOutput.cs.
Referenced by SolidityAST.CompilerOutput.ContainsError(), and SolidityAST.CompilerOutput.PrintErrorsToConsole().
Sources
Dictionary<string, SoliditySourceFile> SolidityAST.CompilerOutput.Sources get private set
Definition at line 18 of file CompilerOutput.cs.
Referenced by SolidityCFG.TestMain.Main().
The documentation for this class was generated from the following file:
Sources/SolidityAST/CompilerOutput.cs