VeriSol: VeriSolRunner.VeriSolExecutor Class Reference
VeriSolRunner.VeriSolExecutor Class Reference
Public Member Functions
VeriSolExecutor (string solidityFilePath, string contractName, int corralRecursionLimit, HashSet< Tuple< string, string >> ignoreMethods, bool tryRefutation, bool tryProofFlag, ILogger logger, bool _printTransactionSequence, TranslatorFlags _translatorFlags=null)
int Execute ()
Private Member Functions
bool FindProof ()
bool RunCorralForRefutation ()
void DisplayTraceUsingConcurrencyExplorer ()
string[] FilterCorralTrace (string[] trace)
List< Tuple< string, string > > ConvertTrace (string[] corralTrace)
string ConvertFunctionName (string origName)
void PrintCounterexample ()
void PrintCounterexampleHelper (List< Tuple< string, string >> trace)
bool ExecuteSolToBoogie ()
string RunBinary (string cmdName, string arguments)
bool CompareCorralOutput (string expected, string actual)
bool CompareBoogieOutput (string actual)
Private Attributes
string SolidityFilePath
string SolidityFileDir
string ContractName
string CorralPath
string BoogiePath
string SolcPath
bool TryProof
bool TryRefutation
ILogger Logger
readonly string outFileName = "__SolToBoogieTest_out.bpl"
readonly string corralTraceFileName = "corral_out_trace.txt"
readonly string counterexampleFileName = "corral_counterex.txt"
readonly int CorralRecursionLimit
readonly int CorralContextBound = 1
HashSet< Tuple< string, string > > ignoreMethods
TranslatorFlags translatorFlags
bool printTransactionSequence = false
Detailed Description
Definition at line 20 of file VeriSolExecuter.cs.
Constructor & Destructor Documentation
VeriSolExecutor()
VeriSolRunner.VeriSolExecutor.VeriSolExecutor (string solidityFilePath, string contractName, int corralRecursionLimit, HashSet< Tuple< string, string >> ignoreMethods, bool tryRefutation, bool tryProofFlag, ILogger logger, bool _printTransactionSequence, TranslatorFlags _translatorFlags = null) inline
Definition at line 41 of file VeriSolExecuter.cs.
References VeriSolRunner.ExternalTools.ExternalToolsManager.Boogie, VeriSolRunner.ExternalTools.ToolManager.Command, VeriSolRunner.ExternalTools.ExternalToolsManager.Corral, VeriSolRunner.VeriSolExecutor.ignoreMethods, and VeriSolRunner.ExternalTools.ExternalToolsManager.Solc.
Member Function Documentation
CompareBoogieOutput()
bool VeriSolRunner.VeriSolExecutor.CompareBoogieOutput (string actual) inline private
Definition at line 451 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.FindProof().
CompareCorralOutput()
bool VeriSolRunner.VeriSolExecutor.CompareCorralOutput (string expected, string actual) inline private
Definition at line 434 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.RunCorralForRefutation().
ConvertFunctionName()
string VeriSolRunner.VeriSolExecutor.ConvertFunctionName (string origName) inline private
Definition at line 248 of file VeriSolExecuter.cs.
ConvertTrace()
List<Tuple<string, string> > VeriSolRunner.VeriSolExecutor.ConvertTrace (string[] corralTrace) inline private
Definition at line 220 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.PrintCounterexample().
DisplayTraceUsingConcurrencyExplorer()
void VeriSolRunner.VeriSolExecutor.DisplayTraceUsingConcurrencyExplorer () inline private
Definition at line 199 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.RunCorralForRefutation().
Execute()
int VeriSolRunner.VeriSolExecutor.Execute () inline
Definition at line 60 of file VeriSolExecuter.cs.
References VeriSolRunner.VeriSolExecutor.ExecuteSolToBoogie(), VeriSolRunner.VeriSolExecutor.FindProof(), VeriSolRunner.VeriSolExecutor.RunCorralForRefutation(), VeriSolRunner.VeriSolExecutor.TryProof, and VeriSolRunner.VeriSolExecutor.TryRefutation.
ExecuteSolToBoogie()
bool VeriSolRunner.VeriSolExecutor.ExecuteSolToBoogie () inline private
Definition at line 368 of file VeriSolExecuter.cs.
References SolidityAST.SolidityCompiler.Compile(), SolidityAST.CompilerOutput.ContainsError(), VeriSolRunner.VeriSolExecutor.ContractName, BoogieAST.BoogieAST.GetRoot(), VeriSolRunner.VeriSolExecutor.ignoreMethods, VeriSolRunner.VeriSolExecutor.outFileName, SolidityAST.CompilerOutput.PrintErrorsToConsole(), VeriSolRunner.VeriSolExecutor.SolcPath, VeriSolRunner.VeriSolExecutor.SolidityFileDir, VeriSolRunner.VeriSolExecutor.SolidityFilePath, SolToBoogie.BoogieTranslator.Translate(), and VeriSolRunner.VeriSolExecutor.translatorFlags.
Referenced by VeriSolRunner.VeriSolExecutor.Execute().
FilterCorralTrace()
string [] VeriSolRunner.VeriSolExecutor.FilterCorralTrace (string[] trace) inline private
Definition at line 211 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.PrintCounterexample().
FindProof()
bool VeriSolRunner.VeriSolExecutor.FindProof () inline private
Definition at line 98 of file VeriSolExecuter.cs.
References VeriSolRunner.VeriSolExecutor.BoogiePath, VeriSolRunner.VeriSolExecutor.CompareBoogieOutput(), VeriSolRunner.VeriSolExecutor.outFileName, SolToBoogie.TranslatorFlags.PerformContractInferce, VeriSolRunner.VeriSolExecutor.RunBinary(), and VeriSolRunner.VeriSolExecutor.translatorFlags.
Referenced by VeriSolRunner.VeriSolExecutor.Execute().
PrintCounterexample()
void VeriSolRunner.VeriSolExecutor.PrintCounterexample () inline private
Definition at line 277 of file VeriSolExecuter.cs.
References VeriSolRunner.VeriSolExecutor.ConvertTrace(), VeriSolRunner.VeriSolExecutor.FilterCorralTrace(), and VeriSolRunner.VeriSolExecutor.PrintCounterexampleHelper().
Referenced by VeriSolRunner.VeriSolExecutor.RunCorralForRefutation().
PrintCounterexampleHelper()
void VeriSolRunner.VeriSolExecutor.PrintCounterexampleHelper (List< Tuple< string, string >> trace) inline private
Definition at line 287 of file VeriSolExecuter.cs.
References VeriSolRunner.VeriSolExecutor.counterexampleFileName.
Referenced by VeriSolRunner.VeriSolExecutor.PrintCounterexample().
RunBinary()
string VeriSolRunner.VeriSolExecutor.RunBinary (string cmdName, string arguments) inline private
Definition at line 407 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.FindProof(), and VeriSolRunner.VeriSolExecutor.RunCorralForRefutation().
RunCorralForRefutation()
bool VeriSolRunner.VeriSolExecutor.RunCorralForRefutation () inline private
Definition at line 138 of file VeriSolExecuter.cs.
References VeriSolRunner.VeriSolExecutor.CompareCorralOutput(), VeriSolRunner.VeriSolExecutor.CorralPath, VeriSolRunner.VeriSolExecutor.DisplayTraceUsingConcurrencyExplorer(), VeriSolRunner.VeriSolExecutor.outFileName, VeriSolRunner.VeriSolExecutor.PrintCounterexample(), VeriSolRunner.VeriSolExecutor.printTransactionSequence, and VeriSolRunner.VeriSolExecutor.RunBinary().
Referenced by VeriSolRunner.VeriSolExecutor.Execute().
Member Data Documentation
BoogiePath
string VeriSolRunner.VeriSolExecutor.BoogiePath private
Definition at line 26 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.FindProof().
ContractName
string VeriSolRunner.VeriSolExecutor.ContractName private
Definition at line 24 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.ExecuteSolToBoogie().
CorralContextBound
readonly int VeriSolRunner.VeriSolExecutor.CorralContextBound = 1 private
Definition at line 36 of file VeriSolExecuter.cs.
CorralPath
string VeriSolRunner.VeriSolExecutor.CorralPath private
Definition at line 25 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.RunCorralForRefutation().
CorralRecursionLimit
readonly int VeriSolRunner.VeriSolExecutor.CorralRecursionLimit private
Definition at line 35 of file VeriSolExecuter.cs.
corralTraceFileName
readonly string VeriSolRunner.VeriSolExecutor.corralTraceFileName = "corral_out_trace.txt" private
Definition at line 33 of file VeriSolExecuter.cs.
counterexampleFileName
readonly string VeriSolRunner.VeriSolExecutor.counterexampleFileName = "corral_counterex.txt" private
Definition at line 34 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.PrintCounterexampleHelper().
ignoreMethods
HashSet<Tuple<string, string> > VeriSolRunner.VeriSolExecutor.ignoreMethods private
Definition at line 37 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.ExecuteSolToBoogie(), and VeriSolRunner.VeriSolExecutor.VeriSolExecutor().
Logger
ILogger VeriSolRunner.VeriSolExecutor.Logger private
Definition at line 31 of file VeriSolExecuter.cs.
outFileName
readonly string VeriSolRunner.VeriSolExecutor.outFileName = "__SolToBoogieTest_out.bpl" private
Definition at line 32 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.ExecuteSolToBoogie(), VeriSolRunner.VeriSolExecutor.FindProof(), and VeriSolRunner.VeriSolExecutor.RunCorralForRefutation().
printTransactionSequence
bool VeriSolRunner.VeriSolExecutor.printTransactionSequence = false private
Definition at line 39 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.RunCorralForRefutation().
SolcPath
string VeriSolRunner.VeriSolExecutor.SolcPath private
Definition at line 27 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.ExecuteSolToBoogie().
SolidityFileDir
string VeriSolRunner.VeriSolExecutor.SolidityFileDir private
Definition at line 23 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.ExecuteSolToBoogie().
SolidityFilePath
string VeriSolRunner.VeriSolExecutor.SolidityFilePath private
Definition at line 22 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.ExecuteSolToBoogie().
translatorFlags
TranslatorFlags VeriSolRunner.VeriSolExecutor.translatorFlags private
Definition at line 38 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.ExecuteSolToBoogie(), and VeriSolRunner.VeriSolExecutor.FindProof().
TryProof
bool VeriSolRunner.VeriSolExecutor.TryProof private
Definition at line 28 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.Execute().
TryRefutation
bool VeriSolRunner.VeriSolExecutor.TryRefutation private
Definition at line 29 of file VeriSolExecuter.cs.
Referenced by VeriSolRunner.VeriSolExecutor.Execute().
The documentation for this class was generated from the following file:
Sources/VeriSol/VeriSolExecuter.cs