VeriSol: SolidityAST.Literal Class Reference
SolidityAST.Literal Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
string Subdenomination [get, set]
string HexValue [get, set]
string Kind [get, set]
string Value [get, set]
Properties inherited from SolidityAST.Expression
List< TypeDescription > ArgumentTypes [get, set]
bool IsConstant [get, set]
bool IsPure [get, set]
bool IsLValue [get, set]
bool LValueRequested [get, set]
TypeDescription TypeDescriptions [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 1392 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.Literal.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1403 of file SolidityAST.cs.
References SolidityAST.IASTVisitor.EndVisit(), and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.Literal.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1409 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.Literal.ToString () inline
Definition at line 1414 of file SolidityAST.cs.
References SolidityAST.Literal.Kind, and SolidityAST.Literal.Value.
Property Documentation
HexValue
string SolidityAST.Literal.HexValue get set
Definition at line 1397 of file SolidityAST.cs.
Kind
string SolidityAST.Literal.Kind get set
Definition at line 1399 of file SolidityAST.cs.
Referenced by SolidityAST.Literal.ToString(), and SolToBoogie.ProcedureTranslator.Visit().
Subdenomination
string SolidityAST.Literal.Subdenomination get set
Definition at line 1395 of file SolidityAST.cs.
Value
string SolidityAST.Literal.Value get set
Definition at line 1401 of file SolidityAST.cs.
Referenced by SolidityAST.Literal.ToString(), SolToBoogie.ProcedureTranslator.TranslateNumberToExpr(), and SolToBoogie.ProcedureTranslator.Visit().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs