VeriSol: SolToBoogie.SourceInfoCollector Class Reference
SolToBoogie.SourceInfoCollector Class Reference
Public Member Functions
SourceInfoCollector (TranslatorContext context)
override bool Visit (SourceUnitList sourceUnits)
override bool Visit (SourceUnit node)
int MapToLineNumber (string srcFilePathName, int position)
Public Member Functions inherited from SolidityAST.BasicASTVisitor
virtual bool Visit (PragmaDirective node)
virtual bool Visit (UsingForDirective node)
virtual bool Visit (ImportDirective node)
virtual bool Visit (ContractDefinition node)
virtual bool Visit (InheritanceSpecifier node)
virtual bool Visit (FunctionDefinition node)
virtual bool Visit (ParameterList node)
virtual bool Visit (ModifierDefinition node)
virtual bool Visit (ModifierInvocation node)
virtual bool Visit (EventDefinition node)
virtual bool Visit (StructDefinition node)
virtual bool Visit (EnumDefinition node)
virtual bool Visit (EnumValue node)
virtual bool Visit (VariableDeclaration node)
virtual bool Visit (ElementaryTypeName node)
virtual bool Visit (UserDefinedTypeName node)
virtual bool Visit (Mapping node)
virtual bool Visit (ArrayTypeName node)
virtual bool Visit (Block node)
virtual bool Visit (PlaceholderStatement node)
virtual bool Visit (IfStatement node)
virtual bool Visit (WhileStatement node)
virtual bool Visit (DoWhileStatement node)
virtual bool Visit (ForStatement node)
virtual bool Visit (Continue node)
virtual bool Visit (Break node)
virtual bool Visit (Return node)
virtual bool Visit (Throw node)
virtual bool Visit (EmitStatement node)
virtual bool Visit (VariableDeclarationStatement node)
virtual bool Visit (InlineAssembly node)
virtual bool Visit (ExpressionStatement node)
virtual bool Visit (Literal node)
virtual bool Visit (Identifier node)
virtual bool Visit (ElementaryTypeNameExpression node)
virtual bool Visit (UnaryOperation node)
virtual bool Visit (BinaryOperation node)
virtual bool Visit (Conditional node)
virtual bool Visit (Assignment node)
virtual bool Visit (TupleExpression node)
virtual bool Visit (FunctionCall node)
virtual bool Visit (NewExpression node)
virtual bool Visit (MemberAccess node)
virtual bool Visit (IndexAccess node)
virtual void EndVisit (SourceUnitList node)
virtual void EndVisit (SourceUnit node)
virtual void EndVisit (PragmaDirective node)
virtual void EndVisit (UsingForDirective node)
virtual void EndVisit (ImportDirective node)
virtual void EndVisit (ContractDefinition node)
virtual void EndVisit (InheritanceSpecifier node)
virtual void EndVisit (FunctionDefinition node)
virtual void EndVisit (ParameterList node)
virtual void EndVisit (ModifierDefinition node)
virtual void EndVisit (ModifierInvocation node)
virtual void EndVisit (EventDefinition node)
virtual void EndVisit (StructDefinition node)
virtual void EndVisit (EnumDefinition node)
virtual void EndVisit (EnumValue node)
virtual void EndVisit (VariableDeclaration node)
virtual void EndVisit (ElementaryTypeName node)
virtual void EndVisit (UserDefinedTypeName node)
virtual void EndVisit (Mapping node)
virtual void EndVisit (ArrayTypeName node)
virtual void EndVisit (Block node)
virtual void EndVisit (PlaceholderStatement node)
virtual void EndVisit (IfStatement node)
virtual void EndVisit (WhileStatement node)
virtual void EndVisit (DoWhileStatement node)
virtual void EndVisit (ForStatement node)
virtual void EndVisit (Continue node)
virtual void EndVisit (Break node)
virtual void EndVisit (Return node)
virtual void EndVisit (Throw node)
virtual void EndVisit (EmitStatement node)
virtual void EndVisit (VariableDeclarationStatement node)
virtual void EndVisit (InlineAssembly node)
virtual void EndVisit (ExpressionStatement node)
virtual void EndVisit (Literal node)
virtual void EndVisit (Identifier node)
virtual void EndVisit (ElementaryTypeNameExpression node)
virtual void EndVisit (UnaryOperation node)
virtual void EndVisit (BinaryOperation node)
virtual void EndVisit (Conditional node)
virtual void EndVisit (Assignment node)
virtual void EndVisit (TupleExpression node)
virtual void EndVisit (FunctionCall node)
virtual void EndVisit (NewExpression node)
virtual void EndVisit (MemberAccess node)
virtual void EndVisit (IndexAccess node)
Protected Member Functions
override void CommonEndVisit (ASTNode node)
Protected Member Functions inherited from SolidityAST.BasicASTVisitor
virtual bool CommonVisit (ASTNode node)
Private Member Functions
List< int > computeLineBreaks (string filePath)
Private Attributes
TranslatorContext context
SourceUnit currentSourceUnit
Dictionary< string, List< int > > DictLineBreaks = new Dictionary<string, List<int>>()
Detailed Description
Definition at line 9 of file SourceInfoCollector.cs.
Constructor & Destructor Documentation
SourceInfoCollector()
SolToBoogie.SourceInfoCollector.SourceInfoCollector (TranslatorContext context) inline
Definition at line 20 of file SourceInfoCollector.cs.
References SolToBoogie.SourceInfoCollector.context.
Member Function Documentation
CommonEndVisit()
override void SolToBoogie.SourceInfoCollector.CommonEndVisit (ASTNode node) inline protected virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 43 of file SourceInfoCollector.cs.
References SolidityAST.SourceUnit.AbsolutePath, SolToBoogie.TranslatorContext.AddSourceInfoForASTNode(), SolToBoogie.SourceInfoCollector.context, SolToBoogie.SourceInfoCollector.currentSourceUnit, SolToBoogie.SourceInfoCollector.MapToLineNumber(), SolToBoogie.TranslatorContext.SourceDirectory, and SolidityAST.ASTNode.Src.
computeLineBreaks()
List<int> SolToBoogie.SourceInfoCollector.computeLineBreaks (string filePath) inline private
Definition at line 76 of file SourceInfoCollector.cs.
Referenced by SolToBoogie.SourceInfoCollector.Visit().
MapToLineNumber()
int SolToBoogie.SourceInfoCollector.MapToLineNumber (string srcFilePathName, int position) inline
Definition at line 59 of file SourceInfoCollector.cs.
References SolToBoogie.SourceInfoCollector.DictLineBreaks.
Referenced by SolToBoogie.SourceInfoCollector.CommonEndVisit().
Visit() [1/2]
override bool SolToBoogie.SourceInfoCollector.Visit (SourceUnit node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 37 of file SourceInfoCollector.cs.
References SolToBoogie.SourceInfoCollector.currentSourceUnit.
Visit() [2/2]
override bool SolToBoogie.SourceInfoCollector.Visit (SourceUnitList sourceUnits) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 25 of file SourceInfoCollector.cs.
References SolToBoogie.SourceInfoCollector.computeLineBreaks(), SolToBoogie.SourceInfoCollector.context, SolToBoogie.SourceInfoCollector.DictLineBreaks, and SolToBoogie.TranslatorContext.SourceDirectory.
Member Data Documentation
context
TranslatorContext SolToBoogie.SourceInfoCollector.context private
Definition at line 12 of file SourceInfoCollector.cs.
Referenced by SolToBoogie.SourceInfoCollector.CommonEndVisit(), SolToBoogie.SourceInfoCollector.SourceInfoCollector(), and SolToBoogie.SourceInfoCollector.Visit().
currentSourceUnit
SourceUnit SolToBoogie.SourceInfoCollector.currentSourceUnit private
Definition at line 15 of file SourceInfoCollector.cs.
Referenced by SolToBoogie.SourceInfoCollector.CommonEndVisit(), and SolToBoogie.SourceInfoCollector.Visit().
DictLineBreaks
Dictionary<string, List<int> > SolToBoogie.SourceInfoCollector.DictLineBreaks = new Dictionary<string, List<int>>() private
Definition at line 18 of file SourceInfoCollector.cs.
Referenced by SolToBoogie.SourceInfoCollector.MapToLineNumber(), and SolToBoogie.SourceInfoCollector.Visit().
The documentation for this class was generated from the following file:
Sources/SolToBoogie/SourceInfoCollector.cs