VeriSol: SolidityCFG.TestMain Class Reference
SolidityCFG.TestMain Class Reference
Static Public Member Functions
static void Main (string[] args)
Static Private Member Functions
static void Test (FunctionDefinition func)
static void PrintCFG (CFGNode root)
Detailed Description
Definition at line 11 of file TestMain.cs.
Member Function Documentation
Main()
static void SolidityCFG.TestMain.Main (string[] args) inline static
Definition at line 13 of file TestMain.cs.
References SolidityAST.SoliditySourceFile.Ast, SolidityAST.SolidityCompiler.Compile(), SolidityAST.ContractDefinition.Name, SolidityAST.FunctionDefinition.Name, SolidityAST.CompilerOutput.Sources, and SolidityCFG.TestMain.Test().
PrintCFG()
static void SolidityCFG.TestMain.PrintCFG (CFGNode root) inline static private
Definition at line 54 of file TestMain.cs.
References SolidityCFG.CFGNode.Exits.
Referenced by SolidityCFG.TestMain.Test().
Test()
static void SolidityCFG.TestMain.Test (FunctionDefinition func) inline static private
Definition at line 47 of file TestMain.cs.
References SolidityCFG.CFGBuilder.BuildFunctionCFG(), SolidityCFG.FunctionCFG.Entry, and SolidityCFG.TestMain.PrintCFG().
Referenced by SolidityCFG.TestMain.Main().
The documentation for this class was generated from the following file:
Sources/SolidityCFG/TestMain.cs