VeriSol: SolidityAST.ElementaryTypeNameExpression Class Reference
SolidityAST.ElementaryTypeNameExpression Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
string TypeName [get, set]
Properties inherited from SolidityAST.Expression
List< TypeDescription > ArgumentTypes [get, set]
bool IsConstant [get, set]
bool IsPure [get, set]
bool IsLValue [get, set]
bool LValueRequested [get, set]
TypeDescription TypeDescriptions [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 1452 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.ElementaryTypeNameExpression.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1456 of file SolidityAST.cs.
References SolidityAST.IASTVisitor.EndVisit(), and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.ElementaryTypeNameExpression.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1462 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.ElementaryTypeNameExpression.ToString () inline
Definition at line 1467 of file SolidityAST.cs.
References SolidityAST.ElementaryTypeNameExpression.TypeName.
Property Documentation
TypeName
string SolidityAST.ElementaryTypeNameExpression.TypeName get set
Definition at line 1454 of file SolidityAST.cs.
Referenced by SolidityAST.ElementaryTypeNameExpression.ToString().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs