VeriSol: VeriSolRunner.ExternalTools.DotnetCliToolManager Class Reference
VeriSolRunner.ExternalTools.DotnetCliToolManager Class Reference
Package Functions
DotnetCliToolManager (ToolSourceSettings settings)
override void EnsureExisted ()
void EnsureLinkedToZ3 (ToolManager z3)
Package Functions inherited from VeriSolRunner.ExternalTools.ToolManager
ToolManager (ToolSourceSettings settings)
Properties
string DependencyTargetPath [get]
Properties inherited from VeriSolRunner.ExternalTools.ToolManager
static string OsName [get]
string ExeName [get]
string Command [get]
Private Member Functions
string InstallDotnetCliTool ()
string GetZ3DependencyPath (ToolManager z3)
Additional Inherited Members
Protected Member Functions inherited from VeriSolRunner.ExternalTools.ToolManager
bool Exists ()
void EnsureCommandPathExisted ()
Protected Attributes inherited from VeriSolRunner.ExternalTools.ToolManager
readonly ToolSourceSettings settings
Detailed Description
Definition at line 7 of file DotnetCliToolManager.cs.
Constructor & Destructor Documentation
DotnetCliToolManager()
VeriSolRunner.ExternalTools.DotnetCliToolManager.DotnetCliToolManager (ToolSourceSettings settings) inline package
Definition at line 17 of file DotnetCliToolManager.cs.
Member Function Documentation
EnsureExisted()
override void VeriSolRunner.ExternalTools.DotnetCliToolManager.EnsureExisted () inline package virtual
Implements VeriSolRunner.ExternalTools.ToolManager.
Definition at line 21 of file DotnetCliToolManager.cs.
References VeriSolRunner.ExternalTools.ToolManager.EnsureCommandPathExisted(), VeriSolRunner.ExternalTools.ToolManager.Exists(), VeriSolRunner.ExternalTools.DotnetCliToolManager.InstallDotnetCliTool(), and VeriSolRunner.ExternalTools.ExternalToolsManager.Log().
EnsureLinkedToZ3()
void VeriSolRunner.ExternalTools.DotnetCliToolManager.EnsureLinkedToZ3 (ToolManager z3) inline package
Definition at line 68 of file DotnetCliToolManager.cs.
References VeriSolRunner.ExternalTools.ToolManager.Command, VeriSolRunner.ExternalTools.DotnetCliToolManager.GetZ3DependencyPath(), and VeriSolRunner.ExternalTools.ExternalToolsManager.Log().
GetZ3DependencyPath()
string VeriSolRunner.ExternalTools.DotnetCliToolManager.GetZ3DependencyPath (ToolManager z3) inline private
Definition at line 91 of file DotnetCliToolManager.cs.
References VeriSolRunner.ExternalTools.DotnetCliToolManager.DependencyTargetPath, and VeriSolRunner.ExternalTools.ToolManager.ExeName.
Referenced by VeriSolRunner.ExternalTools.DotnetCliToolManager.EnsureLinkedToZ3().
InstallDotnetCliTool()
string VeriSolRunner.ExternalTools.DotnetCliToolManager.InstallDotnetCliTool () inline private
Definition at line 34 of file DotnetCliToolManager.cs.
References VeriSolRunner.ExternalTools.ExternalToolsManager.Log().
Referenced by VeriSolRunner.ExternalTools.DotnetCliToolManager.EnsureExisted().
Property Documentation
DependencyTargetPath
string VeriSolRunner.ExternalTools.DotnetCliToolManager.DependencyTargetPath get package
Definition at line 9 of file DotnetCliToolManager.cs.
Referenced by VeriSolRunner.ExternalTools.DotnetCliToolManager.GetZ3DependencyPath().
The documentation for this class was generated from the following file:
Sources/ExternalToolsManager/DotnetCliToolManager.cs