VeriSol: BoogieAST.BoogieProgram Class Reference
BoogieAST.BoogieProgram Class Reference
Public Member Functions
BoogieProgram ()
void AddDeclaration (BoogieDeclaration declaration)
override string ToString ()
Properties
List< BoogieDeclaration > Declarations [get, set]
Detailed Description
Definition at line 36 of file BoogieAST.cs.
Constructor & Destructor Documentation
BoogieProgram()
BoogieAST.BoogieProgram.BoogieProgram () inline
Definition at line 40 of file BoogieAST.cs.
References BoogieAST.BoogieProgram.Declarations.
Member Function Documentation
AddDeclaration()
void BoogieAST.BoogieProgram.AddDeclaration (BoogieDeclaration declaration) inline
Definition at line 45 of file BoogieAST.cs.
References BoogieAST.BoogieProgram.Declarations.
Referenced by SolToBoogie.FallbackGenerator.Generate(), SolToBoogie.RevertLogicGenerator.Generate(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAxioms(), SolToBoogie.HarnessGenerator.GenerateBoogieHarnessForContract(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateBoogieRecord(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateConstants(), SolToBoogie.ProcedureTranslator.GenerateConstructorWithBaseCalls(), SolToBoogie.HarnessGenerator.GenerateCorralChoiceProcForContract(), SolToBoogie.HarnessGenerator.GenerateCorralHarnessForContract(), SolToBoogie.ProcedureTranslator.GenerateDefaultConstructor(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateFunctions(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalProcedureAllocMany(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalProcedureFresh(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalVariables(), SolToBoogie.HarnessGenerator.GenerateHoudiniVarsForContract(), SolToBoogie.HarnessGenerator.GenerateModifiers(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateSingleMemoryVariable(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateStructConstructors(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateTypes(), SolToBoogie.ProcedureTranslator.TranslateStateVarDeclaration(), SolToBoogie.ProcedureTranslator.TranslateStructDefinition(), and SolToBoogie.ProcedureTranslator.Visit().
ToString()
override string BoogieAST.BoogieProgram.ToString () inline
Definition at line 50 of file BoogieAST.cs.
References BoogieAST.BoogieProgram.Declarations.
Property Documentation
Declarations
List<BoogieDeclaration> BoogieAST.BoogieProgram.Declarations get set
Definition at line 38 of file BoogieAST.cs.
Referenced by BoogieAST.BoogieProgram.AddDeclaration(), BoogieAST.BoogieProgram.BoogieProgram(), SolToBoogie.FallbackGenerator.Generate(), SolToBoogie.RevertLogicGenerator.Generate(), SolToBoogie.RevertLogicGenerator.RevertLogicGenerator(), and BoogieAST.BoogieProgram.ToString().
The documentation for this class was generated from the following file:
Sources/BoogieAST/BoogieAST.cs