VeriSol: SolToBoogie.QVarGenerator Class Reference
SolToBoogie.QVarGenerator Class Reference
Static Public Member Functions
static BoogieIdentifierExpr NewQVar (int level, int pos)
Detailed Description
Definition at line 3805 of file ProcedureTranslator.cs.
Member Function Documentation
NewQVar()
static BoogieIdentifierExpr SolToBoogie.QVarGenerator.NewQVar (int level, int pos) inline static
Definition at line 3807 of file ProcedureTranslator.cs.
Referenced by SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodePackedAxiomOneArg(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodePackedAxiomOneArgRef(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodePackedAxiomTwoArgs(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateAbiEncodePackedAxiomTwoArgsOneRef(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateConstToRefAxiom(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateGlobalProcedureAllocMany(), SolToBoogie.ProcedureTranslator.GenerateInitializationForMappingStateVar(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateKeccakAxiom(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateVeriSolSumAxioms(), SolToBoogie.ProcedureTranslator.InitializeNestedArrayMappingStateVar(), SolToBoogie.ProcedureTranslator.TranslateModifiesStmt(), and SolToBoogie.ProcedureTranslator.Visit().
The documentation for this class was generated from the following file:
Sources/SolToBoogie/ProcedureTranslator.cs