VeriSol: SolidityAST.ParameterList Class Reference
SolidityAST.ParameterList Class Reference
Public Member Functions
int Length ()
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
List< VariableDeclaration > Parameters [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 496 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.ParameterList.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 505 of file SolidityAST.cs.
References SolidityAST.IASTVisitor.EndVisit(), SolidityAST.ParameterList.Parameters, and SolidityAST.IASTVisitor.Visit().
Referenced by SolidityAST.FunctionDefinition.Accept(), SolidityAST.ModifierDefinition.Accept(), SolidityAST.EventDefinition.Accept(), and SolToBoogie.ProcedureTranslator.Visit().
Accept< T >()
override T SolidityAST.ParameterList.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 514 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
Length()
int SolidityAST.ParameterList.Length () inline
Definition at line 500 of file SolidityAST.cs.
References SolidityAST.ParameterList.Parameters.
Referenced by SolToBoogie.TransUtils.ComputeEventSignature(), SolToBoogie.TransUtils.ComputeFunctionSignature(), and SolidityAST.FunctionDefinition.ToString().
ToString()
override string SolidityAST.ParameterList.ToString () inline
Definition at line 519 of file SolidityAST.cs.
References SolidityAST.ParameterList.Parameters.
Property Documentation
Parameters
List<VariableDeclaration> SolidityAST.ParameterList.Parameters get set
Definition at line 498 of file SolidityAST.cs.
Referenced by SolidityAST.ParameterList.Accept(), SolToBoogie.TransUtils.CollectLocalVars(), SolToBoogie.TransUtils.ComputeEventSignature(), SolToBoogie.TransUtils.ComputeFunctionSignature(), SolToBoogie.TransUtils.GenerateChoiceBlock(), SolToBoogie.ProcedureTranslator.IsVeriSolContractInvariantFunction(), SolidityAST.ParameterList.Length(), SolidityAST.ParameterList.ToString(), and SolToBoogie.ProcedureTranslator.Visit().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs