VeriSol: SolidityCFG.CFGBuilder Class Reference
SolidityCFG.CFGBuilder Class Reference
Public Member Functions
override bool Visit (BinaryOperation astNode)
override bool Visit (Conditional astNode)
override bool Visit (IfStatement astNode)
Public Member Functions inherited from SolidityAST.BasicASTVisitor
virtual bool Visit (SourceUnitList node)
virtual bool Visit (SourceUnit node)
virtual bool Visit (PragmaDirective node)
virtual bool Visit (UsingForDirective node)
virtual bool Visit (ImportDirective node)
virtual bool Visit (ContractDefinition node)
virtual bool Visit (InheritanceSpecifier node)
virtual bool Visit (FunctionDefinition node)
virtual bool Visit (ParameterList node)
virtual bool Visit (ModifierDefinition node)
virtual bool Visit (ModifierInvocation node)
virtual bool Visit (EventDefinition node)
virtual bool Visit (StructDefinition node)
virtual bool Visit (EnumDefinition node)
virtual bool Visit (EnumValue node)
virtual bool Visit (VariableDeclaration node)
virtual bool Visit (ElementaryTypeName node)
virtual bool Visit (UserDefinedTypeName node)
virtual bool Visit (Mapping node)
virtual bool Visit (ArrayTypeName node)
virtual bool Visit (Block node)
virtual bool Visit (PlaceholderStatement node)
virtual bool Visit (WhileStatement node)
virtual bool Visit (DoWhileStatement node)
virtual bool Visit (ForStatement node)
virtual bool Visit (Continue node)
virtual bool Visit (Break node)
virtual bool Visit (Return node)
virtual bool Visit (Throw node)
virtual bool Visit (EmitStatement node)
virtual bool Visit (VariableDeclarationStatement node)
virtual bool Visit (InlineAssembly node)
virtual bool Visit (ExpressionStatement node)
virtual bool Visit (Literal node)
virtual bool Visit (Identifier node)
virtual bool Visit (ElementaryTypeNameExpression node)
virtual bool Visit (UnaryOperation node)
virtual bool Visit (Assignment node)
virtual bool Visit (TupleExpression node)
virtual bool Visit (FunctionCall node)
virtual bool Visit (NewExpression node)
virtual bool Visit (MemberAccess node)
virtual bool Visit (IndexAccess node)
virtual void EndVisit (SourceUnitList node)
virtual void EndVisit (SourceUnit node)
virtual void EndVisit (PragmaDirective node)
virtual void EndVisit (UsingForDirective node)
virtual void EndVisit (ImportDirective node)
virtual void EndVisit (ContractDefinition node)
virtual void EndVisit (InheritanceSpecifier node)
virtual void EndVisit (FunctionDefinition node)
virtual void EndVisit (ParameterList node)
virtual void EndVisit (ModifierDefinition node)
virtual void EndVisit (ModifierInvocation node)
virtual void EndVisit (EventDefinition node)
virtual void EndVisit (StructDefinition node)
virtual void EndVisit (EnumDefinition node)
virtual void EndVisit (EnumValue node)
virtual void EndVisit (VariableDeclaration node)
virtual void EndVisit (ElementaryTypeName node)
virtual void EndVisit (UserDefinedTypeName node)
virtual void EndVisit (Mapping node)
virtual void EndVisit (ArrayTypeName node)
virtual void EndVisit (Block node)
virtual void EndVisit (PlaceholderStatement node)
virtual void EndVisit (IfStatement node)
virtual void EndVisit (WhileStatement node)
virtual void EndVisit (DoWhileStatement node)
virtual void EndVisit (ForStatement node)
virtual void EndVisit (Continue node)
virtual void EndVisit (Break node)
virtual void EndVisit (Return node)
virtual void EndVisit (Throw node)
virtual void EndVisit (EmitStatement node)
virtual void EndVisit (VariableDeclarationStatement node)
virtual void EndVisit (InlineAssembly node)
virtual void EndVisit (ExpressionStatement node)
virtual void EndVisit (Literal node)
virtual void EndVisit (Identifier node)
virtual void EndVisit (ElementaryTypeNameExpression node)
virtual void EndVisit (UnaryOperation node)
virtual void EndVisit (BinaryOperation node)
virtual void EndVisit (Conditional node)
virtual void EndVisit (Assignment node)
virtual void EndVisit (TupleExpression node)
virtual void EndVisit (FunctionCall node)
virtual void EndVisit (NewExpression node)
virtual void EndVisit (MemberAccess node)
virtual void EndVisit (IndexAccess node)
Static Public Member Functions
static FunctionCFG BuildFunctionCFG (CFGNodeFactory factory, FunctionDefinition func)
Protected Member Functions
override bool CommonVisit (ASTNode astNode)
Protected Member Functions inherited from SolidityAST.BasicASTVisitor
virtual void CommonEndVisit (ASTNode node)
Private Member Functions
CFGBuilder (CFGNodeFactory factory, FunctionCFG currentCFG)
void AppendControlFlow (ASTNode astNode)
CFGNode CreateControlFlow (CFGNode entry, ASTNode astNode)
List< CFGNode > SplitControlFlow (int num)
void MergeControlFlow (List< CFGNode > nodes, CFGNode destination=null)
Static Private Member Functions
static void ConnectControlFlow (CFGNode from, CFGNode to)
Private Attributes
CFGNodeFactory factory
FunctionCFG currentCFG
CFGNode currentNode
Detailed Description
Definition at line 10 of file CFGBuilder.cs.
Constructor & Destructor Documentation
CFGBuilder()
SolidityCFG.CFGBuilder.CFGBuilder (CFGNodeFactory factory, FunctionCFG currentCFG) inline private
Definition at line 37 of file CFGBuilder.cs.
References SolidityCFG.CFGBuilder.currentCFG, SolidityCFG.FunctionCFG.Entry, and SolidityCFG.CFGBuilder.factory.
Referenced by SolidityCFG.CFGBuilder.BuildFunctionCFG().
Member Function Documentation
AppendControlFlow()
void SolidityCFG.CFGBuilder.AppendControlFlow (ASTNode astNode) inline private
Definition at line 44 of file CFGBuilder.cs.
References SolidityAST.ASTNode.Accept().
Referenced by SolidityCFG.CFGBuilder.BuildFunctionCFG(), SolidityCFG.CFGBuilder.CreateControlFlow(), and SolidityCFG.CFGBuilder.Visit().
BuildFunctionCFG()
static FunctionCFG SolidityCFG.CFGBuilder.BuildFunctionCFG (CFGNodeFactory factory, FunctionDefinition func) inline static
Definition at line 18 of file CFGBuilder.cs.
References SolidityCFG.CFGBuilder.AppendControlFlow(), SolidityCFG.CFGBuilder.CFGBuilder(), SolidityCFG.CFGBuilder.ConnectControlFlow(), SolidityCFG.CFGBuilder.currentNode, SolidityCFG.CFGBuilder.factory, and SolidityCFG.CFGNodeFactory.MakeNode().
Referenced by SolidityCFG.TestMain.Test().
CommonVisit()
override bool SolidityCFG.CFGBuilder.CommonVisit (ASTNode astNode) inline protected virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 91 of file CFGBuilder.cs.
References SolidityCFG.BasicBlock.AddExpression(), SolidityCFG.CFGNode.Block, and SolidityCFG.CFGBuilder.currentNode.
ConnectControlFlow()
static void SolidityCFG.CFGBuilder.ConnectControlFlow (CFGNode from, CFGNode to) inline static private
Definition at line 29 of file CFGBuilder.cs.
References SolidityCFG.CFGNode.Entries, and SolidityCFG.CFGNode.Exits.
Referenced by SolidityCFG.CFGBuilder.BuildFunctionCFG(), SolidityCFG.CFGBuilder.MergeControlFlow(), and SolidityCFG.CFGBuilder.SplitControlFlow().
CreateControlFlow()
CFGNode SolidityCFG.CFGBuilder.CreateControlFlow (CFGNode entry, ASTNode astNode) inline private
Definition at line 49 of file CFGBuilder.cs.
References SolidityCFG.CFGBuilder.AppendControlFlow(), and SolidityCFG.CFGBuilder.currentNode.
Referenced by SolidityCFG.CFGBuilder.Visit().
MergeControlFlow()
void SolidityCFG.CFGBuilder.MergeControlFlow (List< CFGNode > nodes, CFGNode destination = null) inline private
Definition at line 74 of file CFGBuilder.cs.
References SolidityCFG.CFGBuilder.ConnectControlFlow(), SolidityCFG.CFGBuilder.currentNode, SolidityCFG.CFGBuilder.factory, and SolidityCFG.CFGNodeFactory.MakeNode().
Referenced by SolidityCFG.CFGBuilder.Visit().
SplitControlFlow()
List<CFGNode> SolidityCFG.CFGBuilder.SplitControlFlow (int num) inline private
Definition at line 59 of file CFGBuilder.cs.
References SolidityCFG.CFGBuilder.ConnectControlFlow(), SolidityCFG.CFGBuilder.currentNode, SolidityCFG.CFGBuilder.factory, and SolidityCFG.CFGNodeFactory.MakeNode().
Referenced by SolidityCFG.CFGBuilder.Visit().
Visit() [1/3]
override bool SolidityCFG.CFGBuilder.Visit (BinaryOperation astNode) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 100 of file CFGBuilder.cs.
References SolidityCFG.CFGBuilder.AppendControlFlow(), SolidityCFG.CFGNode.Block, SolidityCFG.CFGBuilder.CreateControlFlow(), SolidityCFG.CFGBuilder.currentNode, SolidityAST.BinaryOperation.LeftExpression, SolidityCFG.CFGBuilder.MergeControlFlow(), SolidityAST.BinaryOperation.Operator, SolidityAST.BinaryOperation.RightExpression, SolidityCFG.BasicBlock.SetPredicate(), and SolidityCFG.CFGBuilder.SplitControlFlow().
Visit() [2/3]
override bool SolidityCFG.CFGBuilder.Visit (Conditional astNode) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 134 of file CFGBuilder.cs.
References SolidityAST.ASTNode.Accept(), SolidityAST.Conditional.Condition, SolidityCFG.CFGBuilder.CreateControlFlow(), SolidityAST.Conditional.FalseExpression, SolidityCFG.CFGBuilder.MergeControlFlow(), SolidityCFG.CFGBuilder.SplitControlFlow(), and SolidityAST.Conditional.TrueExpression.
Visit() [3/3]
override bool SolidityCFG.CFGBuilder.Visit (IfStatement astNode) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 148 of file CFGBuilder.cs.
References SolidityAST.ASTNode.Accept(), SolidityCFG.CFGNode.Block, SolidityAST.IfStatement.Condition, SolidityCFG.CFGBuilder.CreateControlFlow(), SolidityCFG.CFGBuilder.currentNode, SolidityAST.IfStatement.FalseBody, SolidityCFG.CFGBuilder.MergeControlFlow(), SolidityCFG.BasicBlock.SetPredicate(), SolidityCFG.CFGBuilder.SplitControlFlow(), and SolidityAST.IfStatement.TrueBody.
Member Data Documentation
currentCFG
FunctionCFG SolidityCFG.CFGBuilder.currentCFG private
Definition at line 14 of file CFGBuilder.cs.
Referenced by SolidityCFG.CFGBuilder.CFGBuilder().
currentNode
CFGNode SolidityCFG.CFGBuilder.currentNode private
Definition at line 16 of file CFGBuilder.cs.
Referenced by SolidityCFG.CFGBuilder.BuildFunctionCFG(), SolidityCFG.CFGBuilder.CommonVisit(), SolidityCFG.CFGBuilder.CreateControlFlow(), SolidityCFG.CFGBuilder.MergeControlFlow(), SolidityCFG.CFGBuilder.SplitControlFlow(), and SolidityCFG.CFGBuilder.Visit().
factory
CFGNodeFactory SolidityCFG.CFGBuilder.factory private
Definition at line 12 of file CFGBuilder.cs.
Referenced by SolidityCFG.CFGBuilder.BuildFunctionCFG(), SolidityCFG.CFGBuilder.CFGBuilder(), SolidityCFG.CFGBuilder.MergeControlFlow(), and SolidityCFG.CFGBuilder.SplitControlFlow().
The documentation for this class was generated from the following file:
Sources/SolidityCFG/CFGBuilder.cs