VeriSol: SolidityAST.Return Class Reference
SolidityAST.Return Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
Expression Expression [get, set]
int FunctionReturnParameters [get, set]
Properties inherited from SolidityAST.Statement
string Documnetation [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 1186 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.Return.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1192 of file SolidityAST.cs.
References SolidityAST.ASTNode.Accept(), SolidityAST.IASTVisitor.EndVisit(), and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.Return.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1204 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.Return.ToString () inline
Definition at line 1209 of file SolidityAST.cs.
Property Documentation
Expression
Expression SolidityAST.Return.Expression get set
Definition at line 1188 of file SolidityAST.cs.
Referenced by SolToBoogie.ProcedureTranslator.Visit().
FunctionReturnParameters
int SolidityAST.Return.FunctionReturnParameters get set
Definition at line 1190 of file SolidityAST.cs.
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs