VeriSol: VeriSolRunner.ExternalTools.SolcManager Class Reference
VeriSolRunner.ExternalTools.SolcManager Class Reference
Public Member Functions
SolcManager (ToolSourceSettings settings)
Protected Member Functions
override void Install ()
Protected Member Functions inherited from VeriSolRunner.ExternalTools.DownloadedToolManager
void DownloadAndUnZip ()
void DownloadAndCopy ()
void CreateSymbolicLink ()
Protected Member Functions inherited from VeriSolRunner.ExternalTools.ToolManager
bool Exists ()
void EnsureCommandPathExisted ()
Additional Inherited Members
Protected Attributes inherited from VeriSolRunner.ExternalTools.ToolManager
readonly ToolSourceSettings settings
Package Functions inherited from VeriSolRunner.ExternalTools.DownloadedToolManager
DownloadedToolManager (ToolSourceSettings settings)
override void EnsureExisted ()
Package Functions inherited from VeriSolRunner.ExternalTools.ToolManager
ToolManager (ToolSourceSettings settings)
Properties inherited from VeriSolRunner.ExternalTools.DownloadedToolManager
string DownloadURL [get]
string ExePathWithinZip [get]
string ZipFileName [get]
string TempDirectory [get]
string ZipFilePath [get]
string ExtractPath [get]
string ExeTempPath [get]
Properties inherited from VeriSolRunner.ExternalTools.ToolManager
static string OsName [get]
string ExeName [get]
string Command [get]
Detailed Description
Definition at line 3 of file SolcManager.cs.
Constructor & Destructor Documentation
SolcManager()
VeriSolRunner.ExternalTools.SolcManager.SolcManager (ToolSourceSettings settings) inline
Definition at line 5 of file SolcManager.cs.
Member Function Documentation
Install()
override void VeriSolRunner.ExternalTools.SolcManager.Install () inline protected virtual
Reimplemented from VeriSolRunner.ExternalTools.DownloadedToolManager.
Definition at line 9 of file SolcManager.cs.
References VeriSolRunner.ExternalTools.DownloadedToolManager.CreateSymbolicLink(), VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadAndCopy(), VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadAndUnZip(), and VeriSolRunner.ExternalTools.ToolManager.OsName.
The documentation for this class was generated from the following file:
Sources/ExternalToolsManager/SolcManager.cs