VeriSol: SolidityAST.Mapping Class Reference
SolidityAST.Mapping Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
ElementaryTypeName KeyType [get, set]
TypeName ValueType [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 860 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.Mapping.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 866 of file SolidityAST.cs.
References SolidityAST.ASTNode.Accept(), SolidityAST.ElementaryTypeName.Accept(), SolidityAST.IASTVisitor.EndVisit(), SolidityAST.Mapping.KeyType, SolidityAST.Mapping.ValueType, and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.Mapping.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 876 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.Mapping.ToString () inline
Definition at line 881 of file SolidityAST.cs.
References SolidityAST.Mapping.KeyType, and SolidityAST.Mapping.ValueType.
Property Documentation
KeyType
ElementaryTypeName SolidityAST.Mapping.KeyType get set
Definition at line 862 of file SolidityAST.cs.
Referenced by SolidityAST.Mapping.Accept(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForMapping(), SolToBoogie.ProcedureTranslator.GetBoogieTypesFromMapping(), SolToBoogie.ProcedureTranslator.InitializeNestedArrayMappingStateVar(), and SolidityAST.Mapping.ToString().
ValueType
TypeName SolidityAST.Mapping.ValueType get set
Definition at line 864 of file SolidityAST.cs.
Referenced by SolidityAST.Mapping.Accept(), SolToBoogie.ProcedureTranslator.GenerateInitializationForMappingStateVar(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForMapping(), SolToBoogie.ProcedureTranslator.GetBoogieTypesFromMapping(), and SolidityAST.Mapping.ToString().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs