VeriSol: SolidityAST.Break Class Reference
SolidityAST.Break Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Additional Inherited Members
Properties inherited from SolidityAST.Statement
string Documnetation [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 1167 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.Break.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1169 of file SolidityAST.cs.
References SolidityAST.IASTVisitor.EndVisit(), and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.Break.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1175 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.Break.ToString () inline
Definition at line 1180 of file SolidityAST.cs.
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs