VeriSol: SolToBoogie.HoudiniHelper Class Reference
SolToBoogie.HoudiniHelper Class Reference
Static Public Member Functions
static Dictionary< int, BoogieExpr > GenerateHoudiniVarMapping (ContractDefinition contract, TranslatorContext context)
Static Private Member Functions
static BoogieMapSelect GetBoogieExprOfStateVar (VariableDeclaration varDecl, TranslatorContext context)
static void PrintHoudiniCandidateMap (Dictionary< int, BoogieExpr > map)
Detailed Description
Definition at line 10 of file HoudiniHelper.cs.
Member Function Documentation
GenerateHoudiniVarMapping()
static Dictionary<int, BoogieExpr> SolToBoogie.HoudiniHelper.GenerateHoudiniVarMapping (ContractDefinition contract, TranslatorContext context) inline static
Definition at line 13 of file HoudiniHelper.cs.
References SolToBoogie.HoudiniHelper.GetBoogieExprOfStateVar(), SolToBoogie.TranslatorContext.GetVisibleStateVarsByContract(), and SolidityAST.VariableDeclaration.TypeName.
Referenced by SolToBoogie.HarnessGenerator.Generate().
GetBoogieExprOfStateVar()
static BoogieMapSelect SolToBoogie.HoudiniHelper.GetBoogieExprOfStateVar (VariableDeclaration varDecl, TranslatorContext context) inline static private
Definition at line 63 of file HoudiniHelper.cs.
References SolToBoogie.TransUtils.GetCanonicalStateVariableName().
Referenced by SolToBoogie.HoudiniHelper.GenerateHoudiniVarMapping().
PrintHoudiniCandidateMap()
static void SolToBoogie.HoudiniHelper.PrintHoudiniCandidateMap (Dictionary< int, BoogieExpr > map) inline static private
Definition at line 70 of file HoudiniHelper.cs.
The documentation for this class was generated from the following file:
Sources/SolToBoogie/HoudiniHelper.cs