VeriSol: SolToBoogie.TransUtils Class Reference
SolToBoogie.TransUtils Class Reference
Static Public Member Functions
static BoogieType GetBoogieTypeFromSolidityTypeName (TypeName type)
static string GetCanonicalVariableName (VariableDeclaration varDecl, TranslatorContext context)
static string GetCanonicalLocalVariableName (VariableDeclaration varDecl, TranslatorContext context)
static string GetCanonicalStateVariableName (VariableDeclaration varDecl, TranslatorContext context)
static string GetCanonicalFunctionName (FunctionDefinition funcDef, TranslatorContext context)
static string GetCanonicalConstructorName (ContractDefinition contract)
static int GetEnumValueIndex (EnumDefinition enumDef, string value)
static string ComputeFunctionSignature (FunctionDefinition funcDef)
static string ComputeEventSignature (EventDefinition eventDef)
static string InferFunctionSignature (TranslatorContext context, FunctionCall node)
static string InferTypeFromExpression (Expression expression)
static string GetFuncNameFromFuncCall (FunctionCall node)
static string GetFuncNameFromFuncCallExpr (Expression expr)
static Tuple< string, int > GenerateSourceInfoAnnotation (ASTNode node, TranslatorContext context)
static List< BoogieVariable > GetDefaultInParams ()
static List< BoogieExpr > GetDefaultArguments ()
static List< BoogieVariable > CollectLocalVars (List< ContractDefinition > contracts, TranslatorContext context)
static BoogieIfCmd GenerateChoiceBlock (List< ContractDefinition > contracts, TranslatorContext context, Tuple< string, string > callBackTarget=null)
generate a non-deterministic choice block to call every public visible functions except constructors
static void havocGas (BoogieStmtList list)
static void havocGas (List< BoogieCmd > list)
Static Private Member Functions
static string InferTypeFromTypeString (string typestr)
Detailed Description
Definition at line 280 of file TransUtils.cs.
Member Function Documentation
CollectLocalVars()
static List<BoogieVariable> SolToBoogie.TransUtils.CollectLocalVars (List< ContractDefinition > contracts, TranslatorContext context) inline static
Definition at line 710 of file TransUtils.cs.
References SolToBoogie.TransUtils.GetBoogieTypeFromSolidityTypeName(), SolToBoogie.TransUtils.GetCanonicalLocalVariableName(), BoogieAST.BoogieType.Int, SolidityAST.FunctionDefinition.Name, SolidityAST.VariableDeclaration.Name, SolidityAST.CallableDeclaration.Parameters, SolidityAST.ParameterList.Parameters, BoogieAST.BoogieType.Ref, SolidityAST.CallableDeclaration.ReturnParameters, SolidityAST.VariableDeclaration.TypeName, and SolidityAST.FunctionDefinition.Visibility.
Referenced by SolToBoogie.FallbackGenerator.CreateBodyOfUnknownFallback(), SolToBoogie.HarnessGenerator.GenerateBoogieHarnessForContract(), and SolToBoogie.HarnessGenerator.GenerateCorralChoiceProcForContract().
ComputeEventSignature()
static string SolToBoogie.TransUtils.ComputeEventSignature (EventDefinition eventDef) inline static
Definition at line 506 of file TransUtils.cs.
References SolidityAST.ParameterList.Length(), SolidityAST.EventDefinition.Name, SolidityAST.CallableDeclaration.Parameters, SolidityAST.ParameterList.Parameters, SolidityAST.VariableDeclaration.TypeDescriptions, and SolidityAST.TypeDescription.TypeString.
ComputeFunctionSignature()
static string SolToBoogie.TransUtils.ComputeFunctionSignature (FunctionDefinition funcDef) inline static
Definition at line 483 of file TransUtils.cs.
References SolToBoogie.TransUtils.InferTypeFromTypeString(), SolidityAST.ParameterList.Length(), SolidityAST.FunctionDefinition.Name, SolidityAST.CallableDeclaration.Parameters, SolidityAST.ParameterList.Parameters, SolidityAST.VariableDeclaration.TypeDescriptions, and SolidityAST.TypeDescription.TypeString.
Referenced by SolToBoogie.TranslatorContext.AddFunctionToContract(), SolToBoogie.TranslatorContext.GetFunctionBySignature(), and SolToBoogie.FunctionEventResolver.ResolveFunctions().
GenerateChoiceBlock()
static BoogieIfCmd SolToBoogie.TransUtils.GenerateChoiceBlock (List< ContractDefinition > contracts, TranslatorContext context, Tuple< string, string > callBackTarget = null) inline static
generate a non-deterministic choice block to call every public visible functions except constructors
Parameters
contracts
context
callBackTarget If non-null, this will be the msg.sender for calling back into the contracts
Returns
Definition at line 781 of file TransUtils.cs.
References SolToBoogie.TransUtils.GetCanonicalFunctionName(), SolToBoogie.TransUtils.GetCanonicalLocalVariableName(), SolidityAST.FunctionDefinition.IsConstructor, SolidityAST.FunctionDefinition.IsFallback, BoogieAST.BoogieStmtList.MakeSingletonStmtList(), SolidityAST.FunctionDefinition.Name, SolidityAST.VariableDeclaration.Name, SolidityAST.CallableDeclaration.Parameters, SolidityAST.ParameterList.Parameters, SolidityAST.CallableDeclaration.ReturnParameters, SolToBoogie.TranslatorContext.TX_GAS_COST, SolidityAST.VariableDeclaration.TypeName, and SolidityAST.FunctionDefinition.Visibility.
Referenced by SolToBoogie.FallbackGenerator.CreateBodyOfUnknownFallback(), SolToBoogie.HarnessGenerator.GenerateCorralChoiceProcForContract(), and SolToBoogie.HarnessGenerator.GenerateWhileLoop().
GenerateSourceInfoAnnotation()
static Tuple<string, int> SolToBoogie.TransUtils.GenerateSourceInfoAnnotation (ASTNode node, TranslatorContext context) inline static
Definition at line 682 of file TransUtils.cs.
References SolToBoogie.TranslatorContext.GetAbsoluteSourcePathOfASTNode(), and SolToBoogie.TranslatorContext.GetLineNumberOfASTNode().
Referenced by SolToBoogie.ProcedureTranslator.InstrumentSourceFileAndLineInfo().
GetBoogieTypeFromSolidityTypeName()
static BoogieType SolToBoogie.TransUtils.GetBoogieTypeFromSolidityTypeName (TypeName type) inline static
Definition at line 282 of file TransUtils.cs.
References BoogieAST.BoogieType.Bool, BoogieAST.BoogieType.Int, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.TransUtils.CollectLocalVars(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForArray(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForMapping(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateStructConstructors(), SolToBoogie.HarnessGenerator.GetParamsOfFunction(), SolToBoogie.ProcedureTranslator.TranslateStateVarDeclaration(), SolToBoogie.ProcedureTranslator.TranslateStructDefinition(), SolToBoogie.ModifierCollector.Visit(), and SolToBoogie.ProcedureTranslator.Visit().
GetCanonicalConstructorName()
static string SolToBoogie.TransUtils.GetCanonicalConstructorName (ContractDefinition contract) inline static
Definition at line 465 of file TransUtils.cs.
References SolidityAST.ContractDefinition.Name.
Referenced by SolToBoogie.HarnessGenerator.GenerateConstructorCall(), SolToBoogie.ProcedureTranslator.GenerateConstructorWithBaseCalls(), SolToBoogie.ProcedureTranslator.GenerateDefaultConstructor(), SolToBoogie.RevertLogicGenerator.RevertLogicGenerator(), and SolToBoogie.ProcedureTranslator.TranslateNewStatement().
GetCanonicalFunctionName()
static string SolToBoogie.TransUtils.GetCanonicalFunctionName (FunctionDefinition funcDef, TranslatorContext context) inline static
Definition at line 459 of file TransUtils.cs.
References SolToBoogie.TranslatorContext.GetContractByFunction(), SolidityAST.ContractDefinition.Name, and SolidityAST.FunctionDefinition.Name.
Referenced by SolToBoogie.FallbackGenerator.GenerateBodyOfFallbackDispatch(), SolToBoogie.TransUtils.GenerateChoiceBlock(), SolToBoogie.FunctionEventResolver.PrintVisibleFunctions(), SolToBoogie.ProcedureTranslator.TranslateDynamicDispatchCall(), and SolToBoogie.ProcedureTranslator.TranslateUsingLibraryCall().
GetCanonicalLocalVariableName()
static string SolToBoogie.TransUtils.GetCanonicalLocalVariableName (VariableDeclaration varDecl, TranslatorContext context) inline static
Definition at line 444 of file TransUtils.cs.
References SolidityAST.VariableDeclaration.Name, SolToBoogie.TranslatorFlags.RemoveScopeInVarName, SolidityAST.Declaration.Scope, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.TransUtils.CollectLocalVars(), SolToBoogie.TransUtils.GenerateChoiceBlock(), SolToBoogie.HarnessGenerator.GenerateConstructorCall(), SolToBoogie.TransUtils.GetCanonicalVariableName(), SolToBoogie.HarnessGenerator.GetParamsOfFunction(), SolToBoogie.ModifierCollector.Visit(), and SolToBoogie.ProcedureTranslator.Visit().
GetCanonicalStateVariableName()
static string SolToBoogie.TransUtils.GetCanonicalStateVariableName (VariableDeclaration varDecl, TranslatorContext context) inline static
Definition at line 450 of file TransUtils.cs.
References SolidityAST.VariableDeclaration.Name, SolidityAST.VariableDeclaration.StateVariable, and SolToBoogie.TranslatorContext.StateVarToContractMap.
Referenced by SolToBoogie.ProcedureTranslator.CreateDistinctArrayMappingAddress(), SolToBoogie.ProcedureTranslator.GenerateInitializationForElementaryTypes(), SolToBoogie.ProcedureTranslator.GenerateInitializationForStructStateVar(), SolToBoogie.HoudiniHelper.GetBoogieExprOfStateVar(), SolToBoogie.ProcedureTranslator.GetBoogieTypesFromMapping(), SolToBoogie.TransUtils.GetCanonicalVariableName(), SolToBoogie.ProcedureTranslator.InitializeNestedArrayMappingStateVar(), SolToBoogie.ProcedureTranslator.TranslateDynamicDispatchCall(), SolToBoogie.ProcedureTranslator.TranslateStateVarDeclaration(), and SolToBoogie.ProcedureTranslator.Visit().
GetCanonicalVariableName()
static string SolToBoogie.TransUtils.GetCanonicalVariableName (VariableDeclaration varDecl, TranslatorContext context) inline static
Definition at line 439 of file TransUtils.cs.
References SolToBoogie.TransUtils.GetCanonicalLocalVariableName(), SolToBoogie.TransUtils.GetCanonicalStateVariableName(), and SolidityAST.VariableDeclaration.StateVariable.
GetDefaultArguments()
static List<BoogieExpr> SolToBoogie.TransUtils.GetDefaultArguments () inline static
Definition at line 700 of file TransUtils.cs.
Referenced by SolToBoogie.ProcedureTranslator.TranslateInternalFunctionCall(), and SolToBoogie.ProcedureTranslator.Visit().
GetDefaultInParams()
static List<BoogieVariable> SolToBoogie.TransUtils.GetDefaultInParams () inline static
Definition at line 687 of file TransUtils.cs.
References BoogieAST.BoogieType.Int, and BoogieAST.BoogieType.Ref.
Referenced by SolToBoogie.ProcedureTranslator.GenerateDefaultConstructor(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateStructConstructors(), SolToBoogie.ProcedureTranslator.Visit(), and SolToBoogie.ModifierCollector.Visit().
GetEnumValueIndex()
static int SolToBoogie.TransUtils.GetEnumValueIndex (EnumDefinition enumDef, string value) inline static
Definition at line 470 of file TransUtils.cs.
References SolidityAST.EnumDefinition.Members.
Referenced by SolToBoogie.ProcedureTranslator.Visit().
GetFuncNameFromFuncCall()
static string SolToBoogie.TransUtils.GetFuncNameFromFuncCall (FunctionCall node) inline static
Definition at line 636 of file TransUtils.cs.
References SolidityAST.FunctionCall.Expression, and SolToBoogie.TransUtils.GetFuncNameFromFuncCallExpr().
Referenced by SolToBoogie.TransUtils.GetFuncNameFromFuncCallExpr(), SolToBoogie.TransUtils.InferFunctionSignature(), SolToBoogie.ProcedureTranslator.IsDynamicArrayPush(), SolToBoogie.ProcedureTranslator.TranslateInternalFunctionCall(), and SolToBoogie.ProcedureTranslator.Visit().
GetFuncNameFromFuncCallExpr()
static string SolToBoogie.TransUtils.GetFuncNameFromFuncCallExpr (Expression expr) inline static
Definition at line 655 of file TransUtils.cs.
References SolToBoogie.TransUtils.GetFuncNameFromFuncCall().
Referenced by SolToBoogie.TransUtils.GetFuncNameFromFuncCall().
havocGas() [1/2]
static void SolToBoogie.TransUtils.havocGas (BoogieStmtList list) inline static
Definition at line 865 of file TransUtils.cs.
References BoogieAST.BoogieStmtList.AddStatement().
Referenced by SolToBoogie.HarnessGenerator.GenerateHavocBlock().
havocGas() [2/2]
static void SolToBoogie.TransUtils.havocGas (List< BoogieCmd > list) inline static
Definition at line 872 of file TransUtils.cs.
References SolToBoogie.TranslatorContext.MAX_GAS_LIMIT, and SolToBoogie.TranslatorContext.MIN_GAS_LIMIT.
InferFunctionSignature()
static string SolToBoogie.TransUtils.InferFunctionSignature (TranslatorContext context, FunctionCall node) inline static
Definition at line 528 of file TransUtils.cs.
References SolidityAST.FunctionCall.Arguments, SolidityAST.FunctionCall.Expression, SolToBoogie.TranslatorContext.GetASTNodeById(), SolToBoogie.TransUtils.GetFuncNameFromFuncCall(), SolToBoogie.TransUtils.InferTypeFromTypeString(), SolidityAST.VariableDeclaration.TypeDescriptions, SolidityAST.Expression.TypeDescriptions, and SolidityAST.TypeDescription.TypeString.
Referenced by SolToBoogie.ProcedureTranslator.TranslateDynamicDispatchCall(), and SolToBoogie.ProcedureTranslator.TranslateUsingLibraryCall().
InferTypeFromExpression()
static string SolToBoogie.TransUtils.InferTypeFromExpression (Expression expression) inline static
Definition at line 610 of file TransUtils.cs.
References SolidityAST.Expression.TypeDescriptions, and SolidityAST.TypeDescription.TypeString.
InferTypeFromTypeString()
static string SolToBoogie.TransUtils.InferTypeFromTypeString (string typestr) inline static private
Definition at line 570 of file TransUtils.cs.
Referenced by SolToBoogie.TransUtils.ComputeFunctionSignature(), and SolToBoogie.TransUtils.InferFunctionSignature().
The documentation for this class was generated from the following file:
Sources/SolToBoogie/TransUtils.cs