VeriSol: SolToBoogie.ModSetAnalysis Class Reference
SolToBoogie.ModSetAnalysis Class Reference
Public Member Functions
ModSetAnalysis (TranslatorContext context)
void PerformModSetAnalysis ()
Private Member Functions
BoogieIdentifierExpr findOutermostIdentifierExpr (BoogieMapSelect select)
void calculateFlattenCmdLists (List< BoogieImplementation > impls)
void collectBoogieCmds (BoogieCmd cmd, List< BoogieCmd > cmds)
Private Attributes
TranslatorContext context
Dictionary< string, HashSet< BoogieGlobalVariable > > modSets = new Dictionary<string, HashSet<BoogieGlobalVariable>>()
Dictionary< string, List< BoogieCmd > > flattenedCmdLists = new Dictionary<string, List<BoogieCmd>>()
Detailed Description
Definition at line 10 of file ModSetAnalysis.cs.
Constructor & Destructor Documentation
ModSetAnalysis()
SolToBoogie.ModSetAnalysis.ModSetAnalysis (TranslatorContext context) inline
Definition at line 18 of file ModSetAnalysis.cs.
References SolToBoogie.ModSetAnalysis.context.
Member Function Documentation
calculateFlattenCmdLists()
void SolToBoogie.ModSetAnalysis.calculateFlattenCmdLists (List< BoogieImplementation > impls) inline private
Definition at line 136 of file ModSetAnalysis.cs.
References SolToBoogie.ModSetAnalysis.collectBoogieCmds(), and SolToBoogie.ModSetAnalysis.flattenedCmdLists.
Referenced by SolToBoogie.ModSetAnalysis.PerformModSetAnalysis().
collectBoogieCmds()
void SolToBoogie.ModSetAnalysis.collectBoogieCmds (BoogieCmd cmd, List< BoogieCmd > cmds) inline private
Definition at line 149 of file ModSetAnalysis.cs.
Referenced by SolToBoogie.ModSetAnalysis.calculateFlattenCmdLists().
findOutermostIdentifierExpr()
BoogieIdentifierExpr SolToBoogie.ModSetAnalysis.findOutermostIdentifierExpr (BoogieMapSelect select) inline private
Definition at line 128 of file ModSetAnalysis.cs.
References BoogieAST.BoogieMapSelect.BaseExpr.
Referenced by SolToBoogie.ModSetAnalysis.PerformModSetAnalysis().
PerformModSetAnalysis()
void SolToBoogie.ModSetAnalysis.PerformModSetAnalysis () inline
Definition at line 23 of file ModSetAnalysis.cs.
References SolToBoogie.ModSetAnalysis.calculateFlattenCmdLists(), BoogieAST.BoogieCallCmd.Callee, SolToBoogie.ModSetAnalysis.context, SolToBoogie.ModSetAnalysis.findOutermostIdentifierExpr(), SolToBoogie.ModSetAnalysis.flattenedCmdLists, SolToBoogie.ModSetAnalysis.modSets, BoogieAST.BoogieNamedDecl.Name, BoogieAST.BoogieIdentifierExpr.Name, and SolToBoogie.TranslatorContext.Program.
Referenced by SolToBoogie.BoogieTranslator.Translate().
Member Data Documentation
context
TranslatorContext SolToBoogie.ModSetAnalysis.context private
Definition at line 12 of file ModSetAnalysis.cs.
Referenced by SolToBoogie.ModSetAnalysis.ModSetAnalysis(), and SolToBoogie.ModSetAnalysis.PerformModSetAnalysis().
flattenedCmdLists
Dictionary<string, List<BoogieCmd> > SolToBoogie.ModSetAnalysis.flattenedCmdLists = new Dictionary<string, List<BoogieCmd>>() private
Definition at line 16 of file ModSetAnalysis.cs.
Referenced by SolToBoogie.ModSetAnalysis.calculateFlattenCmdLists(), and SolToBoogie.ModSetAnalysis.PerformModSetAnalysis().
modSets
Dictionary<string, HashSet<BoogieGlobalVariable> > SolToBoogie.ModSetAnalysis.modSets = new Dictionary<string, HashSet<BoogieGlobalVariable>>() private
Definition at line 14 of file ModSetAnalysis.cs.
Referenced by SolToBoogie.ModSetAnalysis.PerformModSetAnalysis().
The documentation for this class was generated from the following file:
Sources/SolToBoogie/ModSetAnalysis.cs