VeriSol: SolidityAST.SolidityCompiler Class Reference
SolidityAST.SolidityCompiler Class Reference
Public Member Functions
CompilerOutput Compile (string solcPath, string derivedFilePath)
Private Member Functions
string RunSolc (string solcPath, string derivedFilePath)
Static Private Attributes
static int solcTimeoutInMilliseconds = TimeSpan.FromSeconds(5).Seconds * 1000
Detailed Description
Definition at line 11 of file SolidityCompiler.cs.
Member Function Documentation
Compile()
CompilerOutput SolidityAST.SolidityCompiler.Compile (string solcPath, string derivedFilePath) inline
Definition at line 15 of file SolidityCompiler.cs.
References SolidityAST.SolidityCompiler.RunSolc().
Referenced by SolidityAST.RegressionExecutor.Execute(), SolToBoogieTest.RegressionExecutor.Execute(), VeriSolRunner.VeriSolExecutor.ExecuteSolToBoogie(), SolidityAST.TestMain.LegacyMain(), and SolidityCFG.TestMain.Main().
RunSolc()
string SolidityAST.SolidityCompiler.RunSolc (string solcPath, string derivedFilePath) inline private
Parameters
solcPath
derivedFilePath Path to the top-level solidty file
Returns
Definition at line 49 of file SolidityCompiler.cs.
References SolidityAST.SolidityCompiler.solcTimeoutInMilliseconds.
Referenced by SolidityAST.SolidityCompiler.Compile().
Member Data Documentation
solcTimeoutInMilliseconds
int SolidityAST.SolidityCompiler.solcTimeoutInMilliseconds = TimeSpan.FromSeconds(5).Seconds * 1000 static private
Definition at line 13 of file SolidityCompiler.cs.
Referenced by SolidityAST.SolidityCompiler.RunSolc().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityCompiler.cs