VeriSol: SolidityAST.Assignment Class Reference
SolidityAST.Assignment Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
Expression LeftHandSide [get, set]
string Operator [get, set]
Expression RightHandSide [get, set]
Properties inherited from SolidityAST.Expression
List< TypeDescription > ArgumentTypes [get, set]
bool IsConstant [get, set]
bool IsPure [get, set]
bool IsLValue [get, set]
bool LValueRequested [get, set]
TypeDescription TypeDescriptions [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 1572 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.Assignment.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1580 of file SolidityAST.cs.
References SolidityAST.ASTNode.Accept(), SolidityAST.IASTVisitor.EndVisit(), SolidityAST.Assignment.LeftHandSide, SolidityAST.Assignment.RightHandSide, and SolidityAST.IASTVisitor.Visit().
Referenced by SolToBoogie.ProcedureTranslator.Visit().
Accept< T >()
override T SolidityAST.Assignment.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1590 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.Assignment.ToString () inline
Definition at line 1595 of file SolidityAST.cs.
References SolidityAST.Assignment.LeftHandSide, SolidityAST.Assignment.Operator, and SolidityAST.Assignment.RightHandSide.
Property Documentation
LeftHandSide
Expression SolidityAST.Assignment.LeftHandSide get set
Definition at line 1574 of file SolidityAST.cs.
Referenced by SolidityAST.Assignment.Accept(), SolidityAST.Assignment.ToString(), and SolToBoogie.ProcedureTranslator.Visit().
Operator
string SolidityAST.Assignment.Operator get set
Definition at line 1576 of file SolidityAST.cs.
Referenced by SolidityAST.Assignment.ToString(), and SolToBoogie.ProcedureTranslator.Visit().
RightHandSide
Expression SolidityAST.Assignment.RightHandSide get set
Definition at line 1578 of file SolidityAST.cs.
Referenced by SolidityAST.Assignment.Accept(), SolidityAST.Assignment.ToString(), and SolToBoogie.ProcedureTranslator.Visit().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs