VeriSol: VeriSolRunner.ExternalTools.ExternalToolsManager Class Reference
VeriSolRunner.ExternalTools.ExternalToolsManager Class Reference
Static Public Member Functions
static void EnsureAllExisted ()
Static Package Functions
static void Log (string v)
Properties
static ToolManager Solc [get, private set]
static ToolManager Z3 [get, private set]
static ToolManager Boogie [get, private set]
static ToolManager Corral [get, private set]
Static Private Member Functions
static ExternalToolsManager ()
Static Private Attributes
static ILogger logger
Detailed Description
Definition at line 8 of file ExternalToolsManager.cs.
Constructor & Destructor Documentation
ExternalToolsManager()
static VeriSolRunner.ExternalTools.ExternalToolsManager.ExternalToolsManager () inline static private
Definition at line 17 of file ExternalToolsManager.cs.
References VeriSolRunner.ExternalTools.ExternalToolsManager.Boogie, VeriSolRunner.ExternalTools.ExternalToolsManager.Corral, VeriSolRunner.ExternalTools.ExternalToolsManager.logger, VeriSolRunner.ExternalTools.ExternalToolsManager.Solc, and VeriSolRunner.ExternalTools.ExternalToolsManager.Z3.
Member Function Documentation
EnsureAllExisted()
static void VeriSolRunner.ExternalTools.ExternalToolsManager.EnsureAllExisted () inline static
Definition at line 48 of file ExternalToolsManager.cs.
References VeriSolRunner.ExternalTools.ExternalToolsManager.Boogie, VeriSolRunner.ExternalTools.ExternalToolsManager.Corral, VeriSolRunner.ExternalTools.ToolManager.EnsureExisted(), VeriSolRunner.ExternalTools.ExternalToolsManager.Solc, and VeriSolRunner.ExternalTools.ExternalToolsManager.Z3.
Referenced by SolToBoogieTest.Program.Main(), and VeriSolRunner.Program.Main().
Log()
static void VeriSolRunner.ExternalTools.ExternalToolsManager.Log (string v) inline static package
Definition at line 43 of file ExternalToolsManager.cs.
References VeriSolRunner.ExternalTools.ExternalToolsManager.logger.
Referenced by VeriSolRunner.ExternalTools.DownloadedToolManager.CopyToCommand(), VeriSolRunner.ExternalTools.DownloadedToolManager.Download(), VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadAndCopy(), VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadAndUnZip(), VeriSolRunner.ExternalTools.DotnetCliToolManager.EnsureExisted(), VeriSolRunner.ExternalTools.DownloadedToolManager.EnsureExisted(), VeriSolRunner.ExternalTools.DotnetCliToolManager.EnsureLinkedToZ3(), VeriSolRunner.ExternalTools.DotnetCliToolManager.InstallDotnetCliTool(), VeriSolRunner.ExternalTools.DownloadedToolManager.PrepareTempDirectory(), and VeriSolRunner.ExternalTools.DownloadedToolManager.RunCmd().
Member Data Documentation
logger
ILogger VeriSolRunner.ExternalTools.ExternalToolsManager.logger static private
Definition at line 10 of file ExternalToolsManager.cs.
Referenced by VeriSolRunner.ExternalTools.ExternalToolsManager.ExternalToolsManager(), and VeriSolRunner.ExternalTools.ExternalToolsManager.Log().
Property Documentation
Boogie
ToolManager VeriSolRunner.ExternalTools.ExternalToolsManager.Boogie static get private set
Definition at line 14 of file ExternalToolsManager.cs.
Referenced by VeriSolRunner.ExternalTools.ExternalToolsManager.EnsureAllExisted(), VeriSolRunner.ExternalTools.ExternalToolsManager.ExternalToolsManager(), and VeriSolRunner.VeriSolExecutor.VeriSolExecutor().
Corral
ToolManager VeriSolRunner.ExternalTools.ExternalToolsManager.Corral static get private set
Definition at line 15 of file ExternalToolsManager.cs.
Referenced by VeriSolRunner.ExternalTools.ExternalToolsManager.EnsureAllExisted(), VeriSolRunner.ExternalTools.ExternalToolsManager.ExternalToolsManager(), SolToBoogieTest.RegressionExecutor.RegressionExecutor(), and VeriSolRunner.VeriSolExecutor.VeriSolExecutor().
Solc
ToolManager VeriSolRunner.ExternalTools.ExternalToolsManager.Solc static get private set
Definition at line 12 of file ExternalToolsManager.cs.
Referenced by VeriSolRunner.ExternalTools.ExternalToolsManager.EnsureAllExisted(), VeriSolRunner.ExternalTools.ExternalToolsManager.ExternalToolsManager(), SolToBoogieTest.RegressionExecutor.RegressionExecutor(), and VeriSolRunner.VeriSolExecutor.VeriSolExecutor().
Z3
ToolManager VeriSolRunner.ExternalTools.ExternalToolsManager.Z3 static get private set
Definition at line 13 of file ExternalToolsManager.cs.
Referenced by VeriSolRunner.ExternalTools.ExternalToolsManager.EnsureAllExisted(), and VeriSolRunner.ExternalTools.ExternalToolsManager.ExternalToolsManager().
The documentation for this class was generated from the following file:
Sources/ExternalToolsManager/ExternalToolsManager.cs