VeriSol: SolidityAST.RegressionExecutor Class Reference
SolidityAST.RegressionExecutor Class Reference
Public Member Functions
RegressionExecutor (string solcPath, string testDirectory, ILogger logger)
bool BatchExecute ()
bool Execute (string filename)
Private Member Functions
bool TextCompare (string originalText, string astText)
string ConcatStringArray (string[] array, string delim)
string[] NormalizeKeywords (string[] words)
Private Attributes
string solcPath
string testDirectory
ILogger logger
Detailed Description
Definition at line 12 of file RegressionExecutor.cs.
Constructor & Destructor Documentation
RegressionExecutor()
SolidityAST.RegressionExecutor.RegressionExecutor (string solcPath, string testDirectory, ILogger logger) inline
Definition at line 20 of file RegressionExecutor.cs.
References SolidityAST.RegressionExecutor.logger, SolidityAST.RegressionExecutor.solcPath, and SolidityAST.RegressionExecutor.testDirectory.
Member Function Documentation
BatchExecute()
bool SolidityAST.RegressionExecutor.BatchExecute () inline
Definition at line 27 of file RegressionExecutor.cs.
References SolidityAST.RegressionExecutor.Execute(), SolidityAST.RegressionExecutor.logger, and SolidityAST.RegressionExecutor.testDirectory.
Referenced by SolidityAST.TestMain.Main(), and SolToBoogieTest.Program.Main().
ConcatStringArray()
string SolidityAST.RegressionExecutor.ConcatStringArray (string[] array, string delim) inline private
Definition at line 123 of file RegressionExecutor.cs.
Execute()
bool SolidityAST.RegressionExecutor.Execute (string filename) inline
Definition at line 64 of file RegressionExecutor.cs.
References SolidityAST.SolidityCompiler.Compile(), SolidityAST.AST.GetSourceUnits(), SolidityAST.RegressionExecutor.solcPath, SolidityAST.RegressionExecutor.testDirectory, and SolidityAST.RegressionExecutor.TextCompare().
Referenced by SolidityAST.RegressionExecutor.BatchExecute(), and SolToBoogieTest.RegressionExecutor.BatchExecute().
NormalizeKeywords()
string [] SolidityAST.RegressionExecutor.NormalizeKeywords (string[] words) inline private
Definition at line 145 of file RegressionExecutor.cs.
Referenced by SolidityAST.RegressionExecutor.TextCompare().
TextCompare()
bool SolidityAST.RegressionExecutor.TextCompare (string originalText, string astText) inline private
Definition at line 80 of file RegressionExecutor.cs.
References SolidityAST.RegressionExecutor.logger, and SolidityAST.RegressionExecutor.NormalizeKeywords().
Referenced by SolidityAST.RegressionExecutor.Execute().
Member Data Documentation
logger
ILogger SolidityAST.RegressionExecutor.logger private
Definition at line 18 of file RegressionExecutor.cs.
Referenced by SolidityAST.RegressionExecutor.BatchExecute(), SolToBoogieTest.RegressionExecutor.BatchExecute(), SolToBoogieTest.RegressionExecutor.ParseTranslatorFlags(), SolidityAST.RegressionExecutor.RegressionExecutor(), SolToBoogieTest.RegressionExecutor.RegressionExecutor(), and SolidityAST.RegressionExecutor.TextCompare().
solcPath
string SolidityAST.RegressionExecutor.solcPath private
Definition at line 14 of file RegressionExecutor.cs.
Referenced by SolidityAST.RegressionExecutor.Execute(), SolToBoogieTest.RegressionExecutor.Execute(), and SolidityAST.RegressionExecutor.RegressionExecutor().
testDirectory
string SolidityAST.RegressionExecutor.testDirectory private
Definition at line 16 of file RegressionExecutor.cs.
Referenced by SolidityAST.RegressionExecutor.BatchExecute(), SolToBoogieTest.RegressionExecutor.BatchExecute(), SolidityAST.RegressionExecutor.Execute(), SolToBoogieTest.RegressionExecutor.Execute(), SolidityAST.RegressionExecutor.RegressionExecutor(), and SolToBoogieTest.RegressionExecutor.RegressionExecutor().
The documentation for this class was generated from the following file:
Sources/SolidityAST/RegressionExecutor.cs