VeriSol: SolidityAST.ASTNode Class Reference
SolidityAST.ASTNode Class Reference abstract
Public Member Functions
abstract void Accept (IASTVisitor visitor)
abstract T Accept< T > (IASTGenericVisitor< T > visitor)
Properties
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 160 of file SolidityAST.cs.
Member Function Documentation
Accept()
abstract void SolidityAST.ASTNode.Accept (IASTVisitor visitor) pure virtual
Implemented in SolidityAST.IndexAccess, SolidityAST.MemberAccess, SolidityAST.NewExpression, SolidityAST.FunctionCall, SolidityAST.TupleExpression, SolidityAST.Assignment, SolidityAST.Conditional, SolidityAST.BinaryOperation, SolidityAST.UnaryOperation, SolidityAST.ElementaryTypeNameExpression, SolidityAST.Identifier, SolidityAST.Literal, SolidityAST.ExpressionStatement, SolidityAST.InlineAssembly, SolidityAST.VariableDeclarationStatement, SolidityAST.EmitStatement, SolidityAST.Throw, SolidityAST.Return, SolidityAST.Break, SolidityAST.Continue, SolidityAST.ForStatement, SolidityAST.DoWhileStatement, SolidityAST.WhileStatement, SolidityAST.IfStatement, SolidityAST.PlaceholderStatement, SolidityAST.Block, SolidityAST.ArrayTypeName, SolidityAST.Mapping, SolidityAST.UserDefinedTypeName, SolidityAST.ElementaryTypeName, SolidityAST.VariableDeclaration, SolidityAST.EnumValue, SolidityAST.EnumDefinition, SolidityAST.StructDefinition, SolidityAST.EventDefinition, SolidityAST.ModifierInvocation, SolidityAST.ModifierDefinition, SolidityAST.ParameterList, SolidityAST.FunctionDefinition, SolidityAST.InheritanceSpecifier, SolidityAST.ContractDefinition, SolidityAST.ImportDirective, SolidityAST.UsingForDirective, SolidityAST.PragmaDirective, SolidityAST.SourceUnit, and SolidityAST.SourceUnitList.
Referenced by SolidityAST.UsingForDirective.Accept(), SolidityAST.VariableDeclaration.Accept(), SolidityAST.Mapping.Accept(), SolidityAST.ArrayTypeName.Accept(), SolidityAST.IfStatement.Accept(), SolidityAST.WhileStatement.Accept(), SolidityAST.DoWhileStatement.Accept(), SolidityAST.ForStatement.Accept(), SolidityAST.Return.Accept(), SolidityAST.VariableDeclarationStatement.Accept(), SolidityAST.ExpressionStatement.Accept(), SolidityAST.UnaryOperation.Accept(), SolidityAST.BinaryOperation.Accept(), SolidityAST.Conditional.Accept(), SolidityAST.Assignment.Accept(), SolidityAST.FunctionCall.Accept(), SolidityAST.NewExpression.Accept(), SolidityAST.MemberAccess.Accept(), SolidityAST.IndexAccess.Accept(), SolidityAST.Utils.AcceptList< T >(), SolidityCFG.CFGBuilder.AppendControlFlow(), SolidityAST.NodeMapper.NodeMapper(), SolToBoogie.ProcedureTranslator.TranslateExpr(), SolToBoogie.ProcedureTranslator.TranslateStatement(), SolidityCFG.CFGBuilder.Visit(), and SolToBoogie.ProcedureTranslator.Visit().
Accept< T >()
abstract T SolidityAST.ASTNode.Accept< T > (IASTGenericVisitor< T > visitor) pure virtual
Implemented in SolidityAST.IndexAccess, SolidityAST.MemberAccess, SolidityAST.NewExpression, SolidityAST.FunctionCall, SolidityAST.TupleExpression, SolidityAST.Assignment, SolidityAST.Conditional, SolidityAST.BinaryOperation, SolidityAST.UnaryOperation, SolidityAST.ElementaryTypeNameExpression, SolidityAST.Identifier, SolidityAST.Literal, SolidityAST.ExpressionStatement, SolidityAST.InlineAssembly, SolidityAST.VariableDeclarationStatement, SolidityAST.EmitStatement, SolidityAST.Throw, SolidityAST.Return, SolidityAST.Break, SolidityAST.Continue, SolidityAST.ForStatement, SolidityAST.DoWhileStatement, SolidityAST.WhileStatement, SolidityAST.IfStatement, SolidityAST.PlaceholderStatement, SolidityAST.Block, SolidityAST.ArrayTypeName, SolidityAST.Mapping, SolidityAST.UserDefinedTypeName, SolidityAST.ElementaryTypeName, SolidityAST.VariableDeclaration, SolidityAST.EnumValue, SolidityAST.EnumDefinition, SolidityAST.StructDefinition, SolidityAST.EventDefinition, SolidityAST.ModifierInvocation, SolidityAST.ModifierDefinition, SolidityAST.ParameterList, SolidityAST.FunctionDefinition, SolidityAST.InheritanceSpecifier, SolidityAST.ContractDefinition, SolidityAST.ImportDirective, SolidityAST.UsingForDirective, SolidityAST.PragmaDirective, SolidityAST.SourceUnit, and SolidityAST.SourceUnitList.
Property Documentation
GasCost
int SolidityAST.ASTNode.GasCost get set
Definition at line 164 of file SolidityAST.cs.
Referenced by SolToBoogie.ProcedureTranslator.preTranslationAction().
Id
int SolidityAST.ASTNode.Id get set
Definition at line 162 of file SolidityAST.cs.
Referenced by SolidityAST.NodeMapper.CommonVisit(), SolidityAST.SourceUnitList.SourceUnitList(), SolToBoogie.ProcedureTranslator.TranslateDynamicDispatchCall(), and SolToBoogie.ProcedureTranslator.Visit().
NodeType
string SolidityAST.ASTNode.NodeType get set
Definition at line 166 of file SolidityAST.cs.
Referenced by SolidityAST.SourceUnitList.SourceUnitList().
Src
string SolidityAST.ASTNode.Src get set
Definition at line 168 of file SolidityAST.cs.
Referenced by SolToBoogie.SourceInfoCollector.CommonEndVisit(), and SolidityAST.SourceUnitList.SourceUnitList().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs