VeriSol: SolToBoogie.RevertLogicGenerator Class Reference
SolToBoogie.RevertLogicGenerator Class Reference
Public Member Functions
RevertLogicGenerator (TranslatorContext context)
void Generate ()
Private Member Functions
bool mustHaveShadow (string globalName)
bool isPublic (BoogieProcedure proc)
BoogieProcedure duplicateProcedure (BoogieProcedure proc, string newNameSuffix, bool dropPublic=false)
BoogieExpr dupAndReplaceExpr (BoogieExpr expr, bool isFail, bool inHarness)
bool catchesExceptions (string methodName)
void generateRevertLogicForCmd (BoogieCmd cmd, BoogieStmtList parent, bool isFail, bool inHarness)
BoogieImplementation createFailImplementation (string name, BoogieImplementation originalImpl)
bool isHarnessProcudure (string procName)
BoogieImplementation createSuccessImplementation (string name, BoogieImplementation originalImpl)
bool isConstructor (string funcName)
BoogieImplementation CreateSendFail ()
BoogieImplementation CreateSendSucess ()
Private Attributes
TranslatorContext context
HashSet< string > constructorNames
Dictionary< string, BoogieGlobalVariable > shadowGlobals = new Dictionary<string, BoogieGlobalVariable>()
Dictionary< string, BoogieImplementation >.KeyCollection procsWiltImplNames
Dictionary< string, BoogieProcedure > proceduresInProgram
Detailed Description
Definition at line 9 of file RevertLogicGenerator.cs.
Constructor & Destructor Documentation
RevertLogicGenerator()
SolToBoogie.RevertLogicGenerator.RevertLogicGenerator (TranslatorContext context) inline
Definition at line 259 of file RevertLogicGenerator.cs.
References SolToBoogie.RevertLogicGenerator.context, SolToBoogie.TranslatorContext.ContractDefinitions, BoogieAST.BoogieProgram.Declarations, SolToBoogie.TransUtils.GetCanonicalConstructorName(), SolToBoogie.RevertLogicGenerator.proceduresInProgram, and SolToBoogie.TranslatorContext.Program.
Member Function Documentation
catchesExceptions()
bool SolToBoogie.RevertLogicGenerator.catchesExceptions (string methodName) inline private
Definition at line 132 of file RevertLogicGenerator.cs.
Referenced by SolToBoogie.RevertLogicGenerator.generateRevertLogicForCmd().
createFailImplementation()
BoogieImplementation SolToBoogie.RevertLogicGenerator.createFailImplementation (string name, BoogieImplementation originalImpl) inline private
Definition at line 228 of file RevertLogicGenerator.cs.
References SolToBoogie.RevertLogicGenerator.generateRevertLogicForCmd(), SolToBoogie.RevertLogicGenerator.isHarnessProcudure(), and BoogieAST.BoogieNamedDecl.Name.
Referenced by SolToBoogie.RevertLogicGenerator.Generate().
CreateSendFail()
BoogieImplementation SolToBoogie.RevertLogicGenerator.CreateSendFail () inline private
Definition at line 441 of file RevertLogicGenerator.cs.
References BoogieAST.BoogieType.Bool, SolToBoogie.RevertLogicGenerator.context, SolToBoogie.TranslatorFlags.InstrumentGas, BoogieAST.BoogieType.Int, BoogieAST.BoogieStmtList.MakeSingletonStmtList(), BoogieAST.BoogieType.Ref, SolToBoogie.RevertLogicGenerator.shadowGlobals, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.RevertLogicGenerator.Generate().
CreateSendSucess()
BoogieImplementation SolToBoogie.RevertLogicGenerator.CreateSendSucess () inline private
Definition at line 560 of file RevertLogicGenerator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), BoogieAST.BoogieType.Bool, SolToBoogie.RevertLogicGenerator.context, SolToBoogie.TranslatorFlags.InstrumentGas, BoogieAST.BoogieType.Int, BoogieAST.BoogieStmtList.MakeSingletonStmtList(), BoogieAST.BoogieType.Ref, SolToBoogie.RevertLogicGenerator.shadowGlobals, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.RevertLogicGenerator.Generate().
createSuccessImplementation()
BoogieImplementation SolToBoogie.RevertLogicGenerator.createSuccessImplementation (string name, BoogieImplementation originalImpl) inline private
Definition at line 247 of file RevertLogicGenerator.cs.
References SolToBoogie.RevertLogicGenerator.generateRevertLogicForCmd(), and SolToBoogie.RevertLogicGenerator.isHarnessProcudure().
Referenced by SolToBoogie.RevertLogicGenerator.Generate().
dupAndReplaceExpr()
BoogieExpr SolToBoogie.RevertLogicGenerator.dupAndReplaceExpr (BoogieExpr expr, bool isFail, bool inHarness) inline private
Definition at line 53 of file RevertLogicGenerator.cs.
References BoogieAST.BoogieMapSelect.Arguments, BoogieAST.BoogieMapUpdate.Arguments, BoogieAST.BoogieFuncCallExpr.Arguments, BoogieAST.BoogieTupleExpr.Arguments, BoogieAST.BoogieMapSelect.BaseExpr, BoogieAST.BoogieMapUpdate.BaseExpr, BoogieAST.BoogieQuantifiedExpr.BodyExpr, BoogieAST.BoogieITE.ElseExpr, BoogieAST.BoogieUnaryOperation.Expr, BoogieAST.BoogieFuncCallExpr.Function, BoogieAST.BoogieITE.Guard, BoogieAST.BoogieQuantifiedExpr.IsForall, BoogieAST.BoogieBinaryOperation.Lhs, BoogieAST.BoogieUnaryOperation.Op, BoogieAST.BoogieBinaryOperation.Op, BoogieAST.BoogieQuantifiedExpr.QVars, BoogieAST.BoogieQuantifiedExpr.QVarTypes, BoogieAST.BoogieBinaryOperation.Rhs, SolToBoogie.RevertLogicGenerator.shadowGlobals, BoogieAST.BoogieITE.ThenExpr, BoogieAST.BoogieQuantifiedExpr.Trigger, and BoogieAST.BoogieMapUpdate.Value.
Referenced by SolToBoogie.RevertLogicGenerator.generateRevertLogicForCmd().
duplicateProcedure()
BoogieProcedure SolToBoogie.RevertLogicGenerator.duplicateProcedure (BoogieProcedure proc, string newNameSuffix, bool dropPublic = false) inline private
Definition at line 40 of file RevertLogicGenerator.cs.
References BoogieAST.BoogieDeclaration.Attributes, BoogieAST.BoogieDeclWithFormals.InParams, BoogieAST.BoogieNamedDecl.Name, and BoogieAST.BoogieDeclWithFormals.OutParams.
Referenced by SolToBoogie.RevertLogicGenerator.Generate().
Generate()
void SolToBoogie.RevertLogicGenerator.Generate () inline
Definition at line 271 of file RevertLogicGenerator.cs.
References BoogieAST.BoogieProgram.AddDeclaration(), BoogieAST.BoogieStmtList.AddStatement(), BoogieAST.BoogieType.Bool, SolToBoogie.RevertLogicGenerator.context, SolToBoogie.RevertLogicGenerator.createFailImplementation(), SolToBoogie.RevertLogicGenerator.CreateSendFail(), SolToBoogie.RevertLogicGenerator.CreateSendSucess(), SolToBoogie.RevertLogicGenerator.createSuccessImplementation(), BoogieAST.BoogieProgram.Declarations, SolToBoogie.RevertLogicGenerator.duplicateProcedure(), BoogieAST.BoogieDeclWithFormals.InParams, SolToBoogie.TranslatorFlags.InstrumentGas, SolToBoogie.RevertLogicGenerator.isConstructor(), SolToBoogie.RevertLogicGenerator.isHarnessProcudure(), SolToBoogie.RevertLogicGenerator.isPublic(), BoogieAST.BoogieImplementation.LocalVars, SolToBoogie.RevertLogicGenerator.mustHaveShadow(), BoogieAST.BoogieNamedDecl.Name, BoogieAST.BoogieDeclWithFormals.OutParams, SolToBoogie.RevertLogicGenerator.proceduresInProgram, SolToBoogie.RevertLogicGenerator.procsWiltImplNames, SolToBoogie.TranslatorContext.Program, SolToBoogie.RevertLogicGenerator.shadowGlobals, BoogieAST.BoogieImplementation.StructuredStmts, and SolToBoogie.TranslatorContext.TranslateFlags.
Referenced by SolToBoogie.BoogieTranslator.Translate().
generateRevertLogicForCmd()
void SolToBoogie.RevertLogicGenerator.generateRevertLogicForCmd (BoogieCmd cmd, BoogieStmtList parent, bool isFail, bool inHarness) inline private
Definition at line 137 of file RevertLogicGenerator.cs.
References BoogieAST.BoogieStmtList.AddStatement(), BoogieAST.BoogieStmtList.BigBlocks, SolToBoogie.RevertLogicGenerator.catchesExceptions(), SolToBoogie.RevertLogicGenerator.dupAndReplaceExpr(), SolToBoogie.RevertLogicGenerator.isHarnessProcudure(), SolToBoogie.RevertLogicGenerator.isPublic(), SolToBoogie.RevertLogicGenerator.proceduresInProgram, and SolToBoogie.RevertLogicGenerator.procsWiltImplNames.
Referenced by SolToBoogie.RevertLogicGenerator.createFailImplementation(), and SolToBoogie.RevertLogicGenerator.createSuccessImplementation().
isConstructor()
bool SolToBoogie.RevertLogicGenerator.isConstructor (string funcName) inline private
Definition at line 266 of file RevertLogicGenerator.cs.
References SolToBoogie.RevertLogicGenerator.constructorNames.
Referenced by SolToBoogie.RevertLogicGenerator.Generate().
isHarnessProcudure()
bool SolToBoogie.RevertLogicGenerator.isHarnessProcudure (string procName) inline private
Definition at line 242 of file RevertLogicGenerator.cs.
Referenced by SolToBoogie.RevertLogicGenerator.createFailImplementation(), SolToBoogie.RevertLogicGenerator.createSuccessImplementation(), SolToBoogie.RevertLogicGenerator.Generate(), and SolToBoogie.RevertLogicGenerator.generateRevertLogicForCmd().
isPublic()
bool SolToBoogie.RevertLogicGenerator.isPublic (BoogieProcedure proc) inline private
Definition at line 26 of file RevertLogicGenerator.cs.
References BoogieAST.BoogieDeclaration.Attributes.
Referenced by SolToBoogie.RevertLogicGenerator.Generate(), and SolToBoogie.RevertLogicGenerator.generateRevertLogicForCmd().
mustHaveShadow()
bool SolToBoogie.RevertLogicGenerator.mustHaveShadow (string globalName) inline private
Definition at line 21 of file RevertLogicGenerator.cs.
Referenced by SolToBoogie.RevertLogicGenerator.Generate().
Member Data Documentation
constructorNames
HashSet<string> SolToBoogie.RevertLogicGenerator.constructorNames private
Definition at line 13 of file RevertLogicGenerator.cs.
Referenced by SolToBoogie.RevertLogicGenerator.isConstructor().
context
TranslatorContext SolToBoogie.RevertLogicGenerator.context private
Definition at line 11 of file RevertLogicGenerator.cs.
Referenced by SolToBoogie.RevertLogicGenerator.CreateSendFail(), SolToBoogie.RevertLogicGenerator.CreateSendSucess(), SolToBoogie.RevertLogicGenerator.Generate(), and SolToBoogie.RevertLogicGenerator.RevertLogicGenerator().
proceduresInProgram
Dictionary<string, BoogieProcedure> SolToBoogie.RevertLogicGenerator.proceduresInProgram private
Definition at line 19 of file RevertLogicGenerator.cs.
Referenced by SolToBoogie.RevertLogicGenerator.Generate(), SolToBoogie.RevertLogicGenerator.generateRevertLogicForCmd(), and SolToBoogie.RevertLogicGenerator.RevertLogicGenerator().
procsWiltImplNames
Dictionary<string, BoogieImplementation>.KeyCollection SolToBoogie.RevertLogicGenerator.procsWiltImplNames private
Definition at line 17 of file RevertLogicGenerator.cs.
Referenced by SolToBoogie.RevertLogicGenerator.Generate(), and SolToBoogie.RevertLogicGenerator.generateRevertLogicForCmd().
shadowGlobals
Dictionary<string, BoogieGlobalVariable> SolToBoogie.RevertLogicGenerator.shadowGlobals = new Dictionary<string, BoogieGlobalVariable>() private
Definition at line 15 of file RevertLogicGenerator.cs.
Referenced by SolToBoogie.RevertLogicGenerator.CreateSendFail(), SolToBoogie.RevertLogicGenerator.CreateSendSucess(), SolToBoogie.RevertLogicGenerator.dupAndReplaceExpr(), and SolToBoogie.RevertLogicGenerator.Generate().
The documentation for this class was generated from the following file:
Sources/SolToBoogie/RevertLogicGenerator.cs