VeriSol: SolidityAST.Block Class Reference
SolidityAST.Block Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
int Scope [get, set]
List< Statement > Statements [get, set]
Properties inherited from SolidityAST.Statement
string Documnetation [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 952 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.Block.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 958 of file SolidityAST.cs.
References SolidityAST.IASTVisitor.EndVisit(), SolidityAST.Block.Statements, and SolidityAST.IASTVisitor.Visit().
Referenced by SolidityAST.FunctionDefinition.Accept(), and SolidityAST.ModifierDefinition.Accept().
Accept< T >()
override T SolidityAST.Block.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 967 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.Block.ToString () inline
Definition at line 972 of file SolidityAST.cs.
References SolidityAST.Block.Statements.
Property Documentation
Scope
int SolidityAST.Block.Scope get set
Definition at line 954 of file SolidityAST.cs.
Referenced by SolToBoogie.SolidityDesugaring.CreateBlockFromTwoStatements().
Statements
List<Statement> SolidityAST.Block.Statements get set
Definition at line 956 of file SolidityAST.cs.
Referenced by SolidityAST.Block.Accept(), SolToBoogie.SolidityDesugaring.CreateBlockFromTwoStatements(), SolToBoogie.SolidityDesugaring.InsertStatementBeforeImpl(), and SolidityAST.Block.ToString().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs