VeriSol: SolidityAST.DoWhileStatement Class Reference
SolidityAST.DoWhileStatement Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
Expression Condition [get, set]
Statement Body [get, set]
Properties inherited from SolidityAST.Statement
string Documnetation [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 1070 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.DoWhileStatement.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1076 of file SolidityAST.cs.
References SolidityAST.ASTNode.Accept(), SolidityAST.DoWhileStatement.Body, SolidityAST.DoWhileStatement.Condition, SolidityAST.IASTVisitor.EndVisit(), and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.DoWhileStatement.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1086 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.DoWhileStatement.ToString () inline
Definition at line 1091 of file SolidityAST.cs.
References SolidityAST.DoWhileStatement.Body, and SolidityAST.DoWhileStatement.Condition.
Property Documentation
Body
Statement SolidityAST.DoWhileStatement.Body get set
Definition at line 1074 of file SolidityAST.cs.
Referenced by SolidityAST.DoWhileStatement.Accept(), SolidityAST.DoWhileStatement.ToString(), and SolToBoogie.ProcedureTranslator.Visit().
Condition
Expression SolidityAST.DoWhileStatement.Condition get set
Definition at line 1072 of file SolidityAST.cs.
Referenced by SolidityAST.DoWhileStatement.Accept(), SolidityAST.DoWhileStatement.ToString(), and SolToBoogie.ProcedureTranslator.Visit().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs