VeriSol: SolToBoogie.SolidityDesugaring Class Reference
SolToBoogie.SolidityDesugaring Class Reference
Public Member Functions
SolidityDesugaring (TranslatorContext context)
override bool Visit (ContractDefinition node)
override void EndVisit (ContractDefinition node)
override bool Visit (FunctionDefinition node)
override bool Visit (PlaceholderStatement node)
override bool Visit (IfStatement node)
override bool Visit (WhileStatement node)
override bool Visit (DoWhileStatement node)
override bool Visit (ForStatement node)
override bool Visit (Continue node)
override bool Visit (Break node)
override bool Visit (Return node)
override bool Visit (Throw node)
override bool Visit (EmitStatement node)
override bool Visit (VariableDeclarationStatement node)
override bool Visit (InlineAssembly node)
override bool Visit (ExpressionStatement node)
override void EndVisit (PlaceholderStatement node)
override void EndVisit (IfStatement node)
override void EndVisit (WhileStatement node)
override void EndVisit (DoWhileStatement node)
override void EndVisit (ForStatement node)
override void EndVisit (Continue node)
override void EndVisit (Break node)
override void EndVisit (Return node)
override void EndVisit (Throw node)
override void EndVisit (EmitStatement node)
override void EndVisit (VariableDeclarationStatement node)
override void EndVisit (InlineAssembly node)
override void EndVisit (ExpressionStatement node)
override bool Visit (FunctionCall node)
override void EndVisit (FunctionCall node)
Public Member Functions inherited from SolidityAST.BasicASTVisitor
virtual bool Visit (SourceUnitList node)
virtual bool Visit (SourceUnit node)
virtual bool Visit (PragmaDirective node)
virtual bool Visit (UsingForDirective node)
virtual bool Visit (ImportDirective node)
virtual bool Visit (InheritanceSpecifier node)
virtual bool Visit (ParameterList node)
virtual bool Visit (ModifierDefinition node)
virtual bool Visit (ModifierInvocation node)
virtual bool Visit (EventDefinition node)
virtual bool Visit (StructDefinition node)
virtual bool Visit (EnumDefinition node)
virtual bool Visit (EnumValue node)
virtual bool Visit (VariableDeclaration node)
virtual bool Visit (ElementaryTypeName node)
virtual bool Visit (UserDefinedTypeName node)
virtual bool Visit (Mapping node)
virtual bool Visit (ArrayTypeName node)
virtual bool Visit (Block node)
virtual bool Visit (Literal node)
virtual bool Visit (Identifier node)
virtual bool Visit (ElementaryTypeNameExpression node)
virtual bool Visit (UnaryOperation node)
virtual bool Visit (BinaryOperation node)
virtual bool Visit (Conditional node)
virtual bool Visit (Assignment node)
virtual bool Visit (TupleExpression node)
virtual bool Visit (NewExpression node)
virtual bool Visit (MemberAccess node)
virtual bool Visit (IndexAccess node)
virtual void EndVisit (SourceUnitList node)
virtual void EndVisit (SourceUnit node)
virtual void EndVisit (PragmaDirective node)
virtual void EndVisit (UsingForDirective node)
virtual void EndVisit (ImportDirective node)
virtual void EndVisit (InheritanceSpecifier node)
virtual void EndVisit (FunctionDefinition node)
virtual void EndVisit (ParameterList node)
virtual void EndVisit (ModifierDefinition node)
virtual void EndVisit (ModifierInvocation node)
virtual void EndVisit (EventDefinition node)
virtual void EndVisit (StructDefinition node)
virtual void EndVisit (EnumDefinition node)
virtual void EndVisit (EnumValue node)
virtual void EndVisit (VariableDeclaration node)
virtual void EndVisit (ElementaryTypeName node)
virtual void EndVisit (UserDefinedTypeName node)
virtual void EndVisit (Mapping node)
virtual void EndVisit (ArrayTypeName node)
virtual void EndVisit (Block node)
virtual void EndVisit (Literal node)
virtual void EndVisit (Identifier node)
virtual void EndVisit (ElementaryTypeNameExpression node)
virtual void EndVisit (UnaryOperation node)
virtual void EndVisit (BinaryOperation node)
virtual void EndVisit (Conditional node)
virtual void EndVisit (Assignment node)
virtual void EndVisit (TupleExpression node)
virtual void EndVisit (NewExpression node)
virtual void EndVisit (MemberAccess node)
virtual void EndVisit (IndexAccess node)
Private Member Functions
void InsertStatementBefore (FunctionDefinition function, Statement beforeThis, Statement stmt)
void InsertStatementBeforeImpl (Block block, Statement beforeThis, Statement stmt)
Block CreateBlockFromTwoStatements (Statement stmt1, Statement stmt2)
Private Attributes
TranslatorContext context
ContractDefinition currentContract
FunctionDefinition currentFunction
Statement currentStatement
Additional Inherited Members
Protected Member Functions inherited from SolidityAST.BasicASTVisitor
virtual bool CommonVisit (ASTNode node)
virtual void CommonEndVisit (ASTNode node)
Detailed Description
Definition at line 10 of file SolidityDesugaring.cs.
Constructor & Destructor Documentation
SolidityDesugaring()
SolToBoogie.SolidityDesugaring.SolidityDesugaring (TranslatorContext context) inline
Definition at line 23 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.context.
Member Function Documentation
CreateBlockFromTwoStatements()
Block SolToBoogie.SolidityDesugaring.CreateBlockFromTwoStatements (Statement stmt1, Statement stmt2) inline private
Definition at line 332 of file SolidityDesugaring.cs.
References SolidityAST.Block.Scope, and SolidityAST.Block.Statements.
Referenced by SolToBoogie.SolidityDesugaring.InsertStatementBeforeImpl().
EndVisit() [1/15]
override void SolToBoogie.SolidityDesugaring.EndVisit (Break node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 171 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
EndVisit() [2/15]
override void SolToBoogie.SolidityDesugaring.EndVisit (Continue node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 166 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
EndVisit() [3/15]
override void SolToBoogie.SolidityDesugaring.EndVisit (ContractDefinition node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 34 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentContract.
EndVisit() [4/15]
override void SolToBoogie.SolidityDesugaring.EndVisit (DoWhileStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 156 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
EndVisit() [5/15]
override void SolToBoogie.SolidityDesugaring.EndVisit (EmitStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 186 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
EndVisit() [6/15]
override void SolToBoogie.SolidityDesugaring.EndVisit (ExpressionStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 201 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
EndVisit() [7/15]
override void SolToBoogie.SolidityDesugaring.EndVisit (ForStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 161 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
EndVisit() [8/15]
override void SolToBoogie.SolidityDesugaring.EndVisit (FunctionCall node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 252 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
EndVisit() [9/15]
override void SolToBoogie.SolidityDesugaring.EndVisit (IfStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 146 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
EndVisit() [10/15]
override void SolToBoogie.SolidityDesugaring.EndVisit (InlineAssembly node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 196 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
EndVisit() [11/15]
override void SolToBoogie.SolidityDesugaring.EndVisit (PlaceholderStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 141 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
EndVisit() [12/15]
override void SolToBoogie.SolidityDesugaring.EndVisit (Return node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 176 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
EndVisit() [13/15]
override void SolToBoogie.SolidityDesugaring.EndVisit (Throw node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 181 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
EndVisit() [14/15]
override void SolToBoogie.SolidityDesugaring.EndVisit (VariableDeclarationStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 191 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
EndVisit() [15/15]
override void SolToBoogie.SolidityDesugaring.EndVisit (WhileStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 151 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
InsertStatementBefore()
void SolToBoogie.SolidityDesugaring.InsertStatementBefore (FunctionDefinition function, Statement beforeThis, Statement stmt) inline private
Definition at line 258 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.InsertStatementBeforeImpl().
InsertStatementBeforeImpl()
void SolToBoogie.SolidityDesugaring.InsertStatementBeforeImpl (Block block, Statement beforeThis, Statement stmt) inline private
Definition at line 263 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.CreateBlockFromTwoStatements(), and SolidityAST.Block.Statements.
Referenced by SolToBoogie.SolidityDesugaring.InsertStatementBefore().
Visit() [1/16]
override bool SolToBoogie.SolidityDesugaring.Visit (Break node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 99 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
Visit() [2/16]
override bool SolToBoogie.SolidityDesugaring.Visit (Continue node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 93 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
Visit() [3/16]
override bool SolToBoogie.SolidityDesugaring.Visit (ContractDefinition node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 28 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentContract.
Visit() [4/16]
override bool SolToBoogie.SolidityDesugaring.Visit (DoWhileStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 81 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
Visit() [5/16]
override bool SolToBoogie.SolidityDesugaring.Visit (EmitStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 117 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
Visit() [6/16]
override bool SolToBoogie.SolidityDesugaring.Visit (ExpressionStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 135 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
Visit() [7/16]
override bool SolToBoogie.SolidityDesugaring.Visit (ForStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 87 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
Visit() [8/16]
override bool SolToBoogie.SolidityDesugaring.Visit (FunctionCall node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 206 of file SolidityDesugaring.cs.
References SolidityAST.FunctionCall.Expression, SolidityAST.FunctionCall.MsgGas, and SolidityAST.FunctionCall.MsgValue.
Visit() [9/16]
override bool SolToBoogie.SolidityDesugaring.Visit (FunctionDefinition node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 39 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentContract, SolToBoogie.SolidityDesugaring.currentFunction, SolidityAST.FunctionDefinition.IsConstructor, SolidityAST.FunctionDefinition.IsFallback, SolidityAST.ContractDefinition.Name, SolidityAST.FunctionDefinition.Name, and SolidityAST.FunctionDefinition.Visibility.
Visit() [10/16]
override bool SolToBoogie.SolidityDesugaring.Visit (IfStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 69 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
Visit() [11/16]
override bool SolToBoogie.SolidityDesugaring.Visit (InlineAssembly node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 129 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
Visit() [12/16]
override bool SolToBoogie.SolidityDesugaring.Visit (PlaceholderStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 63 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
Visit() [13/16]
override bool SolToBoogie.SolidityDesugaring.Visit (Return node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 105 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
Visit() [14/16]
override bool SolToBoogie.SolidityDesugaring.Visit (Throw node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 111 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
Visit() [15/16]
override bool SolToBoogie.SolidityDesugaring.Visit (VariableDeclarationStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 123 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
Visit() [16/16]
override bool SolToBoogie.SolidityDesugaring.Visit (WhileStatement node) inline virtual
Reimplemented from SolidityAST.BasicASTVisitor.
Definition at line 75 of file SolidityDesugaring.cs.
References SolToBoogie.SolidityDesugaring.currentStatement.
Member Data Documentation
context
TranslatorContext SolToBoogie.SolidityDesugaring.context private
Definition at line 12 of file SolidityDesugaring.cs.
Referenced by SolToBoogie.SolidityDesugaring.SolidityDesugaring().
currentContract
ContractDefinition SolToBoogie.SolidityDesugaring.currentContract private
Definition at line 15 of file SolidityDesugaring.cs.
Referenced by SolToBoogie.SolidityDesugaring.EndVisit(), and SolToBoogie.SolidityDesugaring.Visit().
currentFunction
FunctionDefinition SolToBoogie.SolidityDesugaring.currentFunction private
Definition at line 18 of file SolidityDesugaring.cs.
Referenced by SolToBoogie.SolidityDesugaring.Visit().
currentStatement
Statement SolToBoogie.SolidityDesugaring.currentStatement private
Definition at line 21 of file SolidityDesugaring.cs.
Referenced by SolToBoogie.SolidityDesugaring.EndVisit(), and SolToBoogie.SolidityDesugaring.Visit().
The documentation for this class was generated from the following file:
Sources/SolToBoogie/SolidityDesugaring.cs