VeriSol: SolidityAST.TupleExpression Class Reference
SolidityAST.TupleExpression Class Reference
Public Member Functions
int Length ()
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
List< Expression > Components [get, set]
bool IsInlineArray [get, set]
Properties inherited from SolidityAST.Expression
List< TypeDescription > ArgumentTypes [get, set]
bool IsConstant [get, set]
bool IsPure [get, set]
bool IsLValue [get, set]
bool LValueRequested [get, set]
TypeDescription TypeDescriptions [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 1603 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.TupleExpression.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1614 of file SolidityAST.cs.
References SolidityAST.TupleExpression.Components, SolidityAST.IASTVisitor.EndVisit(), and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.TupleExpression.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 1628 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
Length()
int SolidityAST.TupleExpression.Length () inline
Definition at line 1609 of file SolidityAST.cs.
References SolidityAST.TupleExpression.Components.
ToString()
override string SolidityAST.TupleExpression.ToString () inline
Definition at line 1633 of file SolidityAST.cs.
References SolidityAST.TupleExpression.Components.
Property Documentation
Components
List<Expression> SolidityAST.TupleExpression.Components get set
Definition at line 1605 of file SolidityAST.cs.
Referenced by SolidityAST.TupleExpression.Accept(), SolidityAST.TupleExpression.Length(), and SolidityAST.TupleExpression.ToString().
IsInlineArray
bool SolidityAST.TupleExpression.IsInlineArray get set
Definition at line 1607 of file SolidityAST.cs.
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs