VeriSol: SolidityAST.ArrayTypeName Class Reference
SolidityAST.ArrayTypeName Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
TypeName BaseType [get, set]
Expression Length [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 889 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.ArrayTypeName.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 895 of file SolidityAST.cs.
References SolidityAST.ASTNode.Accept(), SolidityAST.ArrayTypeName.BaseType, SolidityAST.IASTVisitor.EndVisit(), SolidityAST.ArrayTypeName.Length, and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.ArrayTypeName.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 908 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.ArrayTypeName.ToString () inline
Definition at line 913 of file SolidityAST.cs.
References SolidityAST.ArrayTypeName.BaseType, and SolidityAST.ArrayTypeName.Length.
Property Documentation
BaseType
TypeName SolidityAST.ArrayTypeName.BaseType get set
Definition at line 891 of file SolidityAST.cs.
Referenced by SolidityAST.ArrayTypeName.Accept(), SolToBoogie.ProcedureTranslator.GenerateInitializationForArrayStateVar(), SolToBoogie.GhostVarAndAxiomGenerator.GenerateMemoryVariablesForArray(), and SolidityAST.ArrayTypeName.ToString().
Length
Expression SolidityAST.ArrayTypeName.Length get set
Definition at line 893 of file SolidityAST.cs.
Referenced by SolidityAST.ArrayTypeName.Accept(), SolToBoogie.ProcedureTranslator.GenerateInitializationForArrayStateVar(), and SolidityAST.ArrayTypeName.ToString().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs