VeriSol: SolidityAST.ModifierInvocation Class Reference
SolidityAST.ModifierInvocation Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
Identifier ModifierName [get, set]
List< Expression > Arguments [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 567 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.ModifierInvocation.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 573 of file SolidityAST.cs.
References SolidityAST.Identifier.Accept(), SolidityAST.ModifierInvocation.Arguments, SolidityAST.IASTVisitor.EndVisit(), SolidityAST.ModifierInvocation.ModifierName, and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.ModifierInvocation.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 586 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.ModifierInvocation.ToString () inline
Definition at line 591 of file SolidityAST.cs.
References SolidityAST.ModifierInvocation.Arguments, and SolidityAST.ModifierInvocation.ModifierName.
Property Documentation
Arguments
List<Expression> SolidityAST.ModifierInvocation.Arguments get set
Definition at line 571 of file SolidityAST.cs.
Referenced by SolidityAST.ModifierInvocation.Accept(), SolToBoogie.ProcedureTranslator.GenerateConstructorWithBaseCalls(), and SolidityAST.ModifierInvocation.ToString().
ModifierName
Identifier SolidityAST.ModifierInvocation.ModifierName get set
Definition at line 569 of file SolidityAST.cs.
Referenced by SolidityAST.ModifierInvocation.Accept(), SolToBoogie.ProcedureTranslator.GetModifierInvocationOfBase(), and SolidityAST.ModifierInvocation.ToString().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs