VeriSol: SolidityAST.AST Class Reference
SolidityAST.AST Class Reference
Public Member Functions
AST (CompilerOutput compilerOutput, string sourceDirectory=null)
SourceUnitList GetSourceUnits ()
Dictionary< int, ASTNode > GetIdToNodeMap ()
ASTNode GetASTNodeByID (int id)
Properties
string SourceDirectory [get, private set]
Private Member Functions
SourceUnitList BuildSourceUnitList (CompilerOutput compilerOutput)
Private Attributes
readonly SourceUnitList sourceUnits
readonly Dictionary< int, ASTNode > idToNodeMap
Detailed Description
Definition at line 47 of file SolidityAST.cs.
Constructor & Destructor Documentation
AST()
SolidityAST.AST.AST (CompilerOutput compilerOutput, string sourceDirectory = null) inline
Definition at line 55 of file SolidityAST.cs.
References SolidityAST.AST.BuildSourceUnitList(), SolidityAST.NodeMapper.GetIdToNodeMap(), SolidityAST.AST.idToNodeMap, SolidityAST.AST.SourceDirectory, and SolidityAST.AST.sourceUnits.
Member Function Documentation
BuildSourceUnitList()
SourceUnitList SolidityAST.AST.BuildSourceUnitList (CompilerOutput compilerOutput) inline private
Definition at line 63 of file SolidityAST.cs.
References SolidityAST.SoliditySourceFile.Ast.
Referenced by SolidityAST.AST.AST().
GetASTNodeByID()
ASTNode SolidityAST.AST.GetASTNodeByID (int id) inline
Definition at line 85 of file SolidityAST.cs.
References SolidityAST.AST.idToNodeMap.
GetIdToNodeMap()
Dictionary<int, ASTNode> SolidityAST.AST.GetIdToNodeMap () inline
Definition at line 80 of file SolidityAST.cs.
References SolidityAST.AST.idToNodeMap.
Referenced by SolToBoogie.BoogieTranslator.Translate().
GetSourceUnits()
SourceUnitList SolidityAST.AST.GetSourceUnits () inline
Definition at line 75 of file SolidityAST.cs.
References SolidityAST.AST.sourceUnits.
Referenced by SolidityAST.RegressionExecutor.Execute(), SolidityAST.TestMain.LegacyMain(), and SolToBoogie.BoogieTranslator.Translate().
Member Data Documentation
idToNodeMap
readonly Dictionary<int, ASTNode> SolidityAST.AST.idToNodeMap private
Definition at line 51 of file SolidityAST.cs.
Referenced by SolidityAST.AST.AST(), SolidityAST.AST.GetASTNodeByID(), and SolidityAST.AST.GetIdToNodeMap().
sourceUnits
readonly SourceUnitList SolidityAST.AST.sourceUnits private
Definition at line 49 of file SolidityAST.cs.
Referenced by SolidityAST.AST.AST(), and SolidityAST.AST.GetSourceUnits().
Property Documentation
SourceDirectory
string SolidityAST.AST.SourceDirectory get private set
Definition at line 53 of file SolidityAST.cs.
Referenced by SolidityAST.AST.AST(), and SolToBoogie.BoogieTranslator.Translate().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs