VeriSol: VeriSolRunner.ExternalTools.DownloadedToolManager Class Reference
VeriSolRunner.ExternalTools.DownloadedToolManager Class Reference
Protected Member Functions
virtual void Install ()
void DownloadAndUnZip ()
void DownloadAndCopy ()
void CreateSymbolicLink ()
Protected Member Functions inherited from VeriSolRunner.ExternalTools.ToolManager
bool Exists ()
void EnsureCommandPathExisted ()
Package Functions
DownloadedToolManager (ToolSourceSettings settings)
override void EnsureExisted ()
Package Functions inherited from VeriSolRunner.ExternalTools.ToolManager
ToolManager (ToolSourceSettings settings)
Properties
string DownloadURL [get]
string ExePathWithinZip [get]
string ZipFileName [get]
string TempDirectory [get]
string ZipFilePath [get]
string ExtractPath [get]
string ExeTempPath [get]
Properties inherited from VeriSolRunner.ExternalTools.ToolManager
static string OsName [get]
string ExeName [get]
string Command [get]
Private Member Functions
void ChangePermission ()
void RunCmd (string cmdName, string arguments)
void PrepareTempDirectory ()
void CopyToCommand (string exeTempPath)
void Download ()
Additional Inherited Members
Protected Attributes inherited from VeriSolRunner.ExternalTools.ToolManager
readonly ToolSourceSettings settings
Detailed Description
Definition at line 10 of file DownloadedToolManager.cs.
Constructor & Destructor Documentation
DownloadedToolManager()
VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadedToolManager (ToolSourceSettings settings) inline package
Definition at line 68 of file DownloadedToolManager.cs.
Member Function Documentation
ChangePermission()
void VeriSolRunner.ExternalTools.DownloadedToolManager.ChangePermission () inline private
Definition at line 87 of file DownloadedToolManager.cs.
References VeriSolRunner.ExternalTools.ToolManager.OsName, and VeriSolRunner.ExternalTools.DownloadedToolManager.RunCmd().
Referenced by VeriSolRunner.ExternalTools.DownloadedToolManager.EnsureExisted().
CopyToCommand()
void VeriSolRunner.ExternalTools.DownloadedToolManager.CopyToCommand (string exeTempPath) inline private
Definition at line 182 of file DownloadedToolManager.cs.
References VeriSolRunner.ExternalTools.ToolManager.Command, and VeriSolRunner.ExternalTools.ExternalToolsManager.Log().
Referenced by VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadAndCopy(), and VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadAndUnZip().
CreateSymbolicLink()
void VeriSolRunner.ExternalTools.DownloadedToolManager.CreateSymbolicLink () inline protected
Definition at line 151 of file DownloadedToolManager.cs.
References VeriSolRunner.ExternalTools.ToolManager.OsName, and VeriSolRunner.ExternalTools.DownloadedToolManager.RunCmd().
Referenced by VeriSolRunner.ExternalTools.SolcManager.Install().
Download()
void VeriSolRunner.ExternalTools.DownloadedToolManager.Download () inline private
Definition at line 188 of file DownloadedToolManager.cs.
References VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadURL, VeriSolRunner.ExternalTools.ExternalToolsManager.Log(), and VeriSolRunner.ExternalTools.DownloadedToolManager.ZipFilePath.
Referenced by VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadAndCopy(), and VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadAndUnZip().
DownloadAndCopy()
void VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadAndCopy () inline protected
Definition at line 140 of file DownloadedToolManager.cs.
References VeriSolRunner.ExternalTools.DownloadedToolManager.CopyToCommand(), VeriSolRunner.ExternalTools.DownloadedToolManager.Download(), VeriSolRunner.ExternalTools.ExternalToolsManager.Log(), VeriSolRunner.ExternalTools.DownloadedToolManager.PrepareTempDirectory(), and VeriSolRunner.ExternalTools.DownloadedToolManager.ZipFilePath.
Referenced by VeriSolRunner.ExternalTools.SolcManager.Install().
DownloadAndUnZip()
void VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadAndUnZip () inline protected
Definition at line 124 of file DownloadedToolManager.cs.
References VeriSolRunner.ExternalTools.DownloadedToolManager.CopyToCommand(), VeriSolRunner.ExternalTools.DownloadedToolManager.Download(), VeriSolRunner.ExternalTools.DownloadedToolManager.ExeTempPath, VeriSolRunner.ExternalTools.DownloadedToolManager.ExtractPath, VeriSolRunner.ExternalTools.ExternalToolsManager.Log(), VeriSolRunner.ExternalTools.DownloadedToolManager.PrepareTempDirectory(), and VeriSolRunner.ExternalTools.DownloadedToolManager.ZipFilePath.
Referenced by VeriSolRunner.ExternalTools.DownloadedToolManager.Install(), and VeriSolRunner.ExternalTools.SolcManager.Install().
EnsureExisted()
override void VeriSolRunner.ExternalTools.DownloadedToolManager.EnsureExisted () inline package virtual
Implements VeriSolRunner.ExternalTools.ToolManager.
Definition at line 72 of file DownloadedToolManager.cs.
References VeriSolRunner.ExternalTools.DownloadedToolManager.ChangePermission(), VeriSolRunner.ExternalTools.ToolManager.EnsureCommandPathExisted(), VeriSolRunner.ExternalTools.ToolManager.Exists(), VeriSolRunner.ExternalTools.DownloadedToolManager.Install(), and VeriSolRunner.ExternalTools.ExternalToolsManager.Log().
Install()
virtual void VeriSolRunner.ExternalTools.DownloadedToolManager.Install () inline protected virtual
Reimplemented in VeriSolRunner.ExternalTools.SolcManager.
Definition at line 119 of file DownloadedToolManager.cs.
References VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadAndUnZip().
Referenced by VeriSolRunner.ExternalTools.DownloadedToolManager.EnsureExisted().
PrepareTempDirectory()
void VeriSolRunner.ExternalTools.DownloadedToolManager.PrepareTempDirectory () inline private
Definition at line 159 of file DownloadedToolManager.cs.
References VeriSolRunner.ExternalTools.DownloadedToolManager.ExtractPath, VeriSolRunner.ExternalTools.ExternalToolsManager.Log(), VeriSolRunner.ExternalTools.DownloadedToolManager.TempDirectory, and VeriSolRunner.ExternalTools.DownloadedToolManager.ZipFilePath.
Referenced by VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadAndCopy(), and VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadAndUnZip().
RunCmd()
void VeriSolRunner.ExternalTools.DownloadedToolManager.RunCmd (string cmdName, string arguments) inline private
Definition at line 95 of file DownloadedToolManager.cs.
References VeriSolRunner.ExternalTools.ExternalToolsManager.Log().
Referenced by VeriSolRunner.ExternalTools.DownloadedToolManager.ChangePermission(), and VeriSolRunner.ExternalTools.DownloadedToolManager.CreateSymbolicLink().
Property Documentation
DownloadURL
string VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadURL get private
Definition at line 12 of file DownloadedToolManager.cs.
Referenced by VeriSolRunner.ExternalTools.DownloadedToolManager.Download().
ExePathWithinZip
string VeriSolRunner.ExternalTools.DownloadedToolManager.ExePathWithinZip get private
Definition at line 20 of file DownloadedToolManager.cs.
ExeTempPath
string VeriSolRunner.ExternalTools.DownloadedToolManager.ExeTempPath get private
Definition at line 60 of file DownloadedToolManager.cs.
Referenced by VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadAndUnZip().
ExtractPath
string VeriSolRunner.ExternalTools.DownloadedToolManager.ExtractPath get private
Definition at line 52 of file DownloadedToolManager.cs.
Referenced by VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadAndUnZip(), and VeriSolRunner.ExternalTools.DownloadedToolManager.PrepareTempDirectory().
TempDirectory
string VeriSolRunner.ExternalTools.DownloadedToolManager.TempDirectory get private
Definition at line 36 of file DownloadedToolManager.cs.
Referenced by VeriSolRunner.ExternalTools.DownloadedToolManager.PrepareTempDirectory().
ZipFileName
string VeriSolRunner.ExternalTools.DownloadedToolManager.ZipFileName get private
Definition at line 28 of file DownloadedToolManager.cs.
ZipFilePath
string VeriSolRunner.ExternalTools.DownloadedToolManager.ZipFilePath get private
Definition at line 44 of file DownloadedToolManager.cs.
Referenced by VeriSolRunner.ExternalTools.DownloadedToolManager.Download(), VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadAndCopy(), VeriSolRunner.ExternalTools.DownloadedToolManager.DownloadAndUnZip(), and VeriSolRunner.ExternalTools.DownloadedToolManager.PrepareTempDirectory().
The documentation for this class was generated from the following file:
Sources/ExternalToolsManager/DownloadedToolManager.cs