VeriSol: SolidityAST.ElementaryTypeName Class Reference
SolidityAST.ElementaryTypeName Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
TypeDescription TypeDescriptions [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 811 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.ElementaryTypeName.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 815 of file SolidityAST.cs.
References SolidityAST.IASTVisitor.EndVisit(), and SolidityAST.IASTVisitor.Visit().
Referenced by SolidityAST.Mapping.Accept().
Accept< T >()
override T SolidityAST.ElementaryTypeName.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 821 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.ElementaryTypeName.ToString () inline
Definition at line 826 of file SolidityAST.cs.
References SolidityAST.TypeDescription.ToString(), and SolidityAST.ElementaryTypeName.TypeDescriptions.
Property Documentation
TypeDescriptions
TypeDescription SolidityAST.ElementaryTypeName.TypeDescriptions get set
Definition at line 813 of file SolidityAST.cs.
Referenced by SolToBoogie.ProcedureTranslator.GenerateInitializationForElementaryTypes(), SolToBoogie.ProcedureTranslator.GetBoogieTypesFromMapping(), SolToBoogie.ProcedureTranslator.InitializeNestedArrayMappingStateVar(), and SolidityAST.ElementaryTypeName.ToString().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs