VeriSol: SolidityAST.ImportDirective Class Reference
SolidityAST.ImportDirective Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
string AbsolutePath [get, set]
string File [get, set]
int SourceUnit [get, set]
List< object > SymbolAliases [get, set]
string UnitAlias [get, set]
Properties inherited from SolidityAST.Declaration
int Scope [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 276 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.ImportDirective.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 288 of file SolidityAST.cs.
References SolidityAST.IASTVisitor.EndVisit(), and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.ImportDirective.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 294 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.ImportDirective.ToString () inline
Definition at line 299 of file SolidityAST.cs.
References SolidityAST.ImportDirective.File.
Property Documentation
AbsolutePath
string SolidityAST.ImportDirective.AbsolutePath get set
Definition at line 278 of file SolidityAST.cs.
File
string SolidityAST.ImportDirective.File get set
Definition at line 280 of file SolidityAST.cs.
Referenced by SolidityAST.ImportDirective.ToString().
SourceUnit
int SolidityAST.ImportDirective.SourceUnit get set
Definition at line 282 of file SolidityAST.cs.
SymbolAliases
List<object> SolidityAST.ImportDirective.SymbolAliases get set
Definition at line 284 of file SolidityAST.cs.
UnitAlias
string SolidityAST.ImportDirective.UnitAlias get set
Definition at line 286 of file SolidityAST.cs.
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs