VeriSol: SolidityAST.SourceUnit Class Reference
SolidityAST.SourceUnit Class Reference
Public Member Functions
override void Accept (IASTVisitor visitor)
override T Accept< T > (IASTGenericVisitor< T > visitor)
override string ToString ()
Properties
string AbsolutePath [get, set]
Dictionary< string, List< int > > ExportedSymbols [get, set]
List< ASTNode > Nodes [get, set]
Properties inherited from SolidityAST.ASTNode
int Id [get, set]
int GasCost [get, set]
string NodeType [get, set]
string Src [get, set]
Detailed Description
Definition at line 175 of file SolidityAST.cs.
Member Function Documentation
Accept()
override void SolidityAST.SourceUnit.Accept (IASTVisitor visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 183 of file SolidityAST.cs.
References SolidityAST.IASTVisitor.EndVisit(), SolidityAST.SourceUnit.Nodes, and SolidityAST.IASTVisitor.Visit().
Accept< T >()
override T SolidityAST.SourceUnit.Accept< T > (IASTGenericVisitor< T > visitor) inline virtual
Implements SolidityAST.ASTNode.
Definition at line 192 of file SolidityAST.cs.
References SolidityAST.IASTGenericVisitor< T >.Visit().
ToString()
override string SolidityAST.SourceUnit.ToString () inline
Definition at line 197 of file SolidityAST.cs.
References SolidityAST.SourceUnit.Nodes.
Property Documentation
AbsolutePath
string SolidityAST.SourceUnit.AbsolutePath get set
Definition at line 177 of file SolidityAST.cs.
Referenced by SolToBoogie.SourceInfoCollector.CommonEndVisit().
ExportedSymbols
Dictionary<string, List<int> > SolidityAST.SourceUnit.ExportedSymbols get set
Definition at line 179 of file SolidityAST.cs.
Nodes
List<ASTNode> SolidityAST.SourceUnit.Nodes get set
Definition at line 181 of file SolidityAST.cs.
Referenced by SolidityAST.SourceUnit.Accept(), and SolidityAST.SourceUnit.ToString().
The documentation for this class was generated from the following file:
Sources/SolidityAST/SolidityAST.cs