VeriSol: SolidityAST.IASTVisitor Interface Reference
SolidityAST.IASTVisitor Interface Reference
Public Member Functions
bool Visit (SourceUnitList node)
bool Visit (SourceUnit node)
bool Visit (PragmaDirective node)
bool Visit (UsingForDirective node)
bool Visit (ImportDirective node)
bool Visit (ContractDefinition node)
bool Visit (InheritanceSpecifier node)
bool Visit (FunctionDefinition node)
bool Visit (ParameterList node)
bool Visit (ModifierDefinition node)
bool Visit (ModifierInvocation node)
bool Visit (EventDefinition node)
bool Visit (StructDefinition node)
bool Visit (EnumDefinition node)
bool Visit (EnumValue node)
bool Visit (VariableDeclaration node)
bool Visit (ElementaryTypeName node)
bool Visit (UserDefinedTypeName node)
bool Visit (Mapping node)
bool Visit (ArrayTypeName node)
bool Visit (Block node)
bool Visit (PlaceholderStatement node)
bool Visit (IfStatement node)
bool Visit (WhileStatement node)
bool Visit (DoWhileStatement node)
bool Visit (ForStatement node)
bool Visit (Continue node)
bool Visit (Break node)
bool Visit (Return node)
bool Visit (Throw node)
bool Visit (EmitStatement node)
bool Visit (VariableDeclarationStatement node)
bool Visit (InlineAssembly node)
bool Visit (ExpressionStatement node)
bool Visit (Literal node)
bool Visit (Identifier node)
bool Visit (ElementaryTypeNameExpression node)
bool Visit (UnaryOperation node)
bool Visit (BinaryOperation node)
bool Visit (Conditional node)
bool Visit (Assignment node)
bool Visit (TupleExpression node)
bool Visit (FunctionCall node)
bool Visit (NewExpression node)
bool Visit (MemberAccess node)
bool Visit (IndexAccess node)
void EndVisit (SourceUnitList node)
void EndVisit (SourceUnit node)
void EndVisit (PragmaDirective node)
void EndVisit (UsingForDirective node)
void EndVisit (ImportDirective node)
void EndVisit (ContractDefinition node)
void EndVisit (InheritanceSpecifier node)
void EndVisit (FunctionDefinition node)
void EndVisit (ParameterList node)
void EndVisit (ModifierDefinition node)
void EndVisit (ModifierInvocation node)
void EndVisit (EventDefinition node)
void EndVisit (StructDefinition node)
void EndVisit (EnumDefinition node)
void EndVisit (EnumValue node)
void EndVisit (VariableDeclaration node)
void EndVisit (ElementaryTypeName node)
void EndVisit (UserDefinedTypeName node)
void EndVisit (Mapping node)
void EndVisit (ArrayTypeName node)
void EndVisit (Block node)
void EndVisit (PlaceholderStatement node)
void EndVisit (IfStatement node)
void EndVisit (WhileStatement node)
void EndVisit (DoWhileStatement node)
void EndVisit (ForStatement node)
void EndVisit (Continue node)
void EndVisit (Break node)
void EndVisit (Return node)
void EndVisit (Throw node)
void EndVisit (EmitStatement node)
void EndVisit (VariableDeclarationStatement node)
void EndVisit (InlineAssembly node)
void EndVisit (ExpressionStatement node)
void EndVisit (Literal node)
void EndVisit (Identifier node)
void EndVisit (ElementaryTypeNameExpression node)
void EndVisit (UnaryOperation node)
void EndVisit (BinaryOperation node)
void EndVisit (Conditional node)
void EndVisit (Assignment node)
void EndVisit (TupleExpression node)
void EndVisit (FunctionCall node)
void EndVisit (NewExpression node)
void EndVisit (MemberAccess node)
void EndVisit (IndexAccess node)
Detailed Description
Definition at line 5 of file IASTVisitor.cs.
Member Function Documentation
EndVisit() [1/46]
void SolidityAST.IASTVisitor.EndVisit (ArrayTypeName node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [2/46]
void SolidityAST.IASTVisitor.EndVisit (Assignment node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [3/46]
void SolidityAST.IASTVisitor.EndVisit (BinaryOperation node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [4/46]
void SolidityAST.IASTVisitor.EndVisit (Block node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [5/46]
void SolidityAST.IASTVisitor.EndVisit (Break node)
Implemented in SolToBoogie.SolidityDesugaring, and SolidityAST.BasicASTVisitor.
EndVisit() [6/46]
void SolidityAST.IASTVisitor.EndVisit (Conditional node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [7/46]
void SolidityAST.IASTVisitor.EndVisit (Continue node)
Implemented in SolToBoogie.SolidityDesugaring, and SolidityAST.BasicASTVisitor.
EndVisit() [8/46]
void SolidityAST.IASTVisitor.EndVisit (ContractDefinition node)
Implemented in SolToBoogie.UsingCollector, SolToBoogie.SolidityDesugaring, SolToBoogie.MapArrayCollector, SolToBoogie.FunctionEventCollector, and SolidityAST.BasicASTVisitor.
EndVisit() [9/46]
void SolidityAST.IASTVisitor.EndVisit (DoWhileStatement node)
Implemented in SolToBoogie.SolidityDesugaring, and SolidityAST.BasicASTVisitor.
EndVisit() [10/46]
void SolidityAST.IASTVisitor.EndVisit (ElementaryTypeName node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [11/46]
void SolidityAST.IASTVisitor.EndVisit (ElementaryTypeNameExpression node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [12/46]
void SolidityAST.IASTVisitor.EndVisit (EmitStatement node)
Implemented in SolToBoogie.SolidityDesugaring, and SolidityAST.BasicASTVisitor.
EndVisit() [13/46]
void SolidityAST.IASTVisitor.EndVisit (EnumDefinition node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [14/46]
void SolidityAST.IASTVisitor.EndVisit (EnumValue node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [15/46]
void SolidityAST.IASTVisitor.EndVisit (EventDefinition node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [16/46]
void SolidityAST.IASTVisitor.EndVisit (ExpressionStatement node)
Implemented in SolToBoogie.SolidityDesugaring, and SolidityAST.BasicASTVisitor.
EndVisit() [17/46]
void SolidityAST.IASTVisitor.EndVisit (ForStatement node)
Implemented in SolToBoogie.SolidityDesugaring, and SolidityAST.BasicASTVisitor.
EndVisit() [18/46]
void SolidityAST.IASTVisitor.EndVisit (FunctionCall node)
Implemented in SolToBoogie.SolidityDesugaring, and SolidityAST.BasicASTVisitor.
EndVisit() [19/46]
void SolidityAST.IASTVisitor.EndVisit (FunctionDefinition node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [20/46]
void SolidityAST.IASTVisitor.EndVisit (Identifier node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [21/46]
void SolidityAST.IASTVisitor.EndVisit (IfStatement node)
Implemented in SolToBoogie.SolidityDesugaring, and SolidityAST.BasicASTVisitor.
EndVisit() [22/46]
void SolidityAST.IASTVisitor.EndVisit (ImportDirective node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [23/46]
void SolidityAST.IASTVisitor.EndVisit (IndexAccess node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [24/46]
void SolidityAST.IASTVisitor.EndVisit (InheritanceSpecifier node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [25/46]
void SolidityAST.IASTVisitor.EndVisit (InlineAssembly node)
Implemented in SolToBoogie.SolidityDesugaring, and SolidityAST.BasicASTVisitor.
EndVisit() [26/46]
void SolidityAST.IASTVisitor.EndVisit (Literal node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [27/46]
void SolidityAST.IASTVisitor.EndVisit (Mapping node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [28/46]
void SolidityAST.IASTVisitor.EndVisit (MemberAccess node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [29/46]
void SolidityAST.IASTVisitor.EndVisit (ModifierDefinition node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [30/46]
void SolidityAST.IASTVisitor.EndVisit (ModifierInvocation node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [31/46]
void SolidityAST.IASTVisitor.EndVisit (NewExpression node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [32/46]
void SolidityAST.IASTVisitor.EndVisit (ParameterList node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [33/46]
void SolidityAST.IASTVisitor.EndVisit (PlaceholderStatement node)
Implemented in SolToBoogie.SolidityDesugaring, and SolidityAST.BasicASTVisitor.
EndVisit() [34/46]
void SolidityAST.IASTVisitor.EndVisit (PragmaDirective node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [35/46]
void SolidityAST.IASTVisitor.EndVisit (Return node)
Implemented in SolToBoogie.SolidityDesugaring, and SolidityAST.BasicASTVisitor.
EndVisit() [36/46]
void SolidityAST.IASTVisitor.EndVisit (SourceUnit node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [37/46]
void SolidityAST.IASTVisitor.EndVisit (SourceUnitList node)
Implemented in SolidityAST.BasicASTVisitor.
Referenced by SolidityAST.SourceUnitList.Accept(), SolidityAST.SourceUnit.Accept(), SolidityAST.PragmaDirective.Accept(), SolidityAST.UsingForDirective.Accept(), SolidityAST.ImportDirective.Accept(), SolidityAST.ContractDefinition.Accept(), SolidityAST.InheritanceSpecifier.Accept(), SolidityAST.FunctionDefinition.Accept(), SolidityAST.ParameterList.Accept(), SolidityAST.ModifierDefinition.Accept(), SolidityAST.ModifierInvocation.Accept(), SolidityAST.EventDefinition.Accept(), SolidityAST.StructDefinition.Accept(), SolidityAST.EnumDefinition.Accept(), SolidityAST.EnumValue.Accept(), SolidityAST.VariableDeclaration.Accept(), SolidityAST.ElementaryTypeName.Accept(), SolidityAST.UserDefinedTypeName.Accept(), SolidityAST.Mapping.Accept(), SolidityAST.ArrayTypeName.Accept(), SolidityAST.Block.Accept(), SolidityAST.PlaceholderStatement.Accept(), SolidityAST.IfStatement.Accept(), SolidityAST.WhileStatement.Accept(), SolidityAST.DoWhileStatement.Accept(), SolidityAST.ForStatement.Accept(), SolidityAST.Continue.Accept(), SolidityAST.Break.Accept(), SolidityAST.Return.Accept(), SolidityAST.Throw.Accept(), SolidityAST.EmitStatement.Accept(), SolidityAST.VariableDeclarationStatement.Accept(), SolidityAST.InlineAssembly.Accept(), SolidityAST.ExpressionStatement.Accept(), SolidityAST.Literal.Accept(), SolidityAST.Identifier.Accept(), SolidityAST.ElementaryTypeNameExpression.Accept(), SolidityAST.UnaryOperation.Accept(), SolidityAST.BinaryOperation.Accept(), SolidityAST.Conditional.Accept(), SolidityAST.Assignment.Accept(), SolidityAST.TupleExpression.Accept(), SolidityAST.FunctionCall.Accept(), SolidityAST.NewExpression.Accept(), SolidityAST.MemberAccess.Accept(), and SolidityAST.IndexAccess.Accept().
EndVisit() [38/46]
void SolidityAST.IASTVisitor.EndVisit (StructDefinition node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [39/46]
void SolidityAST.IASTVisitor.EndVisit (Throw node)
Implemented in SolToBoogie.SolidityDesugaring, and SolidityAST.BasicASTVisitor.
EndVisit() [40/46]
void SolidityAST.IASTVisitor.EndVisit (TupleExpression node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [41/46]
void SolidityAST.IASTVisitor.EndVisit (UnaryOperation node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [42/46]
void SolidityAST.IASTVisitor.EndVisit (UserDefinedTypeName node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [43/46]
void SolidityAST.IASTVisitor.EndVisit (UsingForDirective node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [44/46]
void SolidityAST.IASTVisitor.EndVisit (VariableDeclaration node)
Implemented in SolidityAST.BasicASTVisitor.
EndVisit() [45/46]
void SolidityAST.IASTVisitor.EndVisit (VariableDeclarationStatement node)
Implemented in SolToBoogie.SolidityDesugaring, and SolidityAST.BasicASTVisitor.
EndVisit() [46/46]
void SolidityAST.IASTVisitor.EndVisit (WhileStatement node)
Implemented in SolToBoogie.SolidityDesugaring, and SolidityAST.BasicASTVisitor.
Visit() [1/46]
bool SolidityAST.IASTVisitor.Visit (ArrayTypeName node)
Implemented in SolidityAST.BasicASTVisitor.
Visit() [2/46]
bool SolidityAST.IASTVisitor.Visit (Assignment node)
Implemented in SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [3/46]
bool SolidityAST.IASTVisitor.Visit (BinaryOperation node)
Implemented in SolToBoogie.ProcedureTranslator, SolidityAST.BasicASTVisitor, and SolidityCFG.CFGBuilder.
Visit() [4/46]
bool SolidityAST.IASTVisitor.Visit (Block node)
Implemented in SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [5/46]
bool SolidityAST.IASTVisitor.Visit (Break node)
Implemented in SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [6/46]
bool SolidityAST.IASTVisitor.Visit (Conditional node)
Implemented in SolToBoogie.ProcedureTranslator, SolidityAST.BasicASTVisitor, and SolidityCFG.CFGBuilder.
Visit() [7/46]
bool SolidityAST.IASTVisitor.Visit (Continue node)
Implemented in SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [8/46]
bool SolidityAST.IASTVisitor.Visit (ContractDefinition node)
Implemented in SolToBoogie.UsingCollector, SolToBoogie.StateVariableCollector, SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, SolToBoogie.MapArrayCollector, SolToBoogie.FunctionEventCollector, SolToBoogie.ContractCollector, SolToBoogie.ConstructorCollector, and SolidityAST.BasicASTVisitor.
Visit() [9/46]
bool SolidityAST.IASTVisitor.Visit (DoWhileStatement node)
Implemented in SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [10/46]
bool SolidityAST.IASTVisitor.Visit (ElementaryTypeName node)
Implemented in SolidityAST.BasicASTVisitor.
Visit() [11/46]
bool SolidityAST.IASTVisitor.Visit (ElementaryTypeNameExpression node)
Implemented in SolidityAST.BasicASTVisitor.
Visit() [12/46]
bool SolidityAST.IASTVisitor.Visit (EmitStatement node)
Implemented in SolToBoogie.SolidityDesugaring, and SolidityAST.BasicASTVisitor.
Visit() [13/46]
bool SolidityAST.IASTVisitor.Visit (EnumDefinition node)
Implemented in SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [14/46]
bool SolidityAST.IASTVisitor.Visit (EnumValue node)
Implemented in SolidityAST.BasicASTVisitor.
Visit() [15/46]
bool SolidityAST.IASTVisitor.Visit (EventDefinition node)
Implemented in SolToBoogie.FunctionEventCollector, and SolidityAST.BasicASTVisitor.
Visit() [16/46]
bool SolidityAST.IASTVisitor.Visit (ExpressionStatement node)
Implemented in SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [17/46]
bool SolidityAST.IASTVisitor.Visit (ForStatement node)
Implemented in SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [18/46]
bool SolidityAST.IASTVisitor.Visit (FunctionCall node)
Implemented in SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [19/46]
bool SolidityAST.IASTVisitor.Visit (FunctionDefinition node)
Implemented in SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, SolToBoogie.FunctionEventCollector, and SolidityAST.BasicASTVisitor.
Visit() [20/46]
bool SolidityAST.IASTVisitor.Visit (Identifier node)
Implemented in SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [21/46]
bool SolidityAST.IASTVisitor.Visit (IfStatement node)
Implemented in SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, SolidityAST.BasicASTVisitor, and SolidityCFG.CFGBuilder.
Visit() [22/46]
bool SolidityAST.IASTVisitor.Visit (ImportDirective node)
Implemented in SolidityAST.BasicASTVisitor.
Visit() [23/46]
bool SolidityAST.IASTVisitor.Visit (IndexAccess node)
Implemented in SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [24/46]
bool SolidityAST.IASTVisitor.Visit (InheritanceSpecifier node)
Implemented in SolidityAST.BasicASTVisitor.
Visit() [25/46]
bool SolidityAST.IASTVisitor.Visit (InlineAssembly node)
Implemented in SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [26/46]
bool SolidityAST.IASTVisitor.Visit (Literal node)
Implemented in SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [27/46]
bool SolidityAST.IASTVisitor.Visit (Mapping node)
Implemented in SolidityAST.BasicASTVisitor.
Visit() [28/46]
bool SolidityAST.IASTVisitor.Visit (MemberAccess node)
Implemented in SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [29/46]
bool SolidityAST.IASTVisitor.Visit (ModifierDefinition node)
Implemented in SolToBoogie.ProcedureTranslator, SolidityAST.BasicASTVisitor, and SolToBoogie.ModifierCollector.
Visit() [30/46]
bool SolidityAST.IASTVisitor.Visit (ModifierInvocation node)
Implemented in SolidityAST.BasicASTVisitor.
Visit() [31/46]
bool SolidityAST.IASTVisitor.Visit (NewExpression node)
Implemented in SolidityAST.BasicASTVisitor.
Visit() [32/46]
bool SolidityAST.IASTVisitor.Visit (ParameterList node)
Implemented in SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [33/46]
bool SolidityAST.IASTVisitor.Visit (PlaceholderStatement node)
Implemented in SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [34/46]
bool SolidityAST.IASTVisitor.Visit (PragmaDirective node)
Implemented in SolidityAST.BasicASTVisitor.
Visit() [35/46]
bool SolidityAST.IASTVisitor.Visit (Return node)
Implemented in SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [36/46]
bool SolidityAST.IASTVisitor.Visit (SourceUnit node)
Implemented in SolToBoogie.SourceInfoCollector, and SolidityAST.BasicASTVisitor.
Visit() [37/46]
bool SolidityAST.IASTVisitor.Visit (SourceUnitList node)
Implemented in SolToBoogie.SourceInfoCollector, and SolidityAST.BasicASTVisitor.
Referenced by SolidityAST.SourceUnitList.Accept(), SolidityAST.SourceUnit.Accept(), SolidityAST.PragmaDirective.Accept(), SolidityAST.UsingForDirective.Accept(), SolidityAST.ImportDirective.Accept(), SolidityAST.ContractDefinition.Accept(), SolidityAST.InheritanceSpecifier.Accept(), SolidityAST.FunctionDefinition.Accept(), SolidityAST.ParameterList.Accept(), SolidityAST.ModifierDefinition.Accept(), SolidityAST.ModifierInvocation.Accept(), SolidityAST.EventDefinition.Accept(), SolidityAST.StructDefinition.Accept(), SolidityAST.EnumDefinition.Accept(), SolidityAST.EnumValue.Accept(), SolidityAST.VariableDeclaration.Accept(), SolidityAST.ElementaryTypeName.Accept(), SolidityAST.UserDefinedTypeName.Accept(), SolidityAST.Mapping.Accept(), SolidityAST.ArrayTypeName.Accept(), SolidityAST.Block.Accept(), SolidityAST.PlaceholderStatement.Accept(), SolidityAST.IfStatement.Accept(), SolidityAST.WhileStatement.Accept(), SolidityAST.DoWhileStatement.Accept(), SolidityAST.ForStatement.Accept(), SolidityAST.Continue.Accept(), SolidityAST.Break.Accept(), SolidityAST.Return.Accept(), SolidityAST.Throw.Accept(), SolidityAST.EmitStatement.Accept(), SolidityAST.VariableDeclarationStatement.Accept(), SolidityAST.InlineAssembly.Accept(), SolidityAST.ExpressionStatement.Accept(), SolidityAST.Literal.Accept(), SolidityAST.Identifier.Accept(), SolidityAST.ElementaryTypeNameExpression.Accept(), SolidityAST.UnaryOperation.Accept(), SolidityAST.BinaryOperation.Accept(), SolidityAST.Conditional.Accept(), SolidityAST.Assignment.Accept(), SolidityAST.TupleExpression.Accept(), SolidityAST.FunctionCall.Accept(), SolidityAST.NewExpression.Accept(), SolidityAST.MemberAccess.Accept(), and SolidityAST.IndexAccess.Accept().
Visit() [38/46]
bool SolidityAST.IASTVisitor.Visit (StructDefinition node)
Implemented in SolidityAST.BasicASTVisitor.
Visit() [39/46]
bool SolidityAST.IASTVisitor.Visit (Throw node)
Implemented in SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [40/46]
bool SolidityAST.IASTVisitor.Visit (TupleExpression node)
Implemented in SolidityAST.BasicASTVisitor.
Visit() [41/46]
bool SolidityAST.IASTVisitor.Visit (UnaryOperation node)
Implemented in SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [42/46]
bool SolidityAST.IASTVisitor.Visit (UserDefinedTypeName node)
Implemented in SolidityAST.BasicASTVisitor.
Visit() [43/46]
bool SolidityAST.IASTVisitor.Visit (UsingForDirective node)
Implemented in SolToBoogie.UsingCollector, and SolidityAST.BasicASTVisitor.
Visit() [44/46]
bool SolidityAST.IASTVisitor.Visit (VariableDeclaration node)
Implemented in SolToBoogie.MapArrayCollector, and SolidityAST.BasicASTVisitor.
Visit() [45/46]
bool SolidityAST.IASTVisitor.Visit (VariableDeclarationStatement node)
Implemented in SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
Visit() [46/46]
bool SolidityAST.IASTVisitor.Visit (WhileStatement node)
Implemented in SolToBoogie.SolidityDesugaring, SolToBoogie.ProcedureTranslator, and SolidityAST.BasicASTVisitor.
The documentation for this interface was generated from the following file:
Sources/SolidityAST/IASTVisitor.cs