VeriSol: SolidityAST.IASTGenericVisitor< T > Interface Template Reference
SolidityAST.IASTGenericVisitor< T > Interface Template Reference
Public Member Functions
T Visit (SourceUnitList node)
T Visit (SourceUnit node)
T Visit (PragmaDirective node)
T Visit (UsingForDirective node)
T Visit (ImportDirective node)
T Visit (ContractDefinition node)
T Visit (InheritanceSpecifier node)
T Visit (FunctionDefinition node)
T Visit (ParameterList node)
T Visit (ModifierDefinition node)
T Visit (ModifierInvocation node)
T Visit (EventDefinition node)
T Visit (StructDefinition node)
T Visit (EnumDefinition node)
T Visit (EnumValue node)
T Visit (VariableDeclaration node)
T Visit (ElementaryTypeName node)
T Visit (UserDefinedTypeName node)
T Visit (Mapping node)
T Visit (ArrayTypeName node)
T Visit (Block node)
T Visit (PlaceholderStatement node)
T Visit (IfStatement node)
T Visit (WhileStatement node)
T Visit (DoWhileStatement node)
T Visit (ForStatement node)
T Visit (Continue node)
T Visit (Break node)
T Visit (Return node)
T Visit (Throw node)
T Visit (EmitStatement node)
T Visit (VariableDeclarationStatement node)
T Visit (InlineAssembly node)
T Visit (ExpressionStatement node)
T Visit (Literal node)
T Visit (Identifier node)
T Visit (ElementaryTypeNameExpression node)
T Visit (UnaryOperation node)
T Visit (BinaryOperation node)
T Visit (Conditional node)
T Visit (Assignment node)
T Visit (TupleExpression node)
T Visit (FunctionCall node)
T Visit (NewExpression node)
T Visit (MemberAccess node)
T Visit (IndexAccess node)
Detailed Description
Definition at line 5 of file IASTGenericVisitor.cs.
Member Function Documentation
Visit() [1/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (ArrayTypeName node)
Visit() [2/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (Assignment node)
Visit() [3/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (BinaryOperation node)
Visit() [4/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (Block node)
Visit() [5/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (Break node)
Visit() [6/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (Conditional node)
Visit() [7/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (Continue node)
Visit() [8/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (ContractDefinition node)
Visit() [9/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (DoWhileStatement node)
Visit() [10/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (ElementaryTypeName node)
Visit() [11/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (ElementaryTypeNameExpression node)
Visit() [12/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (EmitStatement node)
Visit() [13/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (EnumDefinition node)
Visit() [14/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (EnumValue node)
Visit() [15/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (EventDefinition node)
Visit() [16/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (ExpressionStatement node)
Visit() [17/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (ForStatement node)
Visit() [18/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (FunctionCall node)
Visit() [19/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (FunctionDefinition node)
Visit() [20/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (Identifier node)
Visit() [21/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (IfStatement node)
Visit() [22/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (ImportDirective node)
Visit() [23/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (IndexAccess node)
Visit() [24/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (InheritanceSpecifier node)
Visit() [25/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (InlineAssembly node)
Visit() [26/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (Literal node)
Visit() [27/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (Mapping node)
Visit() [28/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (MemberAccess node)
Visit() [29/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (ModifierDefinition node)
Visit() [30/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (ModifierInvocation node)
Visit() [31/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (NewExpression node)
Visit() [32/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (ParameterList node)
Visit() [33/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (PlaceholderStatement node)
Visit() [34/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (PragmaDirective node)
Visit() [35/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (Return node)
Visit() [36/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (SourceUnit node)
Visit() [37/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (SourceUnitList node)
Referenced by SolidityAST.SourceUnitList.Accept< T >(), SolidityAST.SourceUnit.Accept< T >(), SolidityAST.PragmaDirective.Accept< T >(), SolidityAST.UsingForDirective.Accept< T >(), SolidityAST.ImportDirective.Accept< T >(), SolidityAST.ContractDefinition.Accept< T >(), SolidityAST.InheritanceSpecifier.Accept< T >(), SolidityAST.FunctionDefinition.Accept< T >(), SolidityAST.ParameterList.Accept< T >(), SolidityAST.ModifierDefinition.Accept< T >(), SolidityAST.ModifierInvocation.Accept< T >(), SolidityAST.EventDefinition.Accept< T >(), SolidityAST.StructDefinition.Accept< T >(), SolidityAST.EnumDefinition.Accept< T >(), SolidityAST.EnumValue.Accept< T >(), SolidityAST.VariableDeclaration.Accept< T >(), SolidityAST.ElementaryTypeName.Accept< T >(), SolidityAST.UserDefinedTypeName.Accept< T >(), SolidityAST.Mapping.Accept< T >(), SolidityAST.ArrayTypeName.Accept< T >(), SolidityAST.Block.Accept< T >(), SolidityAST.PlaceholderStatement.Accept< T >(), SolidityAST.IfStatement.Accept< T >(), SolidityAST.WhileStatement.Accept< T >(), SolidityAST.DoWhileStatement.Accept< T >(), SolidityAST.ForStatement.Accept< T >(), SolidityAST.Continue.Accept< T >(), SolidityAST.Break.Accept< T >(), SolidityAST.Return.Accept< T >(), SolidityAST.Throw.Accept< T >(), SolidityAST.EmitStatement.Accept< T >(), SolidityAST.VariableDeclarationStatement.Accept< T >(), SolidityAST.InlineAssembly.Accept< T >(), SolidityAST.ExpressionStatement.Accept< T >(), SolidityAST.Literal.Accept< T >(), SolidityAST.Identifier.Accept< T >(), SolidityAST.ElementaryTypeNameExpression.Accept< T >(), SolidityAST.UnaryOperation.Accept< T >(), SolidityAST.BinaryOperation.Accept< T >(), SolidityAST.Conditional.Accept< T >(), SolidityAST.Assignment.Accept< T >(), SolidityAST.TupleExpression.Accept< T >(), SolidityAST.FunctionCall.Accept< T >(), SolidityAST.NewExpression.Accept< T >(), SolidityAST.MemberAccess.Accept< T >(), and SolidityAST.IndexAccess.Accept< T >().
Visit() [38/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (StructDefinition node)
Visit() [39/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (Throw node)
Visit() [40/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (TupleExpression node)
Visit() [41/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (UnaryOperation node)
Visit() [42/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (UserDefinedTypeName node)
Visit() [43/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (UsingForDirective node)
Visit() [44/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (VariableDeclaration node)
Visit() [45/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (VariableDeclarationStatement node)
Visit() [46/46]
T SolidityAST.IASTGenericVisitor< T >.Visit (WhileStatement node)
The documentation for this interface was generated from the following file:
Sources/SolidityAST/IASTGenericVisitor.cs