var namespace_sol_to_boogie =
[
    [ "BoogieTranslator", "class_sol_to_boogie_1_1_boogie_translator.html", "class_sol_to_boogie_1_1_boogie_translator" ],
    [ "ConstructorCollector", "class_sol_to_boogie_1_1_constructor_collector.html", "class_sol_to_boogie_1_1_constructor_collector" ],
    [ "ContractCollector", "class_sol_to_boogie_1_1_contract_collector.html", "class_sol_to_boogie_1_1_contract_collector" ],
    [ "FallbackGenerator", "class_sol_to_boogie_1_1_fallback_generator.html", "class_sol_to_boogie_1_1_fallback_generator" ],
    [ "FunctionEventCollector", "class_sol_to_boogie_1_1_function_event_collector.html", "class_sol_to_boogie_1_1_function_event_collector" ],
    [ "FunctionEventResolver", "class_sol_to_boogie_1_1_function_event_resolver.html", "class_sol_to_boogie_1_1_function_event_resolver" ],
    [ "GhostVarAndAxiomGenerator", "class_sol_to_boogie_1_1_ghost_var_and_axiom_generator.html", "class_sol_to_boogie_1_1_ghost_var_and_axiom_generator" ],
    [ "HarnessGenerator", "class_sol_to_boogie_1_1_harness_generator.html", "class_sol_to_boogie_1_1_harness_generator" ],
    [ "HoudiniHelper", "class_sol_to_boogie_1_1_houdini_helper.html", "class_sol_to_boogie_1_1_houdini_helper" ],
    [ "InheritanceCollector", "class_sol_to_boogie_1_1_inheritance_collector.html", "class_sol_to_boogie_1_1_inheritance_collector" ],
    [ "MapArrayCollector", "class_sol_to_boogie_1_1_map_array_collector.html", "class_sol_to_boogie_1_1_map_array_collector" ],
    [ "MapArrayHelper", "class_sol_to_boogie_1_1_map_array_helper.html", "class_sol_to_boogie_1_1_map_array_helper" ],
    [ "ModifierCollector", "class_sol_to_boogie_1_1_modifier_collector.html", "class_sol_to_boogie_1_1_modifier_collector" ],
    [ "ModSetAnalysis", "class_sol_to_boogie_1_1_mod_set_analysis.html", "class_sol_to_boogie_1_1_mod_set_analysis" ],
    [ "ParseUtils", "class_sol_to_boogie_1_1_parse_utils.html", "class_sol_to_boogie_1_1_parse_utils" ],
    [ "ProcedureTranslator", "class_sol_to_boogie_1_1_procedure_translator.html", "class_sol_to_boogie_1_1_procedure_translator" ],
    [ "QVarGenerator", "class_sol_to_boogie_1_1_q_var_generator.html", "class_sol_to_boogie_1_1_q_var_generator" ],
    [ "ResolutionHelper", "class_sol_to_boogie_1_1_resolution_helper.html", "class_sol_to_boogie_1_1_resolution_helper" ],
    [ "RevertLogicGenerator", "class_sol_to_boogie_1_1_revert_logic_generator.html", "class_sol_to_boogie_1_1_revert_logic_generator" ],
    [ "SolidityDesugaring", "class_sol_to_boogie_1_1_solidity_desugaring.html", "class_sol_to_boogie_1_1_solidity_desugaring" ],
    [ "SourceInfoCollector", "class_sol_to_boogie_1_1_source_info_collector.html", "class_sol_to_boogie_1_1_source_info_collector" ],
    [ "StateVariableCollector", "class_sol_to_boogie_1_1_state_variable_collector.html", "class_sol_to_boogie_1_1_state_variable_collector" ],
    [ "StateVariableResolver", "class_sol_to_boogie_1_1_state_variable_resolver.html", "class_sol_to_boogie_1_1_state_variable_resolver" ],
    [ "TranslatorContext", "class_sol_to_boogie_1_1_translator_context.html", "class_sol_to_boogie_1_1_translator_context" ],
    [ "TranslatorFlags", "class_sol_to_boogie_1_1_translator_flags.html", "class_sol_to_boogie_1_1_translator_flags" ],
    [ "Extensions", "class_sol_to_boogie_1_1_extensions.html", "class_sol_to_boogie_1_1_extensions" ],
    [ "TransUtils", "class_sol_to_boogie_1_1_trans_utils.html", "class_sol_to_boogie_1_1_trans_utils" ],
    [ "UsingCollector", "class_sol_to_boogie_1_1_using_collector.html", "class_sol_to_boogie_1_1_using_collector" ]
];